### ISSUE TITLE
[kms]: Missing credentials leads to misleading exception and pointless retry loop

### ISSUE THREAD

**Issue by idontusenumbers** [googleapis/google-cloud-java#10224]
#### Environment details

1. Specify the API at the beginning of the title. For example, "[vision]: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: MacOS 14.1 (23B74)
3. Java version: 17.0.9 (Eclipse Adoptium 17.0.9+9)
4. Version(s):
```
com.google.auth:google-auth-library-oauth2-http:1.22.0
com.google.cloud:google-cloud-storage:2.31.0
```

#### Steps to reproduce

  1. Instantiate a KMS client without credentials and without logging in using gcloud command
  2. Attempt to create a key

#### Code example

```java
// example
```

#### Stack trace
```
io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:570)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.google.auth.oauth2.GoogleAuthException: com.google.api.client.http.HttpResponseException: 400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:127)
	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:143)
	at com.google.auth.oauth2.UserCredentials.doRefreshAccessToken(UserCredentials.java:272)
	at com.google.auth.oauth2.UserCredentials.refreshAccessToken(UserCredentials.java:177)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633)
	... 3 more
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
	at com.google.auth.oauth2.UserCredentials.doRefreshAccessToken(UserCredentials.java:270)
	... 8 more

```

#### Any additional information below
Seems like 'UNAUTHORIZED would be more appropriate here; some mention of the lack of credentials, instead of saying the credentials didn't work (implying they were supplied), would be helpful.

Additionally, the error seen here causes a retry loop eventually timing out. The original call blocks for quite some time until the client gives up retrying. It seems unlikely retrying makes sense for this sort of error.

**Comment by blakeli0** [comment]
@idontusenumbers Thanks for reporting this issue! I agree `UNAUTHORIZED` might be more appropriate here. However, I see that the exception is coming from gRPC library `io.grpc.StatusRuntimeException: UNAVAILABLE`, they may have good reasons to do so. + Auth library owner @TimurSadykov to provide more info.

For the retry behavior, I think it is working as intended because 
1. `UNAVAILABLE` is [configured](https://github.com/googleapis/googleapis/blob/master/google/cloud/kms/v1/cloudkms_grpc_service_config.json#L156-L165) to be retried.
2. `UNAVAILABLE` usually happens when there is an intermittent network issue, which most of time could be resolved automatically in subsequent retries.

**Comment by TimurSadykov** [comment]
@idontusenumbers Thanks for reporting, confirming that UNAUTHORIZED error is more appropriate here. There is a work planned for this in 2024, but no more specific ETA at the moment, we will update later.

**Comment by TimurSadykov** [comment]
@blakeli0 Can you please move this to auth-library-java repo?
