### ISSUE TITLE
[language]: exception while trying to create LanguageServiceClient instance

### ISSUE THREAD

**Issue by gilamsalem** [googleapis/google-cloud-java#10475]
#### Environment details

1. API: Language
2. OS type and version: Centos
3. Java version: 11
4. Version(s): google-cloud-language 2.2.0 and 2.37.0

#### Steps to reproduce

  1. Try to create LanguageServiceClient using the code sample below

#### Code example

```java
        LanguageServiceSettings settings = LanguageServiceSettings.newHttpJsonBuilder().build();
        client = LanguageServiceClient.create(settings);
```

#### Stack trace
```
Exception in thread "main" java.lang.VerifyError: class com.google.cloud.language.v1.stub.LanguageServiceStubSettings overrides final method com.google.api.gax.rpc.StubSettings.getEndpoint()Ljava/lang/String;
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.google.cloud.language.v1.LanguageServiceSettings$Builder.createHttpJsonDefault(LanguageServiceSettings.java:208)
	at com.google.cloud.language.v1.LanguageServiceSettings$Builder.access$100(LanguageServiceSettings.java:184)
	at com.google.cloud.language.v1.LanguageServiceSettings.newHttpJsonBuilder(LanguageServiceSettings.java:166)
```

Thanks!

**Comment by zhumin8** [comment]
I was not able to reproduce the error with Java 11 and google-cloud-language 2.37.0. 
Can you create a minimal reproducer if this persists for you?

**Comment by suztomo** [comment]
Ensure to use the GAX version higher than or equal to 2.32.0.

Similar error reported https://github.com/googleapis/google-cloud-java/issues/10604
