### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by LeeEleven11** [googleapis/google-cloud-java#11370]
Exception in thread "main" com.google.cloud.bigquery.BigQueryException: java.net.SocketTimeoutException: connect timed out
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:116)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:773)
	at com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1374)
	at com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1371)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:102)
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
	at com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1370)
	at com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1358)
	at com.google.cloud.bigquery.benchmark.Benchmark.main(Benchmark.java:55)

**Comment by mpeddada1** [comment]
@LeeEleven11 To help us understand the issue better, would you be able to provide additional details on:
- How often this occurs.
- The version of the library you're using. 
- If possible, a small code sample that reproduced this error.

**Comment by lqiu96** [comment]
Going to close this issue as there hasn't been a response in ~6 months. Feel free to re-open if this occurs again and if there is  more information provided. Thanks!
