### ISSUE TITLE
[java-datastore] Cloud Datastore Emulator doesn't support IN/NOT_IN/NOT_EQUAL operators

### ISSUE THREAD

**Issue by montss** [googleapis/google-cloud-java#12001]
googleapis/java-datastore#665 
com.google.cloud:libraries-bom:26.0.0

Gcloud SDK 394.0.0

#### Stack trace
```
com.google.cloud.datastore.DatastoreException: A list value is not allowed  A list value is not allowed
com.google.datastore.v1.client.DatastoreException: A list value is not allowed, code=INVALID_ARGUMENT  A list value is not allowed
com.google.datastore.v1.client.DatastoreException: A list value is not allowed, code=INVALID_ARGUMENT
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:171)
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:239)
	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:100)
	at com.google.datastore.v1.client.Datastore.runQuery(Datastore.java:117)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:198)
	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:195)
	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:192)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:191)
	at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:73)
	at com.google.cloud.datastore.QueryResultsImpl.<init>(QueryResultsImpl.java:57)
	at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:184)
	at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:175)
```

#### command used to run the emulator 
gcloud beta emulators datastore start --project="projectName" --host-port=localhost:8082 --data-dir="dataDir" --use-firestore-in-datastore-mode

####installed gcloud components 
Google Cloud SDK 394.0.0
app-engine-java 1.9.97
app-engine-python 1.9.100
beta 2022.07.19
bq 2.0.75
cloud-datastore-emulator 2.2.1
core 2022.07.19
gsutil 5.11

**Comment by mcamelot** [comment]
Hello, 

same issue, 

I see that this is specified here: https://docs.cloud.google.com/datastore/docs/tools/datastore-emulator

How can we work with Google Cloud Datastore if it's not possible to run it locally? 
Our code works in production, but not locally. 
How can we develop in such conditions? 
Does anyone have a workaround to work with count, in etc... ? 

Thank you very much.

**Comment by mehrajmalik-full** [comment]
This was reported in 2022 and we are in 2026, the issue still persists.
