### ISSUE TITLE
StorageException: 404 Not Found

### ISSUE THREAD

**Issue by swatijain1101** [googleapis/google-cloud-java#3402]
We make use of Google's JAVA client library to create storage client using which we get a particular blob by: storageClient.get(blobId).

We are facing an issue - calling the above method intermittently leads to "StorageException: 404 Not Found". Even when the objects exists and can be seen from console.

Below is the stack-trace: 
```
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT **Caused by: com.google.cloud.storage.StorageException: 404 Not Found**
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT No such object: <our object name - we would not want to disclose>
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.load(HttpStorageRpc.java:588) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl$16.call(StorageImpl.java:464) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl$16.call(StorageImpl.java:461) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89) ~[gax-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.RetryHelper.run(RetryHelper.java:74) ~[google-cloud-core-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51) ~[google-cloud-core-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl.readAllBytes(StorageImpl.java:461) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.Blob.getContent(Blob.java:455) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.sap.hcp.osaas.cfbroker.utils.GCPUtils.getBlob(GCPUtils.java:60) ~[classes/:?]

   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	... 89 more
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT **Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found**
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT No such object: <our object name we would not want to disclose>
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065) ~[google-http-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMedia(AbstractGoogleClientRequest.java:380) ~[google-api-client-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.services.storage.Storage$Objects$Get.executeMedia(Storage.java:6189) ~[google-api-services-storage-v1-rev114-1.23.0.jar!/:?]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.load(HttpStorageRpc.java:584) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl$16.call(StorageImpl.java:464) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl$16.call(StorageImpl.java:461) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89) ~[gax-1.23.0.jar!/:1.23.0]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.RetryHelper.run(RetryHelper.java:74) ~[google-cloud-core-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51) ~[google-cloud-core-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at com.google.cloud.storage.StorageImpl.readAllBytes(StorageImpl.java:461) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
   2018-06-25T15:25:38.58+0530 [APP/PROC/WEB/1] OUT 	at **com.google.cloud.storage.Blob.getContent**(Blob.java:455) ~[google-cloud-storage-1.24.1.jar!/:1.24.1]
```

Can there be anything that we might be missing? or is it an issue on the library side?

Thanks,
Swati Jain

**Comment by hzyi-google** [comment]
Hi Swati,

Can you provide a brief repro snippet?

**Comment by hzyi-google** [comment]
That seems to be the correct way to retrieve an object. I just noticed that this error happens intermittently. Can you provide more information to help debug? Thanks!

- How intermittent it is?
- Is the error that occurs at `blob.getContent()` always a `NOT_FOUND` or would it be `NullPointerException` or other type of errors in any case?
- Is there another client reading from or writing to the same bucket/blob?

**Comment by swatijain1101** [comment]
- As per our observation, it happens for the **first time after a long gap** (of may be 24 hours). After it fails, if we make the call again, it works fine.
- Also, what we observed is that the exception occurs when for the first time we do following operations one after the other as part of our use-case in a matter of few seconds-  

1. create the blob
2. update the blob
3. fetch the blob again
4. update it again

- Yes, the error occurs at `blob.getContent()` as is evident in the logs as well.

- When a blob exists in the bucket, we never came across any `NullPointerException'.

- We did not come across any other exception apart from the one that we have reported already.

- No other client is trying to read/update/delete the blob/bucket.

**Comment by hzyi-google** [comment]
So is the error happening in 3. fetch the blob again? Can you please describe what is updated during step 2? `storage.update()` can only update the metadata of a blob, but if the operation isn't finished on the server side yet, fetching the blob again might cause a 404.

**Comment by himanshujain18** [comment]
Hi @hzyi-google 
As mentioned by @swatijain1101 , by "updating the blob", we mean that we override the content of the blob by calling `storage.put()`  and not `storage.update()`. So, we are not updating the metadata of a blob, instead, we call `storage.put()` on the same blob and then call the `storage.get()` . This is where (step 3) as mentioned above, we get the 404.

**Comment by hzyi-google** [comment]
Hi @himanshujain18 ,
I don't see a `storage.put()` method in the current version of `google-cloud-storage`. Which version is the client library your are using?

**Comment by himanshujain18** [comment]
Hi @hzyi-google , I am sorry for the confusion. I mistakenly mentioned `storage.put()` method above. Its actually `storage.create()` method that we are using , which is for uploading a blob in the bucket. I have updated my earlier comment.

**Comment by hzyi-google** [comment]
Hi @himanshujain18 ,

Thanks for the update. There are a few things I can think of that might be causing the 404:

- Please make sure you are not using an outdated `blob` when calling `blob.getContent()`. i.e., 
```java
Blob blob = storage.create(blobInfo);
Blob updatedBlob = storage.create(blobInfo, byteArray);
blob.getContent();  // this would cause a 404
updatedBlob.getContent();  // the right way
```

- If the size of the contents is quite large, consider using [`blob.writer()`](https://googlecloudplatform.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html) instead of `storage.create()` for updating.

**Comment by himanshujain18** [comment]
Hi @hzyi-google ,
Thanks for clarifying above. But in our case we are not accessing an outdated blob. Once, the two steps are done as mentioned by you - 

    Blob blob = storage.create(blobInfo);
    Blob updatedBlob = storage.create(blobInfo, byteArray);

We perform `storage.get()` and then perform `blob.getContent()` to get the content of the blob. So, the flow is like this - 

    Blob blob = storage.create(blobInfo);
    Blob updatedBlob = storage.create(blobInfo, byteArray);
    Blob fetchedBlob = storage.get(blobId);
    // Here blobId is the blob id of the updatedBlob
    fetchedBlob.getContent(); // we got 404 as mentioned in the discussion above

**Comment by hzyi-google** [comment]
Hi @himanshujain18 ,

In this case can you try changing the second `create` to use `blob.writer()`? I'll check with the server side if that does not help. Thanks!

**Comment by BrandonY** [comment]
Hi @himanshujain18,

Is it possible that you have more than one process simultaneously operating on this object? If you were to call storage.get(), and then a second process deleted the object, and then the first process called getContent(), that first process could get a 404.

**Comment by chingor13** [comment]
Is this still happening? We haven't been able to reproduce this on our side with a single client doing the create and then get.

If it is still happening, feel free to reopen.

**Comment by samir-** [comment]
hello @hzyi-google @chingor13 
i had the same issue recently
what i did is create a file with this : 
`STORAGE.create(
                                    BlobInfo
                                            .newBuilder(BlobId.of(bucketName, tempPath))
                                            .setContentType("text/plain")
                                            .build(),
                                    chunk.getBytes());

`
and i did a request compose like this 
`
                            ComposeRequest request =
                                    ComposeRequest.newBuilder()
                                            .setTarget(targetBlob)
                                            .addSource(eventsPath)
                                            .addSource(tempPath)
                                            .build();
                            STORAGE.compose(request);`
this code runs on dataflow job that process > 80K files, i got the 404 error on only 1 file .
but apparently there is some retry process so it did write my file in the end.
Do you have any explanation why this can happen if the 2 codes are sequential ? 
Thanks

**Comment by sduskis** [comment]
@JesseLovelace @frankyn: any help would be appreciated.

**Comment by frankyn** [comment]
Hi @samir- ,

Thanks for raising your question.

General questions:
1. Are you able to consistently reproduce this issue?
2. Could you provide more context on your Dataflow pipeline, and the shortest code snippet so we can reproduce the issue?


Based on what you've provided, it looks like you're concatenating a new blob located at `tempPath`.

1. Is the code using a unique path for every new object created before performing a compose operation?
2. Is there a delete operation happening during your pipeline? 

```java
STORAGE.create(BlobInfo
        .newBuilder(BlobId.of(bucketName, tempPath))
        .setContentType("text/plain")
        .build(),
        chunk.getBytes());

ComposeRequest request =
         ComposeRequest.newBuilder()
        .setTarget(targetBlob)
        .addSource(eventsPath)
        .addSource(tempPath)
        .build();

STORAGE.compose(request);
```

**Comment by samir-** [comment]
Hello @frankyn 
**Are you able to consistently able reproduce this issue?**

No it's rare in fact, 3 or 2 times in total 
**Could you provide more context on your Dataflow pipeline and the shortest code snippet so we can reproduce the issue?**

This issue is random, Trying to reproduce it in my case would be runninng a pipeline that reads millions of rows in bigquery and grouping them to create strings. after that i store them in a bucket. I used the native storage library to do that instead of storage sink IO in dataflow, The compose request is used to build files with sum of chars that exceeds java array size limitation [2^32].

this code shows how it's done basically : 
- create the target file
- loop to create a temp file
- compose the temp file with target file
- delete temp file
- repeat

`       
                   Public void processElement(@Element KV<String, List<String>> element) {

                        String bucketName = bucket.get();
                        String eventsPath = element.getKey() + "/" + date.get() + "/events.csv";
                        BlobId blobId = BlobId.of(bucketName, eventsPath);
                        String tempPath = element.getKey() + "/" + date.get() + "/temp_events.csv";
                        BlobId blobIdTemp = BlobId.of(bucketName, tempPath);

                        BlobInfo targetBlob = deleteGcsFile(bucketName, eventsPath, blobId);
                        createGcsFile(bucketName, eventsPath);

                        for (String chunk : element.getValue()) {
                            STORAGE.create(
                                    BlobInfo
                                            .newBuilder(BlobId.of(bucketName, tempPath))
                                            .setContentType("text/plain")
                                            .build(),
                                    chunk.getBytes());

                            ComposeRequest request =
                                    ComposeRequest.newBuilder()
                                            .setTarget(targetBlob)
                                            .addSource(eventsPath)
                                            .addSource(tempPath)
                                            .build();
                            STORAGE.compose(request);
                            STORAGE.delete(blobIdTemp);
                        }
                    }
}
`

**Is the code using a unique path for every new object created before performing a compose operation?**

yes exactly

**Is there a delete operation in your pipeline?**

Yes

**The error** 

Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "No such object: my target file",
    "reason" : "notFound"
  } ],
  "message" : "No such object: my target file"
}
