### ISSUE TITLE
Compute v1: NPE in iterateAll()

### ISSUE THREAD

**Issue by yonran** [googleapis/google-cloud-java#3736]
Using `"com.google.cloud" % "google-cloud-compute" % "0.63.0-alpha"`, `com.google.api.gax.paging.AbstractPagedListResponse.iterateAll().iterator()` throws `NullPointerException` when there are no results:

Using scala console:

```scala
import com.google.cloud.compute.v1._
import com.google.cloud.ServiceOptions

val zone = ProjectZoneName.of(ServiceOptions.getDefaultProjectId(), "us-west1-a")
val instanceClient: InstanceClient = InstanceClient.create()
val diskClient: DiskClient = DiskClient.create()

instanceClient.listInstances(ListInstancesHttpRequest.newBuilder()
  .setZone(zone.toString())
  .setFilter("labels.app=nonexistant")
  .build()
).iterateAll().iterator()

diskClient.listDisks(ListDisksHttpRequest.newBuilder()
  .setZone(zone.toString())
  .setFilter(s"labels.app=nonexistant status=READY")
  .build()
).iterateAll().iterator()
```
throws
```
java.lang.NullPointerException
  at com.google.api.gax.paging.AbstractPage$AllResourcesIterator.<init>(AbstractPage.java:168)
  at com.google.api.gax.paging.AbstractPage$AllResourcesIterator.<init>(AbstractPage.java:162)
  at com.google.api.gax.paging.AbstractPage$2.iterator(AbstractPage.java:136)
  ... 47 elided
```

Possibly related to #2973

**Comment by ajaaym** [comment]
This is fixed.
