### ISSUE TITLE
Listing redacted BigQuery jobs results in an NPE

### ISSUE THREAD

**Issue by bmenasha** [googleapis/google-cloud-java#3739]
When run without "bigquery.jobs.listAll"  permissions on a project   (like "Viewer")  that contains other user's jobs this program results in an NPE .   

package com.bmenasha;

import com.google.cloud.Page;
import com.google.cloud.bigquery.BigQuery;
import com.google.cloud.bigquery.BigQueryOptions;
import com.google.cloud.bigquery.Job;

public class Main {
    public static void main(String[] args){
        BigQuery service = BigQueryOptions.builder().projectId(args[0]).build().service();
        Page<Job> jobPage = service.listJobs(BigQuery.JobListOption.allUsers());
        for(Job job: jobPage.values()){
            System.out.println("status:" + job.status());
        }
    }
}

Exception in thread "main" java.lang.NullPointerException
	at com.google.cloud.bigquery.JobConfiguration.fromPb(JobConfiguration.java:132)
	at com.google.cloud.bigquery.JobInfo$BuilderImpl.<init>(JobInfo.java:166)
	at com.google.cloud.bigquery.Job.fromPb(Job.java:264)
	at com.google.cloud.bigquery.BigQueryImpl$19.apply(BigQueryImpl.java:498)
	at com.google.cloud.bigquery.BigQueryImpl$19.apply(BigQueryImpl.java:495)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.bmenasha.Main.main(Main.java:16)

BigQuery is redacting the metadata from these jobs as described here: 

https://cloud.google.com/bigquery/docs/managing-jobs

The libraries should be able to parse these redacted job responses and not error when the metadata is missing.
thanks

**Comment by bmenasha** [comment]
Additionally it should be possible to list BigQuery jobs and be selective about the returned fields... currently we demand that the job's configuration always be returned via JobField.REQUIRED_FIELDS.  

When listing many jobs this field can be large. The client library overriding my choice and requesting that this field not be returned.

**Comment by sombra-mykola-bakay** [comment]
@bmenasha,
gcloud-java-bigquery is previous artifact id 
Latest version distributed under this artifact is 0.2.8

Current artifact id is google-cloud-bigquery

Latest version dependency:
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-bigquery</artifactId>
  <version>1.46.0</version>
</dependency>

Could you please try to reproduce with latest version?

Will try to reproduce too

**Comment by bmenasha** [comment]
Yes... occurs in  

    <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-bigquery</artifactId>
        <version>1.46.0</version>
    </dependency>

thanks

**Comment by PoriLisa** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.cloud.bigquery.JobConfiguration com.google.cloud.bigquery.JobConfiguration.setProjectId(java.lang.String)' on a null object reference
