### ISSUE TITLE
Cloud Vision API - Authentication using API Key

### ISSUE THREAD

**Issue by anuragkapur** [googleapis/google-cloud-java#3763]
Using an API key with the `https://vision.googleapis.com/v1/images:annotate` endpoint via curl works as expected which means API keys can be used with the cloud vision API.

As per discussion here https://github.com/googleapis/google-cloud-java/issues/1405 supplying a `GOOGLE_API_KEY` environment variable while ensuring no `GOOGLE_APPLICATION_CREDENTIALS` variable is set should mean that API key based authentication should be used by the client lib. However the following code:

```java
class GCPCloudVisionClient {

    public void initialiseClient() throws IOException {
        ImageAnnotatorClient imageAnnotatorClient = ImageAnnotatorClient.create();
    }

    public static void main(String[] args) {
        GCPCloudVisionClient gcpCloudVisionClient = new GCPCloudVisionClient();
        try {
            gcpCloudVisionClient.initialiseClient();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
``` 

fails with the following exception
```text
java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:131)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:127)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:100)
	at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:59)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:132)
	at com.google.cloud.vision.v1.stub.GrpcImageAnnotatorStub.create(GrpcImageAnnotatorStub.java:84)
	at com.google.cloud.vision.v1.stub.ImageAnnotatorStubSettings.createStub(ImageAnnotatorStubSettings.java:120)
	at com.google.cloud.vision.v1.ImageAnnotatorClient.<init>(ImageAnnotatorClient.java:136)
	at com.google.cloud.vision.v1.ImageAnnotatorClient.create(ImageAnnotatorClient.java:117)
	at com.google.cloud.vision.v1.ImageAnnotatorClient.create(ImageAnnotatorClient.java:108)
```

Does this indicate a bug in the client library where in it doesn't use the API key supplied as expected?

**Comment by ajaaym** [comment]
Translate is apiary based client(also that solution only applied to translate don't know why), while vision uses grpc transport. GRPC transport needs proper authentication as described in [readme](https://github.com/googleapis/google-cloud-java#authentication) Closing this issue for now. Please reopen if you need further help.
