### ISSUE TITLE
Firestore authentication doesn't work

### ISSUE THREAD

**Issue by Qi77Qi** [googleapis/google-cloud-java#3872]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS:
- Java version: 1.8
- google-cloud-java version(s):

#### Steps to reproduce

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

import com.google.auth.oauth2.ServiceAccountCredentials
import java.io.FileInputStream
import com.google.cloud.firestore.{Firestore, FirestoreOptions}
FirestoreOptions
    .newBuilder()
    .setCredentials(ServiceAccountCredentials.fromStream(new FileInputStream("/Users/qi/.google/workbench-firestore-ce9e54f3c762.json")))
    .build()
    .getService

// Exiting paste mode, now interpreting.

java.lang.NoSuchFieldError: transportTracerFactory
  at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:335)
  at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:325)
  at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:246)
  at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:160)
  at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:152)
  at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:149)
  at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:114)
  at com.google.cloud.firestore.spi.v1beta1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:122)
  at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:80)
  at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:72)
  at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:512)
  at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:315)
  at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:76)
  at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:63)
  at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:56)
  at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:499)
  ... 44 elided
```

#### Stacktrace

```
Any relevant stacktrace here.
```

#### Code snippet

```java
Any relevant code snippet to help reproduce the issue.
```

#### External references such as API reference guides used

- ?

#### Any additional information below

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by JustinBeckwith** [comment]
Heads up @schmidt-sebastian @JesseLovelace - this one has a support ticket associated :) @schmidt-sebastian I'm not sure who has done the firestore Java work to this point, but I'm guessing it's you 🤣

**Comment by schmidt-sebastian** [comment]
From the dependency tree that we have received over email, it looks like their project is pulling in GRPC `io.grpc:grpc-core:1.5.0`, which gets mixed with other GRPC libraries that Firestore pulls in. Firestore 0.68 uses GRPC 1.15, and most other GRPC libraries in the dependency tree are at this version.

@Qi77Qi Can you let us know if upgrading to GRPC 1.15 solves your issue?

**Comment by Qi77Qi** [comment]
Just to give an update. I was able to get things working locally with grpc 1.15. But it's hard for me to tell if everything is backward compatible yet since other parts of the project was using grpc 1.5. I'll report back if there's more issue. Thanks for the attention.
