### ISSUE TITLE
StringEnumValue does not support reference equality after Serialization

### ISSUE THREAD

**Issue by pmkc** [googleapis/google-cloud-java#3942]
#### Environment details

- OS: Linux (Debian 9)
- Java version: openjdk version "1.8.0_181"
- google-cloud-java version(s): 1.52.0

#### Steps to reproduce

1. Serialize StringEnumValue 
2. Deserialize StringEnumValue
3. Use it in a way that requires reference equality
4. Crash

#### Stacktrace

```
Exception in thread "main" java.lang.IllegalArgumentException: Only RECORD fields can have sub-fields
        at com.google.cloud.bigquery.Field$Builder.setType(Field.java:137)
        at com.google.cloud.bigquery.Field.newBuilder(Field.java:275)
        at com.google.cloud.bigquery.Field.of(Field.java:261)
        at App.main(App.java:27)
```

#### Code snippet

```java
LegacySQLTypeName record = SerializationUtils.clone(LegacySQLTypeName.RECORD);
System.out.println(LegacySQLTypeName.RECORD == record); // false
Field.of("foo", record, Field.of("bar", LegacySQLTypeName.BOOLEAN)); // throws
```

**Comment by bsidhom** [comment]
Representing these values as standard Java enums would provide (de)serialization-safe reference equality for free. Why not use enums? StringEnumValue has a doc comment that indicates enums don't work due to the need to extend values later. What exactly does this mean and why can't this functionality be provided as a method on standard enum types?

**Comment by pmkc** [comment]
I don't think this is a BigQuery client issue.

The BigQuery client simply tripped over the underlying issue that StringEnumValue isn't safe.
