### ISSUE TITLE
BigQuery client throws NullPointerException when estimatedFields is empty

### ISSUE THREAD

**Issue by lgajowy** [googleapis/google-cloud-java#3982]
#### Environment details

- OS: linux /macos
- Java version: 8
- google-cloud-java version(s): ???

#### Steps to reproduce

1. Run the following code:

```java
BigQueryOptions options = BigQueryOptions.newBuilder().build();
BigQuery client = options.getService();

TableId tableId = TableId.of(projectId, dataset, tableName);

// no options - all table fields are fetched
client.getTable(tableId);
```

#### Stacktrace

```
Exception in thread "main"
java.lang.NullPointerException
at com.google.cloud.bigquery.StandardTableDefinition$StreamingBuffer.fromPb(StandardTableDefinition.java:116)
at com.google.cloud.bigquery.StandardTableDefinition.fromPb(StandardTableDefinition.java:225)
at com.google.cloud.bigquery.TableDefinition.fromPb(TableDefinition.java:155)
at com.google.cloud.bigquery.TableInfo$BuilderImpl.<init>(TableInfo.java:183)
at com.google.cloud.bigquery.Table.fromPb(Table.java:593)
at com.google.cloud.bigquery.BigQueryImpl.getTable(BigQueryImpl.java:410)
at org.apache.beam.sdk.testutils.publishing.BigQueryClient.createTableIfNotExists(BigQueryClient.java:74)
at org.apache.beam.sdk.nexmark.Main.savePerfsToBigQuery(Main.java:184)
at org.apache.beam.sdk.nexmark.Main.runAll(Main.java:148)
at org.apache.beam.sdk.nexmark.Main.runAll(Main.java:98)
at org.apache.beam.sdk.nexmark.Main.main(Main.java:423)
```

#### Any additional information below

This happens only if table.streamingBuffer.estimatedFields field is null in table. This is not allways the case but when it is null the exception appears. 

See more info here: https://issues.apache.org/jira/browse/BEAM-6076

Thanks!

**Comment by ajaaym** [comment]
@chingor13 One of the similar issue [1131](https://github.com/googleapis/google-cloud-java/issues/1131) is fixed by changing variable type to Long and adding not null check. Do we do same thing for both of estimatedSize & estimatedRows field or should we set to 0 if its not present in the response, I think setting it to 0 or -1 would make sense, WDYT?

**Comment by lgajowy** [comment]
Thanks for fixing this! :)
