### ISSUE TITLE
DataProc com.google.cloud.dataproc.v1.ClusterControllerClient.getCluster supports only region global

### ISSUE THREAD

**Issue by yohayg** [googleapis/google-cloud-java#4016]
DataProc com.google.cloud.dataproc.v1.ClusterControllerClient.getCluster supports only region global.
It should support other regions as well.
I cannot get the cluster details using Java API for clusters on regions other than global.

#### Environment details

- OS: mac OS mojave
- Java version: jdk1.8.0_151
- google-cloud-java version(s):
- google-cloud-dataproc version: 0.71.0-alpha
- google-api-services-compute version: v1-rev201-1.24.1

#### Steps to reproduce

1. Invoke the following method with the path to service account json, name of the cluster, project id, region
2. You will get this error.
3. Change to region to global and no error will appear

#### Stacktrace

```
Exception in thread "main" com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Region 'us-west1' is invalid. Please see https://cloud.google.com/dataproc/docs/concepts/regional-endpoints for additional information on regional endpoints
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.dataproc.v1.ClusterControllerClient.getCluster(ClusterControllerClient.java:567)
		at co.cask.cdap.runtime.spi.provisioner.dataproc.DataprocTool.getCluster(DataprocTool.java:276)
		at co.cask.cdap.runtime.spi.provisioner.dataproc.DataprocTool.main(DataprocTool.java:130)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Region 'us-west1' is invalid. Please see https://cloud.google.com/dataproc/docs/concepts/regional-endpoints for additional information on regional endpoints
	at io.grpc.Status.asRuntimeException(Status.java:526)
	... 24 more
```

#### Code snippet

```java
public static void getCluster(String accountKeyJsonFilePath, String name, String projectId, String region) throws IOException {
    String accountKey = new String(Files.readAllBytes(
            new File(accountKeyJsonFilePath).toPath()));
    GoogleCredentials credentials;
    try (InputStream is = new ByteArrayInputStream(accountKey.getBytes(StandardCharsets.UTF_8))) {
      credentials = GoogleCredentials.fromStream(is);
    }
    CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(credentials);

    ClusterControllerSettings controllerSettings = ClusterControllerSettings.newBuilder()
            .setCredentialsProvider(credentialsProvider)
            .build();
    try (ClusterControllerClient client = ClusterControllerClient.create(controllerSettings)) {

      com.google.cloud.dataproc.v1.Cluster cluster = client.getCluster(GetClusterRequest.newBuilder()
              .setClusterName(name)
              .setProjectId(projectId)
              .setRegion(region)
              .build());
      System.out.println(cluster.getConfig());
    }
  }
```

#### External references such as API reference guides used

- https://developers.google.com/resources/api-libraries/documentation/dataproc/v1/java/latest/com/google/api/services/dataproc/Dataproc.Projects.Regions.Clusters.Get.html

**Comment by sduskis** [comment]
This looks like a service problem.  @aniket486 can you help triage this issue?

**Comment by bsidhom** [comment]
Note that the service does support regions, but this requires clients to manually set regional endpoints.

For example,

```java
String regionalEndpoint = "us-central1-dataproc.googleapis.com:443";
ClusterControllerSettings controllerSettings = ClusterControllerSettings.newBuilder()
            .setCredentialsProvider(credentialsProvider)
            .setEndpoint(regionalEndpoint)
            .build();
```

This is documented at https://cloud.google.com/dataproc/docs/concepts/regional-endpoints, but it might make sense to make this easier to discover/use in the client library.
