### ISSUE TITLE
Exception in thread "Thread-4" com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by SebRut** [googleapis/google-cloud-java#4203]
I am trying to access a list of intents for a dialogflow project using a service json file. Running my program on my development MacBooks works flawlessly but using the same .jar on the target machines running Windows fails with the exception detailed below.
#### Environment details

- OS: Windows 7 64bit
- Java version:
`java version "1.8.0_131"`
`Java(TM) SE Runtime Environment (build 1.8.0_131-b11)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)`
- google-cloud-java version(s):
`com.google.cloud:google-cloud-dialogflow:0.70.0-alpha`

#### Stacktrace

```
Exception in thread "Thread-4" com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:69)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:634)
at com.google.common.util.concurrent.ForwardingListenableFuture.addListener(ForwardingListenableFuture.java:45)
at com.google.api.core.ApiFutureToListenableFuture.addListener(ApiFutureToListenableFuture.java:52)
at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1135)
at com.google.api.core.ApiFutures.addCallback(ApiFutures.java:63)
at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:67)
at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:81)
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
```

#### Code snippet
_Setup code_
```java
ServiceAccountCredentials credentials = ServiceAccountCredentials.fromStream(new FileInputStream(serviceJsonPath));
IntentsSettings settings = IntentsSettings.newBuilder().setCredentialsProvider(FixedCredentialsProvider.create(credentials)).build();
```

_The program fails somewhere here_
```java
IntentsClient client = IntentsClient.create(settings);
Iterable<Intent> intents = client.listIntents(String.format("projects/%s/agent", projectId)).iterateAll();
```

#### External references such as API reference guides used

- https://dialogflow.com/docs/reference/api-v2/rest/v2/projects.agent.intents/list

#### Any additional information below

The Windows machine needs a proxy to connect to the internet which I configured using `http.proxyHost`, `http.proxyPort`, `https.proxyHost` and `https.proxyPort`.

**Comment by ajaaym** [comment]
can you add log level to FINE and send long?

**Comment by lv-alex** [comment]
hi, is there any resolution to this? We are able to run DialogFlow(w/wo knowledgeBase) without issues if it runs as a Java application. As soon as we migrate it under a Web app, it starts having issues. Could you please try to run this under a Java web app(Dynamic Web application)?


If synchronous:

Mar 20, 2019 9:03:51 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [servletName] in context with path [/kbb] threw exception
com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)



If Async:
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:531)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:492)
	at com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:56)


Code :
Async (sync is commented out)

		QueryParameters queryParameters = null;
		
		TextInput textInput = TextInput.newBuilder()
	        .setLanguageCode(languageCode)
	        .setText(queryText)
	        .build();
		
		QueryInput queryInput;
		if (eventName != null){
			com.google.cloud.dialogflow.v2beta1.EventInput ei = com.google.cloud.dialogflow.v2beta1.EventInput.newBuilder()
					.setName(eventName)
					.setLanguageCode(languageCode)
					.setParameters(accountData)
					.build();

			queryInput = QueryInput.newBuilder()
		    		.setText(textInput)
		    		.setEvent(ei)
		    		.build();

		}
		else{
			queryInput = QueryInput.newBuilder()
	    		.setText(textInput)
	    		.build();
			
			if (knowledgeBaseName != null){
		        queryParameters = QueryParameters.newBuilder()
		            .addKnowledgeBaseNames(knowledgeBaseName)    
		            .build();
			}
		}
		
		DetectIntentRequest request = null;
        if (queryParameters != null){
		    // Build the DetectIntentRequest
		    request = DetectIntentRequest.newBuilder()
		        //projects/<Project ID>/agent/sessions/<Session ID>
				.setSession(sessionId)
		        .setQueryInput(queryInput)
		        .setQueryParams(queryParameters)
		        .build();		
        }
        else{
		    request = DetectIntentRequest.newBuilder()
			        //projects/<Project ID>/agent/sessions/<Session ID>
					.setSession(sessionId)
			        .setQueryInput(queryInput)
			        .build();
        }
        
        //sync
	    //DetectIntentResponse r = gcpVirtualAssistant.detectIntent(request);
	    	  
        //async
	    ApiFuture<DetectIntentResponse> future = gcpVirtualAssistant.detectIntentCallable().futureCall(request);
	    // Do something
    	try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    DetectIntentResponse r = null;
		try {
			r = future.get();
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ExecutionException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	    System.out.println("Client side");
		
		final Map<Descriptors.FieldDescriptor, Object> responseFields = r.getQueryResult().getAllFields();
		Map<String, Object> map = new LinkedHashMap<>();
		for (Map.Entry<Descriptors.FieldDescriptor, Object> entry : responseFields.entrySet()) {
		    final Descriptors.FieldDescriptor fieldDescriptor = entry.getKey();
		    logger.debug("key:"+fieldDescriptor.getJsonName() + " value:"+entry.getValue());
		    map.put(fieldDescriptor.getJsonName(), entry.getValue());
		}	    
		return map;


Libraries included:
	compile group: 'com.google.apis', name: 'google-api-services-dialogflow', version: 'v2-rev64-1.25.0'
	compile group: 'com.google.api.grpc', name: 'proto-google-cloud-dialogflow-v2', version: '0.48.0'
	compile group: 'com.google.api.grpc', name: 'grpc-google-cloud-dialogflow-v2beta1', version: '0.48.0'
	compile group: 'com.google.cloud', name: 'google-cloud-dialogflow', version: '0.83.0-alpha'
	

thank you

**Comment by jianxia612** [comment]
please not vpn access api
