### ISSUE TITLE
Spanner java api 1.0.0 - java.util.concurrent.RejectedExecutionException on createDatabase

### ISSUE THREAD

**Issue by cberez** [googleapis/google-cloud-java#4219]
Hello,

I'm trying to implement a Spanner utility package to wrap customary calls such as create/drop/update database/table for my project and I'm running into exceptions on Database creation with the 1.0.0 version of the library on a Scala project

I didn't find any reference to a 1.0.0 release on this repo but the jar is available on maven repositories and I'd prefer to avoid a beta version if possible. In the meantime I'm reverting to `v0.68.0-beta`.

I've seen references to the same exception in other issues but they were all old and closed.

#### Environment details

- OS: ArchLinux
- Java version: 1.8.0_112
- Scala version: 2.11.12
- google-cloud-spanner version(s): 1.0.0

#### Stacktrace

```
UNKNOWN: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4267c4d8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7f3fe94d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
com.google.cloud.spanner.SpannerException: UNKNOWN: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4267c4d8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7f3fe94d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:119)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:43)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:80)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:58)
	at com.google.cloud.spanner.SpannerImpl$DatabaseAdminClientImpl$2.apply(SpannerImpl.java:478)
	at com.google.cloud.spanner.SpannerImpl$DatabaseAdminClientImpl$2.apply(SpannerImpl.java:475)
	at com.google.api.core.ApiFutures$GaxFunctionToGuavaFunction.apply(ApiFutures.java:204)
	at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:206)
	at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:194)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:107)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:92)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:148)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:92)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:148)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:675)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:105)
	at com.google.common.util.concurrent.ForwardingListenableFuture.addListener(ForwardingListenableFuture.java:45)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture.setAttemptFuture(CallbackChainRetryingFuture.java:93)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:138)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4267c4d8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7f3fe94d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator.schedule(MoreExecutors.java:563)
	at com.google.api.gax.retrying.ScheduledRetryingExecutor.submit(ScheduledRetryingExecutor.java:116)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:137)
	... 42 more
```

#### Code snippet

```scala
val opts = SpannerOptions.newBuilder().build()
val spanner: Spanner = opts.getService
val dbClient: DatabaseAdminClient = spanner.getDatabaseAdminClient

val op: OperationFuture[Database, CreateDatabaseMetadata] = dbClient.createDatabase(instance, database, Iterable.empty[String])

try {
  op.get()
} catch {
  case e: ExecutionException   => throw e.getCause.asInstanceOf[SpannerException]
  case e: InterruptedException => throw SpannerExceptionFactory.propagateInterrupt(e)
}
```

#### External references such as API reference guides used

- https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/spanner/snippets/DatabaseAdminClientSnippets.java

#### Any additional information below

Thanks for your help!

**Comment by cberez** [comment]
Update (sorry for the spam): 

I just observed the same behaviour on v0.68.0 with the following code taken from the examples [here](https://github.com/googleapis/google-cloud-java/blob/v0.68.0/google-cloud-examples/src/main/java/com/google/cloud/examples/spanner/snippets/DatabaseAdminClientSnippets.java): 

```scala
val opts = SpannerOptions.newBuilder().build()
val spanner: Spanner = opts.getService
val dbClient: DatabaseAdminClient = spanner.getDatabaseAdminClient

val op: Operation[Database, CreateDatabaseMetadata] = dbClient.createDatabase(instance, database, Iterable.empty[String])

try {
  val db: Database = op.waitFor().getResult()
} catch {
  case e: ExecutionException   => throw e.getCause.asInstanceOf[SpannerException]
  case e: InterruptedException => throw SpannerExceptionFactory.propagateInterrupt(e)
}
```

Not doing the `.waitFor().getResult()` does not throw any exception and creates the database on v0.68  
Not doing the `.get()` does not throw any exception and the database is not created on v1.0.0

**Comment by charlesliqlogic** [comment]
@cberez  It seems like creating database without any Exceptions in both of your cases.

**Case1: Java1.8 , Scala 2.11.12, google-cloud-spanner 1.0.0**

```scala
  def main(args : Array[String]) {
    val opts = SpannerOptions.newBuilder().build()
    val spanner: Spanner = opts.getService
    val dbClient: DatabaseAdminClient = spanner.getDatabaseAdminClient
  	val instance = "INSTANCE"
    val database = "DATABASE"
    val op: OperationFuture[Database, CreateDatabaseMetadata] = dbClient.createDatabase(instance, database, new util.ArrayList[String]())
    try {
      op.get()
    } catch {
      case e: ExecutionException   => throw e.getCause.asInstanceOf[SpannerException]
      case e: InterruptedException => throw SpannerExceptionFactory.propagateInterrupt(e)
    }
  }
```

**Case2: Java1.8 , Scala 2.11.12, google-cloud-spanner v0.68.0-beta**

```scala
def main(args : Array[String]) {
    val opts = SpannerOptions.newBuilder().build()
    val spanner: Spanner = opts.getService
    val dbClient: DatabaseAdminClient = spanner.getDatabaseAdminClient
    val instance = "INSTANCE"
    val database = "DATABASE"
    val op: Operation[Database, CreateDatabaseMetadata] = dbClient.createDatabase(instance, database, util.Arrays.asList())
    try {
      val db: Database = op.waitFor().getResult()
    } catch {
      case e: ExecutionException   => throw e.getCause.asInstanceOf[SpannerException]
      case e: InterruptedException => throw SpannerExceptionFactory.propagateInterrupt(e)
    }
  }
```


If there are still issues, can you please provide complete dependency tree?

**Comment by ajaaym** [comment]
Closing this as it seems not an issue anymore. If this is still an issue please feel free to reopen with complete dependency tree.

**Comment by cberez** [comment]
Sorry didn't see the notification on your answer @charlesliqlogic 

I'll check again and re-open if I still have issues

**Comment by cberez** [comment]
Ok I juste tested with the 1.0.0 version and it now works, I can't reproduce the original problem

Thx for your input @charlesliqlogic !
