### ISSUE TITLE
Google PubSub Subscriber does not fail on Unauthenticated exception

### ISSUE THREAD

**Issue by qingwei91** [googleapis/google-cloud-java#4244]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS: Mac and Ubuntu-Linux
- Java version: 8
- google-cloud-java version(s): 1.40.0

#### Steps to reproduce

1. Run `com.google.cloud.pubsub.v1.Subscriber` as usual using FixedCredentialsProvider
2. Delete the credential
3. I am expecting it to **fail**, but it does not seems to fail, just printing lots of error messages, is this by design?

#### Stacktrace

```
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

#### Code snippet

I am running in Scala, but I doubt it matters
```scala
      val subscriber = Subscriber
        .newBuilder(subscriptionName, messageReceiver)
        .setCredentialsProvider(credentialsProvider)
        .setFlowControlSettings(flowControl)
        .build()

      val done = subscriber.startAsync()
      done.awaitTerminated()
```

Thanks!

**Comment by kolea2** [comment]
Have you tried implementing a listener on your subscriber to handle the state?
`subscriber.addListener(...)`

You could also try checking the status of the subscriber after starting the async worker.

**Comment by qingwei91** [comment]
Hi @kolea2 

I've tried adding listener, but it was not triggered as well, I think the subscriber does not enter `FAILED` state

**Comment by kolea2** [comment]
Hi @qingwei91, I tried reproducing this and was able to get this to enter the failed state. I created a subscriber with valid credentials, saw no errors. I then deleted the credentials, reran, and saw the same error you did and it entering the failed state. To highlight, here's a piece of my listener code (in Java):

 ```
subscriber.addListener(new Subscriber.Listener() {
         @Override
         public void failed(ApiService.State from, Throwable failure) {
              System.out.println("Failed");
         }
         ...
```

My error message is the same as what you posted above, and I can see "Failed" being printed to the console. Any other information or steps I could be missing to help debug this?

**Comment by qingwei91** [comment]
@kolea2 Thanks for putting in effort, can you try to let it continue running instead of rerunning it ?

I can confirm the program throws exception when it starts with invalid credentials, but what if I remove the credentials without restarting the program?

so far my observation is that it prints out error message, but it does not fail the main program even after 5 minutes

**Comment by kolea2** [comment]
Sure - I ran again with valid credentials, no issues, deleted them, and then did get into the failure state with the `UnauthenticatedException` stack trace (without stopping and rerunning). I noticed you're using version 1.40.0 - can you try upgrading the library? I'm using version 1.56.0 for Pub/Sub. Hope that helps!
