### ISSUE TITLE
Pubsub: change in behaviour for synchronous pull?

### ISSUE THREAD

**Issue by bruceskingle** [googleapis/google-cloud-java#4246]
I have an application which uses the synchronous pull method for pubsub.

There seems to have been a change in behaviour in the case where there are no messages on the subscription between 1.33.0 and 1.56.0

With the old library I get a normal return (with zero messages) after 15-20 seconds or so. With the new library I get nothing for 10 minutes and then the exception stack trace below.

Is this intentional and if so is it documented anywhere (I can't find anything to this effect)?

Since the exception is a GRPC exception and that's an internal implementation detail I assume it must be a bug, please advise.

Thanks,
Bruce.

```
13:41:09.218 [PubSub-subscriber-1] ERROR org.symphonyoss.s2.fugue.pubsub.AbstractPullSubscriber - Error processing message
com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 11999627952ns
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:51) ~[gax-1.35.1.jar:1.35.1]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) ~[gax-grpc-1.35.1.jar:1.35.1]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) ~[gax-grpc-1.35.1.jar:1.35.1]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) ~[gax-grpc-1.35.1.jar:1.35.1]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) ~[api-common-1.7.0.jar:?]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1371) ~[guava-23.5-jre.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:397) ~[guava-23.5-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1016) ~[guava-23.5-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:867) ~[guava-23.5-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:713) ~[guava-23.5-jre.jar:?]
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:492) ~[grpc-stub-1.10.1.jar:1.10.1]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467) ~[grpc-stub-1.10.1.jar:1.10.1]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.16.1.jar:1.16.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.16.1.jar:1.16.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) ~[gax-1.35.1.jar:1.35.1]
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) ~[gax-1.35.1.jar:1.35.1]
		at org.symphonyoss.s2.fugue.google.pubsub.GoogleSubscriber$GooglePullSubscriberContext.pull(GoogleSubscriber.java:171) ~[classes/:?]
		at org.symphonyoss.s2.fugue.google.pubsub.GoogleSubscriber$GooglePullSubscriberContext.blockingPull(GoogleSubscriber.java:164) ~[classes/:?]
		at org.symphonyoss.s2.fugue.pubsub.AbstractPullSubscriber.getSomeMessages(AbstractPullSubscriber.java:110) [classes/:?]
		at org.symphonyoss.s2.fugue.pubsub.AbstractPullSubscriber.getSomeMessages(AbstractPullSubscriber.java:79) [classes/:?]
		at org.symphonyoss.s2.fugue.pubsub.AbstractPullSubscriber.run(AbstractPullSubscriber.java:222) [classes/:?]
		at org.symphonyoss.s2.fugue.pubsub.AbstractPullSubscriber.run(AbstractPullSubscriber.java:209) [classes/:?]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 11999627952ns
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.16.1.jar:1.16.1]
	... 23 more
```

**Comment by stetra** [comment]
I also encountered this issue. I believe this change in behavior was introduced in [1.45.0](https://github.com/googleapis/google-cloud-java/blob/7a43f6fa43cf186bab16e16db7f83abb7418aaf1/google-cloud-clients/google-cloud-pubsub/pom.xml), due to the transitive dependency on com.google.api:gax (through com.google.cloud:google-cloud-core) moving from 1.31.0 to 1.32.0. [1.32.0](https://github.com/googleapis/gax-java/releases/tag/v1.32.0) changed the timeout on the initial RPC request to correctly use the initial timeout instead of the total timeout. Unfortunately the default initial RPC timeout (and max RPC timeout) is [12 seconds](https://github.com/googleapis/google-cloud-java/blob/7a43f6fa43cf186bab16e16db7f83abb7418aaf1/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java#L512), so a synchronous pull will fail with DEADLINE_EXCEEDED since the response takes ~20 seconds if there's no pending messages.

The easiest fix is probably to increase the timeouts like so:

    SubscriberStubSettings.Builder settingsBuilder = SubscriberStubSettings.newBuilder();
    settingsBuilder.pullSettings().setSimpleTimeoutNoRetries(Duration.ofSeconds(60));
    SubscriberStubSettings settings = settingsBuilder.build();
    SubscriberStub subscriber = GrpcSubscriberStub.create(settings);

**Comment by ajaaym** [comment]
seems like same issue as #4220

**Comment by bruceskingle** [comment]
The fix provided by @stetra works for me, thank you.
