### ISSUE TITLE
BigQuery: client.insert_rows doesn't handle nested schemas

### ISSUE THREAD

**Issue by adamf** [googleapis/google-cloud-java#4248]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS: Any
- Java version: N/A - it's python (3.5)
- google-cloud-java version(s): 1.8.1 (pypi)

#### Steps to reproduce

1. Created a nested schema:

```
[
  {
    "mode": "NULLABLE",
    "name": "timestamp",
    "type": "TIMESTAMP"
  },
  {
    "mode": "NULLABLE",
    "name": "astring",
    "type": "STRING"
  },
  {
    "mode": "NULLABLE",
    "name": "somefloat",
    "type": "FLOAT"
  },
  {
    "mode": "REPEATED",
    "name": "alistofstuff",
    "type": "STRING"
  },
  {
    "fields": [
      {
        "mode": "NULLABLE",
        "name": "somebytes",
        "type": "BYTES"
      },
      {
        "mode": "NULLABLE",
        "name": "update_time",
        "type": "TIMESTAMP"
      }
    ],
    "mode": "REPEATED",
    "name": "arepeatedfield",
    "type": "RECORD"
  },
  {
    "mode": "NULLABLE",
    "name": "destip",
    "type": "BYTES"
  }
]
```

2. Use this schema (in python form) with the `google-cloud-bigquery` as the default job config. 
3. Pass in a correctly formatted list of dicts to `client.insert_rows(table_with_this_schema, rows)`
4. See that the fields at the top level of the schema are properly encoded into json via https://github.com/googleapis/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/client.py#L1500
5. See that the fields in the `REPEATED` and `RECORD` fields are not encoded.
6. Get a json encoding error on those fields.

#### Stacktrace

```
ERROR:google.cloud.pubsub_v1.subscriber._protocol.streaming_pull_manager:Top-level exception occurred in callback while processing a message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 63, in _wrap_callback_errors
    callback(message)
  File "bq_db.py", line 300, in handle_trace_result
    self.write_result_to_bq(bq_result)
  File "bq_db.py", line 294, in write_result_to_bq
    self.bq_client.insert_rows(self.bq_table, [result])
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/client.py", line 1463, in insert_rows
    return self.insert_rows_json(table, json_rows, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/client.py", line 1537, in insert_rows_json
    data=data)
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/client.py", line 364, in _call_api
    return call()
  File "/usr/local/lib/python3.5/dist-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.5/dist-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/_http.py", line 285, in api_request
    data = json.dumps(data)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'J}%\xcd' is not JSON serializable

```

#### Code snippet

Maybe `_helpers.py` needs to handle `RECORDS/REPEATED` in perhaps another lookup helper like the one for scalars? Or, `insert_rows()` should check for list/dict values, something like:

```python
        for index, row in enumerate(rows):
            if isinstance(row, dict):
                row = _row_from_mapping(row, schema)
                print(row)
            json_row = {}

            for field, value in zip(schema, row):
                if isinstance(value, list):
                    values = value
                    value = []
                    for v in values:
                        converter = _SCALAR_VALUE_TO_JSON_ROW.get(field.field_type)
                        if converter is not None:  # STRING doesn't need converting
                            value.append(converter(v))
                        else:
                            value.append(v)
                else:
                    converter = _SCALAR_VALUE_TO_JSON_ROW.get(field.field_type)
                    if converter is not None:  # STRING doesn't need converting
                        value = converter(value)
                json_row[field.name] = value

            json_rows.append(json_row)
```

#### External references such as API reference guides used

- https://googleapis.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.insert_rows

#### Any additional information below

It's not clear in the documentation anywhere if nested schemas are supported, and what to do if not. 

Thanks!

**Comment by adamf** [comment]
Wrong project! Sorry!
