### ISSUE TITLE
Cloud Text-to-Speech: java.lang.NoSuchMethodError when calling TextToSpeechClient.create() via Kotlin

### ISSUE THREAD

**Issue by Flameborn** [googleapis/google-cloud-java#4268]
#### Environment details

- OS: Google Compute Engine
- Java version: openjdk 11.0.1
- google-cloud-java version(s): Not Applicable

#### Steps to reproduce

1. Call TextToSpeechClient.create()

#### Stacktrace

jav
a.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.builder()Lcom/
google/common/collect/ImmutableList$Builder;] with root cause

java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.builder()Lcom/google/common/collect/ImmutableList$Builder;
        at com.google.cloud.texttospeech.v1.stub.TextToSpeechStubSettings.<clinit>(TextToSpeechStubSettings.java:77) ~[google-cloud-texttospeech-0.74.0-beta.jar
!/:0.74.0-beta]
        at com.google.cloud.texttospeech.v1.TextToSpeechSettings$Builder.createDefault(TextToSpeechSettings.java:142) ~[google-cloud-texttospeech-0.74.0-beta.jar!/:0.74.0-beta]
        at com.google.cloud.texttospeech.v1.TextToSpeechSettings$Builder.access$000(TextToSpeechSettings.java:132) ~[google-cloud-texttospeech-0.74.0-beta.jar!/:0.74.0-beta]
        at com.google.cloud.texttospeech.v1.TextToSpeechSettings.newBuilder(Text
ToSpeechSettings.java:114) ~[google-cloud-texttospeech-0.74.0-beta.jar!/:0.74.0-beta]
        at com.google.cloud.texttospeech.v1.TextToSpeechClient.create(TextToSpeechClient.java:101) ~[google-cloud-texttospeech-0.74.0-beta.jar!/:0.74.0-beta]

#### External references such as API reference guides used

- https://google.github.io/guava/releases/20.0/api/docs/com/google/common/collect/ImmutableList.Builder.html

#### Any additional information below

According to the API docs above, the builder constructor should be called *as Builder*.

**Comment by sduskis** [comment]
This seems like a dependency issue.

@Flameborn, can you tell which version of guava is being used?

**Comment by sduskis** [comment]
For reference, the expected version of `guava` for `google-cloud-texttospeech` `0.74.0`  is `26.0-android`.

**Comment by Flameborn** [comment]
I did not explicitly specify a Guava version via Gradle, but rather followed the install and usage instructions at https://cloud.google.com/text-to-speech/docs/reference/libraries#client-libraries-install-java

As a result, *gradle dependencies* shows

    com.google.guava:guava:19.0
     com.google.guava:guava:20.0

for certain com.google.X packages.

My intended target platform is not Android, but I can try with an explicit dependency.

**Comment by Flameborn** [comment]
With an explicit _Guava 26.0-android_ dependency, initialisation and usage seems to work as expected. Thank you very much!
