### ISSUE TITLE
Question : Catch Async Exception of Logging write()

### ISSUE THREAD

**Issue by noxymon** [googleapis/google-cloud-java#4326]
I'm using google cloud logging library version 1.58.0
when i call asynchronous logging write :
```
Logging logging = LoggingOptions.getDefaultInstance().getService(); 
LogEntry logEntry = LogEntry.newBuilder(Payload.StringPayload.of(message))
                    .setLogName(logName)
                    .setLabels(labelMap)
                    .setSeverity(logLevel)
                    .setResource(MonitoredResource.newBuilder("global").build())
                    .build();
logging.write(Collections.singleton(logEntry));
```
i got this exception 

```
java.lang.RuntimeException: com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: {SOMETHING_ERROR}: {SOMETHING_ERROR_MESSAGE}.
	at com.google.cloud.logging.LoggingImpl$7.onFailure(LoggingImpl.java:616) ~[google-cloud-logging-1.58.0.jar:1.58.0]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) [api-common-1.7.0.jar:na]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052) [guava-26.0-android.jar:na]
```
is it possible to catch this type of exception ? i need to put fallback mechanism of logging when google cloud logging can't be used.

**Comment by ajaaym** [comment]
you can use sync writes as below, then you can catch RuntimeException if that helps?
```
logging.setWriteSynchronicity(Synchronicity.SYNC);
```

**Comment by noxymon** [comment]
> you can use sync writes as below, then you can catch RuntimeException if that helps?
> 
> ```
> logging.setWriteSynchronicity(Synchronicity.SYNC);
> ```

yeah, this can could be a solution, but synchronous method, especially for google cloud logging actually is a rest request to google cloud server (which probable have latency), right ?

is it possible to have some futureCallbackListener to write() ?
