### ISSUE TITLE
Speech v1p1beta1 - java.lang.NoSuchMethodError: decodeBase64

### ISSUE THREAD

**Issue by gary0351** [googleapis/google-cloud-java#4340]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

Android app built with Android Studio using speech v1p1beta1 library crashes at startup on Android tablet running API 24 while trying to decode the JSON credentials file to pass to Google speech service. App works fine using speech v1 library.

#### Environment details

- OS: Android API 24
- Java version:
- google-cloud-java version(s): speech v1p1beta1

#### Steps to reproduce

1. Zip file attached or get Android speech example source code from:
https://github.com/GoogleCloudPlatform/android-docs-samples/tree/master/speech/Speech/app/src/main/java/com/google/cloud/android/speech
2. Import app into Android Studio.
3. Modify build-gradle (module app) file to reference speech v1p1beta1 library and dependencies in 
   section:
        android
          // Google Cloud Speech beta - remove duplicate files
          packagingOptions {
              pickFirst  '**'
           }

        dependencies
          // Google Cloud Speech beta
          compile('com.google.cloud:google-cloud-speech:0.77.0-beta')
          compile('com.google.api.grpc:grpc-google-cloud-speech-v1p1beta1:0.42.0')

    Note: additional library dependency updates were tried with no difference
    in build.gradle (module app)
          changing grpcVersion = '1.4.0' to '1.16.1'
          changing google-auth-library-oauth2-http:0.7.0 to 0.12.0

    in build.gradle (project speech)
          changing protobuf-gradle-plugin:0.8.0 to 0.8.7
   
4. Modify SpeechService.java file import references from "v1" to "v1p1beta1":
   import com.google.cloud.speech.v1p1beta1.RecognitionAudio;
   import com.google.cloud.speech.v1p1beta1.RecognitionConfig;
   import com.google.cloud.speech.v1p1beta1.RecognizeRequest;
   import com.google.cloud.speech.v1p1beta1.RecognizeResponse;
   import com.google.cloud.speech.v1p1beta1.SpeechGrpc;
   import com.google.cloud.speech.v1p1beta1.SpeechRecognitionAlternative;
   import com.google.cloud.speech.v1p1beta1.SpeechRecognitionResult;
   import com.google.cloud.speech.v1p1beta1.StreamingRecognitionConfig;
   import com.google.cloud.speech.v1p1beta1.StreamingRecognitionResult;
   import com.google.cloud.speech.v1p1beta1.StreamingRecognizeRequest;
   import com.google.cloud.speech.v1p1beta1.StreamingRecognizeResponse;

5. Build app with Android Studio and run in development mode on Android tablet running API 24.

#### Stacktrace

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: com.google.cloud.android.speech, PID: 4963
                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:318)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
                   Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
                      at com.google.api.client.util.Base64.decodeBase64(Base64.java:101)
                      at com.google.api.client.util.PemReader.readNextSection(PemReader.java:106)
                      at com.google.api.client.util.PemReader.readFirstSectionAndClose(PemReader.java:135)
                      at com.google.auth.oauth2.ServiceAccountCredentials.privateKeyFromPkcs8(ServiceAccountCredentials.java:296)
                      at com.google.auth.oauth2.ServiceAccountCredentials.fromPkcs8(ServiceAccountCredentials.java:286)
                      at com.google.auth.oauth2.ServiceAccountCredentials.fromJson(ServiceAccountCredentials.java:210)
                      at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:174)
                      at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:141)
                      at com.google.cloud.android.speech.SpeechService$AccessTokenTask.doInBackground(SpeechService.java:358)
                      at com.google.cloud.android.speech.SpeechService$AccessTokenTask.doInBackground(SpeechService.java:334)
                      at android.os.AsyncTask$2.call(AsyncTask.java:304)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 

#### Code snippet
SpeechService.java:
            final InputStream stream = getResources().openRawResource(R.raw.credential);
            try {
                final GoogleCredentials credentials = GoogleCredentials.fromStream(stream)
                        .createScoped(SCOPE);

#### External references such as API reference guides used

Google speech v1p1beta1 project dependencies http://googleapis.github.io/google-cloud-java/google-cloud-clients/google-cloud-speech/dependency-management.html

#### Any additional information below
[Speech.zip](https://github.com/googleapis/google-cloud-java/files/2757162/Speech.zip)

Android Studio Build output:
Information:Gradle tasks [:app:generateDevDebugSources, :app:generateDevDebugAndroidTestSources, :app:prepareDevDebugUnitTestDependencies, :app:mockableAndroidJar]
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.5 is ignored for prodDebug as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.5 is ignored for prodRelease as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.5 is ignored for devDebug as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.5 is ignored for devRelease as it may be conflicting with the internal version provided by Android.
Information:BUILD SUCCESSFUL
Information:Total time: 45.532 secs
Information:0 errors
Information:4 warnings
Information:See complete output in console

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by gary0351** [comment]
Thanks. Will try it.

**Comment by sduskis** [comment]
@gary0351 Can we close this issue?

**Comment by gary0351** [comment]
yes

**Comment by xianzhez** [comment]
@gary0351 So...how did you fix this issue? Met the same problem and spent tons of time. Thanks in advance!

**Comment by gary0351** [comment]
Unfortunately I ran into issues resolving other parts of the code with the patch and decided to postpone using the experimental library. I am using the existing library to do what I want for now.

I thought I might spend lots of time going down a rabbit hole. I spent many hours trying to track down the original issue and didn’t want to do more work to end up where I started.

**Comment by HewaWellageDarshana** [comment]
Any working android project in beta vesion
