### ISSUE TITLE
Dependency conflict between guava versions of spark and google storage api

### ISSUE THREAD

**Issue by lanastazia** [googleapis/google-cloud-java#4414]
Hello,

I’m deploying a Spark application, that has a dependency on the [ google storage java client](https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-storage), to list files in the bucket, and treat them one after another with Spark.

It seems that adding this dependency along with Spark causes a conflict with guava, and all my attempts to exclude certain guava (like here https://stackoverflow.com/questions/44935550/gae-cloud-storage-guava-nosuchmethoderror-on-appspot), try different guava versions and spark versions don’t succeed.

The error is only triggered in “assembly” mode (required to run the spark application on Dataproc), not when the application is run in local.

Do you know if there is a way to make these two libraries compatible?

Here is an example to reproduce this error https://github.com/lanastazia/spark-guava-issue

Here is the whole trace of this error : 
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:82)
	at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:88)
	at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:74)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:75)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:334)
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:290)
	at Main$.main(Main.scala:20)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
Thanks !

**Comment by lanastazia** [comment]
Yes, I tried to exclude the older version of Guava evicted by the latest one, but it doesn't work.

**Comment by ajaaym** [comment]
@lanastazia please add spark.executor.userClassPathFirst=true and spark.driver.userClassPathFirst=true in properties as below.

![image](https://user-images.githubusercontent.com/34161822/51935786-b8ae9980-23d4-11e9-93d0-982715c11c18.png)

**Comment by lanastazia** [comment]
It works, thanks a lot !

**Comment by ajaaym** [comment]
@elharo @saturnism FYI, another diamond dependency related to guava.

**Comment by ejona86** [comment]
@ajaaym, I don't think this very related to Guava. I think I root-caused this in https://github.com/grpc/grpc-java/issues/5592#issuecomment-483518426 . I think that Guava is just what _failed first_. I believe Protobuf also would have failed.

This is not the standard diamond dependency issue, either. It relates to class loaders, not package managers.
