### ISSUE TITLE
DEADLINE_EXCEEDED: deadline exceeded after 59999410667ns

### ISSUE THREAD

**Issue by balaji2712** [googleapis/google-cloud-java#4513]
Hi,

We have Google cloud client java program to retrieve messages from Google pub sub topic. This program is being executed from a controlled environment behind a firewall.

When the program was first executed, we got UnknownhostException:pubsub.googleapis.com: Temporary failure in name resolution. Post to which firewall was configured to allows connections to pubsub.googleapis.com:443, www.googleapis.com: 443

Now when the program is executed, we are getting the StatusRuntimeException with DEADLINE_EXCEEDED error. Not sure if any other port needs to be opened up for the program to work. Am not able to determine if any other port needs to be opened up in the firewall.

Any help to resolve this issue would be of great help!

#### Environment details

- OS: RHEL 7
- Java version: 1.8
- google-cloud-java version(s):
google-cloud-pubsub - 1.62.0
google-api-services-pubsub - v1-rev415-1.25.0

#### Steps to reproduce

1. Run Google pub/sub pull message example from behind a firewall

#### Stacktrace

Exception in thread "main" com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 59999410667ns
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:51)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.pubsub.v1.SubscriptionAdminClient.getSubscription(SubscriptionAdminClient.java:467)
		at com.google.cloud.pubsub.v1.SubscriptionAdminClient.getSubscription(SubscriptionAdminClient.java:420)
		at com.hpe.indus.gcp.IoTAlarmSubscriber.main(IoTAlarmSubscriber.java:68)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 59999410667ns
	at io.grpc.Status.asRuntimeException(Status.java:530)
	... 23 more

Thanks!
Balaji

**Comment by ajaaym** [comment]
@balaji2712 You need to allow range of IP addresses. You can use various utilities depending on os to query for all IP for pubsub.googleapis.com and allow all that ip as of now it resolves to below ip address.

```
$ dig +short pubsub.googleapis.com
googleapis.l.google.com.
172.217.12.138
172.217.6.202
172.217.7.10
172.217.11.10
172.217.11.42
172.217.12.170
172.217.12.202
172.217.9.234
172.217.10.10
172.217.10.42
172.217.10.74
172.217.10.138
172.217.3.106
```

**Comment by balaji2712** [comment]
@ajaaym - Thanks. Will try it out.

**Comment by sduskis** [comment]
I believe that you can use a proxy. 
see https://github.com/googleapis/google-cloud-java/issues/2775
and  https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a

**Comment by sduskis** [comment]
@ejona86, what's the preferred grpc solution to accessing grpc services across a firewall?

**Comment by ejona86** [comment]
The general approach is "Do the same thing that you would do with HTTPS," like for REST.
