### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/api/gax/rpc/HeaderProvider

### ISSUE THREAD

**Issue by charbull** [googleapis/google-cloud-java#4537]
Hello, 

I am trying to use your example with a spring application but keep getting the following error:

java.lang.NoClassDefFoundError: com/google/api/gax/rpc/HeaderProvider

#### Environment details

- OS: mac os
- Java version: 8
- google-cloud-java version(s): 1.63.0

#### Steps to reproduce
public static void init() throws FileNotFoundException, IOException {
		
		ClassLoader classLoader = FirebaseHandler.class.getClassLoader();
		String path = classLoader.getResource("keys.json").getPath();
		GoogleCredentials credentials = GoogleCredentials.fromStream(new FileInputStream(path))
				.createScoped(Collections.singleton(IamScopes.CLOUD_PLATFORM));

		   com.google.cloud.storage.Storage storage = StorageOptions.newBuilder().setCredentials(credentials).build().getService();

		    // Creates the new bucket
		    com.google.cloud.storage.Bucket bucket = storage.create(BucketInfo.newBuilder(GCP_OTA.BUCKET_NAME).setStorageClass(StorageClass.STANDARD).setLocation("us-central").build());

		    System.out.printf("Bucket %s created.%n", bucket.getName());
	}

#### Stacktrace
java.lang.NoClassDefFoundError: com/google/api/gax/rpc/HeaderProvider
	at com.google.cloud.storage.StorageOptions.getDefaultHttpTransportOptions(StorageOptions.java:104)
	at com.google.cloud.storage.StorageOptions$StorageDefaults.getDefaultTransportOptions(StorageOptions.java:99)
	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:262)
	at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:82)
	at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:31)
	at com.google.cloud.storage.StorageOptions$Builder.build(StorageOptions.java:77)
	at org.eclipse.hawkbit.google.gcp.FirebaseHandler.init(FirebaseHandler.java:23)
	at org.eclipse.hawkbit.simulator.SimulatorStartup.onApplicationEvent(SimulatorStartup.java:54)
	at org.eclipse.hawkbit.simulator.SimulatorStartup.onApplicationEvent(SimulatorStartup.java:30)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:99)
	at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176)
	at org.eclipse.hawkbit.simulator.DeviceSimulator.main(DeviceSimulator.java:55)
Caused by: java.lang.ClassNotFoundException: com.google.api.gax.rpc.HeaderProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 common frames omitted
Thanks!

**Comment by sduskis** [comment]
@meltsufin, FYI

**Comment by meltsufin** [comment]
@sduskis Why did cc me on this?
In any case, this part in the stack trace seems interesting:
```
at org.eclipse.hawkbit.google.gcp.FirebaseHandler.init(FirebaseHandler.java:23)
```
What is this `FirebaseHandler`?

**Comment by sduskis** [comment]
@meltsufin, this phrase "I am trying to use your example with a spring application"

**Comment by sduskis** [comment]
@charbull, NoClassDefFoundError happen when dependencies are mismatched. Can you please list your dependencies? (maven and gradle both have ways of showing how dependencies are resolved)

**Comment by meltsufin** [comment]
@charbull So, yeah, if you're interested, there is Cloud Storage support in Spring Cloud GCP. See: https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample

**Comment by charbull** [comment]
@meltsufin thank you for the pointers. I will check it out.

I eventually tried this [here](https://github.com/google/google-api-java-client-samples/blob/master/storage-cmdline-sample/src/main/java/com/google/api/services/samples/storage/examples/ObjectsGetMetadataExample.java)

@sduskis My code sample and maven dependencies are [here](https://github.com/charbull/hawkbit-examples/blob/master/hawkbit-device-simulator/pom.xml)

**Comment by ajaaym** [comment]
@charbull I dont see below dependency in your pom file. Also looks like code is changed too. Dont find this class or code related to storage.

```
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-storage</artifactId>
  <version>1.63.0</version>
</dependency>
```

**Comment by charbull** [comment]
Thank you, I updated it seems to be working
