### ISSUE TITLE
Internal Error encountered while attempting to create K8s cluster

### ISSUE THREAD

**Issue by shashank-g172** [googleapis/google-cloud-java#4543]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

Problem: I'm attempting to write a utility that will let me create and tear down K8s clusters on-demand. 

Issue: I created service account credentials for my GCP account and saved them in a JSON file. I'm referencing that file for the  environment variable GOOGLE_APPLICATION_CREDENTIALS and running that through Eclipse (Photon). It's a single Java class that I'm running right now. 

#### Environment details

- OS: Windows 10
- Java version: jdk 1.8.0_191
- google-cloud-java version(s):

		<dependency>
			<groupId>com.google.auth</groupId>
			<artifactId>google-auth-library-oauth2-http</artifactId>
			<version>0.13.0</version>
			<exclusions>
				<exclusion>
					<groupId>io.opencensus</groupId>
					<artifactId>opencensus-contrib-http-util</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.opencensus</groupId>
			<artifactId>opencensus-contrib-http-util</artifactId>
			<version>0.18.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-container</artifactId>
			<version>0.80.0-beta</version>
		</dependency>

#### Steps to reproduce

1. Please run the following code given below - replace the service account with one of the in-house ones and the project name as well.

#### Stacktrace

Any relevant stacktrace here.
Exception in thread "main" com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.container.v1.ClusterManagerClient.createCluster(ClusterManagerClient.java:440)

Caused by: io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.
	at io.grpc.Status.asRuntimeException(Status.java:530)
	... 23 more

#### Code snippet

```java
public Operation createKubernetesCluster()
      throws IOException, InterruptedException, ExecutionException {
    try (ClusterManagerClient clusterManagerClient = ClusterManagerClient.create()) {
      String projectId = "My First Project";
      Cluster cluster = Cluster.newBuilder().setName("test-cluster1").setInitialNodeCount(3).build();
      CreateClusterRequest request = CreateClusterRequest.newBuilder().setProjectId(projectId).setZone("us-east4-a") 
          .setCluster(cluster).build();
```

#### External references such as API reference guides used

- https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/container/v1/package-summary.html
- https://mvnrepository.com/search?q=google-cloud-container&sort=popular
- All the JavaDoc on the 0.80 version of the cloud-container maven artifact

#### Any additional information below

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sduskis** [comment]
Do you have any more of the the stack trace? It's not clear where the `io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.` occurred.

**Comment by shashank-g172** [comment]
It looks like there;s a suppressed Asynchronous task failing:

Exception in thread "main" com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.container.v1.ClusterManagerClient.createCluster(ClusterManagerClient.java:440)
		at 

Caused by: io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.
	at io.grpc.Status.asRuntimeException(Status.java:530)
	... 23 more

and the createCluster call is from the code that I wrote above.

**Comment by ajaaym** [comment]
@shashank-g172 I just tried your example and it works fine. Can you please set the log level to FINEST and send the log file? Also can you make sure your service account has proper permission?

**Comment by shashank-g172** [comment]
I think I'll need to assign the Kubernetes container admin and the container clusterAdmin roles to the service account following this document: https://cloud.google.com/iam/docs/understanding-roles#kubernetes-engine-roles. 

Do I have that right?

I'll reply once I have the roles set up. Hopefully it's just the roles.

**Comment by shashank-g172** [comment]
I added all the roles to the service account, and I'm still seeing the same error. I even created a new JSON key, enabled the APIs and passed that file as the GOOGLE_APPLICATION_CREDENTIALS environment variable to my program. 

Is there anything that I've described that doesn't match up to the way you have your program set up which ran with no issues?

**Comment by ajaaym** [comment]
@shashank-g172 I tried on windows as well and it working fine.

**Comment by olavloite** [comment]
@shashank-g172 I am also not able to reproduce this. Does this still fail for you? Running the following application works for me:

```java
public class ContainerConfigTest {
  public static void main(String[] args)
      throws IOException, InterruptedException, ExecutionException {
    try (ClusterManagerClient client = ClusterManagerClient.create()) {
      String projectId = "my-project-id";
      Cluster cluster =
          Cluster.newBuilder().setName("test-cluster1").setInitialNodeCount(3).build();
      CreateClusterRequest request =
          CreateClusterRequest.newBuilder()
              .setProjectId(projectId)
              .setZone("us-east4-a")
              .setCluster(cluster)
              .build();
      client.createCluster(request);
    }
  }
}

```

I noticed in your first post that you also included more dependencies than absolutely necessary to only run the above code (you included dependencies for OpenCensus and google-auth-library-oauth2-http). Strictly speaking, to run my example you don't need any more than this:

```
  <dependency>
  	<groupId>com.google.cloud</groupId>
  	<artifactId>google-cloud-container</artifactId>
  	<version>0.80.0-beta</version>
  </dependency>
```

I tried to run my example including your dependencies as well, but it still executes as expected.

If it still fails, could you supply a complete example. The snippet that you provided above should normally be enough, but as we cannot reproduce it, I'm starting to wonder whether it is caused by something else that is also in your example application that we are not seeing.

**Comment by olavloite** [comment]
@shashank-g172 We haven't heard back from you in a while, and we are not able to reproduce this problem, so closing this for now. Please feel free to reopen if this problem still occurs.
