### ISSUE TITLE
SubscriberStub awaitTerminate() returns before all threads are closed

### ISSUE THREAD

**Issue by Xeli** [googleapis/google-cloud-java#4558]
Hello!

#### Issue
I run into a problem when using `shutdown()` and `awaitTermination()` of a SubscriberStub. When `awaitTermination()` returns not every grpc thread has actually finished. 

I need a way to know when the subscriber and all background threads are actually finised. This is needed because the Apache Flink cluster it is running on will remove classes and if anything is still running this will cause ClassNotFoundExceptions. (See this issue (https://github.com/googleapis/google-cloud-java/issues/3752 for a more thorough explaination) 

So my question is two-fold:

Is it correct `awaitTerminate()` does not wait for all background resources the shutdown? 
If this is the intended behavior, is there any other way of knowing when all background resources are done?

#### Steps to reproduce

This piece of code shows the existence of background threads after `awaitTermination()` returns:

    //no grpc threads obviously 
    Thread.getAllStackTraces().keySet().stream().filter(Thread::isAlive).map(Thread::getName).forEach(Sy stem.out::println);

    SubscriberStubSettings settings = SubscriberStubSettings.newBuilder().build();
    GrpcSubscriberStub stub = GrpcSubscriberStub.create(settings);

    stub.shutdownNow();
    stub.awaitTermination(1, TimeUnit.MINUTES);

    //grpc threads, in particular: grpc-shared-destroyer-x, when actual work has been done even more threads are shown like grpc-worker-x-y
    Thread.getAllStackTraces().keySet().stream().filter(Thread::isAlive).map(Thread::getName).forEach(System.out::println);

#### External references such as API reference guides used

https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/pubsub/v1/stub/GrpcSubscriberStub.html#awaitTermination-long-java.util.concurrent.TimeUnit-

Thank you for looking into this

**Comment by ajaaym** [comment]
@Xeli grpc uses shared event loop if not specified to be used by any number of client. On awaitTermination of client it schedules the destroyer thread which destroys the event loop if no new client is created or exists with in that time. so to make sure that shared resources are destroyed please wait for 3-5 second after calling awaitTermination to remove all grpc threads.

**Comment by Xeli** [comment]
@ajaaym thanks for the quick response. Is there another way besides waiting a few seconds?

I would prefer a more robust check to be sure everything is gone.

**Comment by ajaaym** [comment]
@Xeli Unfortunately there is no robust way unless you provide your own TransportChannelProvider. In that case you can create channel builder using NettyChannelBuilder and provide your own event loop which you can shutdown. If you want to go that route I can send you full working sample.

**Comment by Xeli** [comment]
@ajaaym That is too bad. I would appreciate it if you could point me to a working sample!

**Comment by ajaaym** [comment]
@Xeli please use below code.

```
    final EventLoopGroup eventLoopGroup = new DefaultEventLoopGroup(6);
    InstantiatingGrpcChannelProvider
        channelProvider = SubscriberStubSettings.defaultGrpcTransportProviderBuilder().setChannelConfigurator(new ApiFunction<ManagedChannelBuilder, ManagedChannelBuilder>() {
      @Override public ManagedChannelBuilder apply(ManagedChannelBuilder input) {
        NettyChannelBuilder nettyChannelBuilder = (NettyChannelBuilder) input;
        nettyChannelBuilder.eventLoopGroup(eventLoopGroup);
        return nettyChannelBuilder;
      }
    }).build();
    SubscriberStubSettings settings = SubscriberStubSettings.newBuilder().setTransportChannelProvider(channelProvider).build();
    GrpcSubscriberStub stub = GrpcSubscriberStub.create(settings);
    stub.shutdownNow();
    stub.awaitTermination(1, TimeUnit.MINUTES);
    eventLoopGroup.shutdownGracefully();
    eventLoopGroup.terminationFuture().await(1, TimeUnit.MINUTES);
```

**Comment by Xeli** [comment]
Thank you for this @ajaaym 

I am running into a problem when providing an EventLoopGroup. Locally (osx machine) it works fine when I am using DefaultEventLoopGroup.

But if I run the code on the Google Cloud Platform (kubernetes) it fails with the exception:

    Caused by: java.lang.IllegalStateException: incompatible event loop type: 
    io.grpc.netty.shaded.io.netty.channel.DefaultEventLoop
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:469)
	at io.grpc.netty.shaded.io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.grpc.netty.shaded.io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.grpc.netty.shaded.io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.grpc.netty.shaded.io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:230)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:266)
	at io.grpc.internal.InternalSubchannel.access$700(InternalSubchannel.java:67)
	at io.grpc.internal.InternalSubchannel$TransportListener.transportShutdown(InternalSubchannel.java:611)
	at io.grpc.netty.shaded.io.grpc.netty.ClientTransportLifecycleManager.notifyShutdown(ClientTransportLifecycleManager.java:53)
	at io.grpc.netty.shaded.io.grpc.netty.ClientTransportLifecycleManager.notifyTerminated(ClientTransportLifecycleManager.java:69)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport$4.run(NettyClientTransport.java:248)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:101)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:130)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onAddresses(ManagedChannelImpl.java:1300)
	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:325)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:225)
	... 3 more

This seems to be because it requires a NioEventLoop (https://netty.io/wiki/native-transports.html)

Do you have any tips how to create the correct EventLoop ?

**Comment by ajaaym** [comment]
@Xeli can you try to use  NioEventLoopGroup or EpollEventLoopGroup instead of Default? GRPC uses NioSocketChannel by default. Not sure why it worked on mac. I also tried on mac only.

**Comment by Xeli** [comment]
Yes this works perfectly! Thank you so much for your help @ajaaym
