### ISSUE TITLE
Stackdriver Error Reporting API has not been used in project

### ISSUE THREAD

**Issue by keviocastro** [googleapis/google-cloud-java#4561]
#### Environment details

- OS: Ubuntu 18.04
- Java version: jdk1.7.0_80
- google-cloud-java version(s): 0.81.0-beta

#### Steps to reproduce

1. Install google cloud sdk 
2. Initialized account with google SDK: gcloud init
3. Enabled google-cloud-errorreporting api: gcloud services enable clouderrorreporting.googleapis.com
4. Run this example: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/errorreporting/src/main/java/com/example/errorreporting/QuickStart.java

I already checked the google cloud console. Api is enabled.

#### Stacktrace

```java
Exception in thread "main" com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Stackdriver Error Reporting API has not been used in project 563584335869 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/clouderrorreporting.googleapis.com/overview?project=563584335869 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.errorreporting.v1beta1.ReportErrorsServiceClient.reportErrorEvent(ReportErrorsServiceClient.java:255)
		at com.google.cloud.errorreporting.v1beta1.ReportErrorsServiceClient.reportErrorEvent(ReportErrorsServiceClient.java:188)
		at servicos.erro.ErroService.main(ErroService.java:55)
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Stackdriver Error Reporting API has not been used in project 563584335869 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/clouderrorreporting.googleapis.com/overview?project=563584335869 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at io.grpc.Status.asRuntimeException(Status.java:530)
	... 23 more
```

#### Code snippet
```

        // Google Cloud Platform Project ID
        String projectId = (args.length > 0) ? args[0] : ServiceOptions.getDefaultProjectId();
        ProjectName projectName = ProjectName.of(projectId);

        // Instantiate an Error Reporting Client
        try{
            ReportErrorsServiceClient reportErrorsServiceClient = ReportErrorsServiceClient.create();
            // Custom error events require an error reporting location as well.
            ErrorContext errorContext = ErrorContext.newBuilder()
                    .setReportLocation(SourceLocation.newBuilder()
                            .setFilePath("Test.java")
                            .setLineNumber(10)
                            .setFunctionName("myMethod")
                            .build())
                    .build();

            //Report a custom error event
            ReportedErrorEvent customErrorEvent = ReportedErrorEvent.getDefaultInstance()
                    .toBuilder()
                    .setMessage("custom error event")
                    .setContext(errorContext)
                    .build();
            // Report an event synchronously, use .reportErrorEventCallable for asynchronous reporting.
            reportErrorsServiceClient.reportErrorEvent(projectName, customErrorEvent);
        }catch (IOException e){
             logger.log(Level.SEVERE, "Exception encountered logging custom event", e);
        }
```

**Comment by ajaaym** [comment]
@keviocastro  What do you see when you go [here](https://console.developers.google.com/apis/api/clouderrorreporting.googleapis.com/overview?project=563584335869) Is it showing enabled?

**Comment by keviocastro** [comment]
display error

![captura de tela de 2019-02-25 20-34-47](https://user-images.githubusercontent.com/1850270/53376371-d40db580-393c-11e9-80ca-fb485eef4749.png)

**Comment by sduskis** [comment]
Unfortunately, there's very little we can do in this repository.  Please visit https://cloud.google.com/stackdriver/docs/getting-support to get help from the Stackdriver team.
