### ISSUE TITLE
Getting error while using the Java Client Library in my spring boot application for Stackdriver Logging

### ISSUE THREAD

**Issue by bilalbari** [googleapis/google-cloud-java#4654]
I am trying to use Stackdriver Logging in my spring boot project. Using the Java Client Library for Logging. 
Have added the maven dependency and am trying to post data to my Stackdriver Logging console.
**Dependency-**

```
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-logging</artifactId>
  <version>1.64.0</version>
</dependency>
```

 **My Code (Rest Controller)-**

```
@PostMapping("/enterLogging")
	public void userAccess(@RequestBody Map<String, String> myMap) throws FileNotFoundException, IOException
	{
		LoggingOptions options = LoggingOptions.newBuilder().setCredentials(ServiceAccountCredentials.fromStream(new FileInputStream("*****"))).build();
		logger.info(options.getProjectId());
		Map<String, String> innerMap = new HashMap<String, String>();
		innerMap.put("description", myMap.get("description"));
		innerMap.put("module",myMap.get("module"));
		innerMap.put("source",myMap.get("source"));
		innerMap.put("userID",myMap.get("userID"));
		logger.info("logging for stackdriver");
		try(Logging logging = options.getService()){
			LogEntry firstEntry = LogEntry.newBuilder(JsonPayload.of(innerMap))
								.setLogName("test-log")
								.setResource(MonitoredResource.newBuilder("global").addLabel("project_id",options.getProjectId()).build())
								.build();
			logging.write(Collections.singleton(firstEntry));
		}
		catch (Exception e) {
			System.out.println("Wrong entry");
		}
	}
```

**Error Trace -** 

```
 RuntimeException while executing runnable CallbackListener{com.google.api.core.ApiFutures$1@2f47a26a} with executor MoreExecutors.directExecutor()

java.lang.RuntimeException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4b8d44d6[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@1d339d86[Wrapped task = io.grpc.internal.SerializingExecutor@3b638d3d]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@2664cf42[Shutting down, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 0]
	at com.google.cloud.logging.LoggingImpl$7.onFailure(LoggingImpl.java:616) ~[google-cloud-logging-1.64.0.jar:1.64.0]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) ~[api-common-1.7.0.jar:na]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:92) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:98) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030) ~[guava-26.0-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871) ~[guava-26.0-android.jar:na]
```

Any help or guidance??

**Comment by ajaaym** [comment]
@bilalbari you shouldnt be creating autoclosing client in a method. Either you need to create it once and use it or in worst case if you want to create and close in a method then you need to wait till operation completes in a try block. So code should look like below

```
    try(Logging logging = options.getService()){
      LogEntry firstEntry = LogEntry.newBuilder(JsonPayload.of(innerMap))
          .setLogName("test-log")
          .setResource(MonitoredResource.newBuilder("global").addLabel("project_id",options.getProjectId()).build())
          .build();
      logging.write(Collections.singleton(firstEntry));
      logging.flush();
    }
    catch (Exception e) {
      System.out.println("Wrong entry");
    }
```

**Comment by sduskis** [comment]
@ajaaym, that makes sense.  It would make sense to keep a `Logging logging = options.getService()` variable rather than creating a new one for every request.  In this case, it seems like we want autoflush, or even a single RPC rather than waiting for the logger to aggregate all requests into a single RPC.

The `Logging.write()` wasn't meant for that situation.  Would making `LoggingImpl.writeAsync()` public help?  I would not put `writeAsync()` in the `Logging` interface, so that way power users have access to the method, but will realize that this isn't the standard way of using the client.

**Comment by sduskis** [comment]
On a different note, I see this in `LoggingImpl`:

```java
  public void write(Iterable<LogEntry> logEntries, WriteOption... options) {
    if (inWriteCall.get() != null) {
      return;
    }
   ...
```

This means that you can't cache the Logging service.

**Comment by ajaaym** [comment]
@sduskis there is a autoflush. ```Logging.write()``` is async by default unless ```WriteSynchronicity``` is set. I think what we need is another method which returns ApiFuture for every write call rather than returning void. There is similar request related to this as well #4326

**Comment by bilalbari** [comment]
@ajaaym Thanks for the help. The error is not happening now. A problem however , the call is executing but nothing is getting logged in my GCP Logging console. It shows no entry in the Stackdriver Console . 

**Trace -** 
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/***/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-03-08 11:43:04.004  INFO 42018 --- [nio-8080-exec-2] c.w.a.p.f.a.l.AuditServiceDemoController : About to write
2019-03-08 11:43:05.987  INFO 42018 --- [nio-8080-exec-2] c.w.a.p.f.a.l.AuditServiceDemoController : Written
2019-03-08 11:43:06.004 DEBUG 42018 --- [nio-8080-exec-2] m.m.a.RequestResponseBodyMethodProcessor : Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
2019-03-08 11:43:06.004 DEBUG 42018 --- [nio-8080-exec-2] m.m.a.RequestResponseBodyMethodProcessor : Nothing to write: null body
2019-03-08 11:43:06.005 TRACE 42018 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : No view rendering, null ModelAndView returned.
2019-03-08 11:43:06.005 DEBUG 42018 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Completed 200 OK, headers={}
` 
Any help please..

**Comment by ajaaym** [comment]
@bilalbari what filter do you have in gcp logging console? can you check under global?

**Comment by bilalbari** [comment]
@ajaaym Yes, the logs are showing under global configuration . Thank you so much for the help!
