### ISSUE TITLE
Cannot use Cloud Datastore Java APIs with Graal VM.

### ISSUE THREAD

**Issue by ludoch** [googleapis/google-cloud-java#4670]
Playing with the native example of Quarkus IO https://quarkus.io/  located at:

https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started

Adding a dep with 
```
       <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-datastore</artifactId>
      <version>1.62.0</version>
    </dependency>
```
And using the Cloud Datastore API (simple imports/usage)

Notice I do not define GAE App Engine APIs which I do not want to use (it would not work anyway in a Java11 titanium pure runtime.

I then compile with:

mvn install -Dnative-image.docker-build -Pnative
...
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[quarkus-quickstart-runner:6]     analysis:  22,469.29 ms
Printing call tree to /project/reports/call_tree_quarkus-quickstart-runner_20190312_181219.txt
Printing list of used classes to /project/reports/used_classes_quarkus-quickstart-runner_20190312_181222.txt
Printing list of used packages to /project/reports/used_packages_quarkus-quickstart-runner_20190312_181222.txt
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: com.google.appengine.api.urlfetch.HTTPMethod. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: com.google.appengine.api.urlfetch.HTTPMethod. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing com.google.api.client.extensions.appengine.http.UrlFetchTransport.buildRequest(UrlFetchTransport.java:116)
Call path from entry point to com.google.api.client.extensions.appengine.http.UrlFetchTransport.buildRequest(String, String): 
        at com.google.api.client.extensions.appengine.http.UrlFetchTransport.buildRequest(UrlFetchTransport.java:113)
        at com.google.api.client.extensions.appengine.http.UrlFetchTransport.buildRequest(UrlFetchTransport.java:50)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:901)
        at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:183)
        at com.google.datastore.v1.client.Datastore.commit(Datastore.java:87)
        at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:152)
        at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:496)
        at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:493)
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
        at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
        at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:176)
        at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:72)
        at com.google.cloud.datastore.QueryResultsImpl.computeNext(QueryResultsImpl.java:93)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at java.util.AbstractCollection.containsAll(AbstractCollection.java:317)
        at java.util.RegularEnumSet.containsAll(RegularEnumSet.java:199)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:158)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:131)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

**Comment by ludoch** [comment]
Trying with:
```
      <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-datastore</artifactId>
      <version>1.62.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.http-client</groupId>
                    <artifactId>google-http-client-appengine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
Maybe this dep should not be declared, and added by a customer only when they  want to run on GAE compat?
Also, the Java8 GAE compat runtime can use native sockets (for a price) so it might be nice to really cut this dep and use the native path...


Anyway, now getting:
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[quarkus-quickstart-runner:7]     analysis:  22,991.78 ms
Printing call tree to /project/reports/call_tree_quarkus-quickstart-runner_20190312_184524.txt
Printing list of used classes to /project/reports/used_classes_quarkus-quickstart-runner_20190312_184528.txt
Printing list of used packages to /project/reports/used_packages_quarkus-quickstart-runner_20190312_184528.txt
Error: unsupported features in 2 methods
Detailed message:
Error: Class initialization failed: com.google.cloud.http.HttpTransportOptions$DefaultHttpTransportFactory
Original exception that caused the problem: java.lang.NoClassDefFoundError: com/google/api/client/extensions/appengine/http/UrlFetchTransport
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at com.oracle.svm.hosted.ClassInitializationFeature.ensureClassInitialized(ClassInitializationFeature.java:371)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:334)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:310)
	at com.oracle.svm.hosted.ClassInitializationFeature.maybeInitializeHosted(ClassInitializationFeature.java:131)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:179)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:261)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:202)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:179)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.getDeclaringClass(AnalysisMethod.java:323)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.getSignature(AnalysisMethod.java:300)
	at com.oracle.graal.pointsto.flow.MethodFlowsGraph.<init>(MethodFlowsGraph.java:98)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.<init>(MethodTypeFlow.java:75)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:129)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:404)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:392)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:115)
	at org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4035)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1452)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5020)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3184)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2993)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:890)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:784)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:205)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:324)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.flow.SourceTypeFlowBase.update(SourceTypeFlowBase.java:121)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.google.api.client.extensions.appengine.http.UrlFetchTransport
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.google.cloud.http.HttpTransportOptions$DefaultHttpTransportFactory.access$400(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.google.cloud.http.HttpTransportOptions.<init>(HttpTransportOptions.java:128)
Call path from entry point to com.google.cloud.http.HttpTransportOptions.<init>(HttpTransportOptions$Builder): 
	at com.google.cloud.http.HttpTransportOptions.<init>(HttpTransportOptions.java:123)
	at com.google.cloud.http.HttpTransportOptions$Builder.build(HttpTransportOptions.java:85)
	at com.google.cloud.datastore.DatastoreOptions.getDefaultHttpTransportOptions(DatastoreOptions.java:138)
	at com.google.cloud.datastore.DatastoreOptions$DatastoreDefaults.getDefaultTransportOptions(DatastoreOptions.java:133)
	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:286)
	at com.google.cloud.datastore.DatastoreOptions.<init>(DatastoreOptions.java:97)
	at com.google.cloud.datastore.DatastoreOptions.<init>(DatastoreOptions.java:35)
	at com.google.cloud.datastore.DatastoreOptions$Builder.build(DatastoreOptions.java:86)
	at com.google.cloud.datastore.DatastoreOptions.getDefaultInstance(DatastoreOptions.java:148)
	at org.acme.quickstart.GreetingResource.datastore(GreetingResource.java:67)
	at com.oracle.svm.reflect.GreetingResource_datastore_bf72e037a8921df24a0083e81a304930d044c723_28.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.io.Closer$SuppressingSuppressor.suppress(Closer.java:291)
	at com.google.common.io.Closer.close(Closer.java:221)
	at org.xnio.IoUtils.safeClose(IoUtils.java:152)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:506)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

**Comment by ludoch** [comment]
using this quarkus plugin configuration with --allow-incomplete-classpath
 ```
        <plugin>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
            <version>${quarkus.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>native-image</goal>
                </goals>
                <configuration>
                  <enableHttpUrlHandler>true</enableHttpUrlHandler>
                  <additionalBuildArgs>--allow-incomplete-classpath</additionalBuildArgs>
                </configuration>
              </execution>
            </executions>
          </plugin>
```
I can generate the executable.

**Comment by ludoch** [comment]
Execution gives a runtime error:

 textPayload:  "2019-03-12 20:32:40,045 ERROR [io.und.request] (XNIO-1 task-1) UT005023: Exception handling request to /hello/datastore: org.jboss.resteasy.spi.UnhandledException: com.oracle.svm.core.jdk.UnsupportedFeatureError: Accessing an URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=https option to the native-image command."  
Trying now the new option.

**Comment by ludoch** [comment]
Next error: Getting
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v /Users/ludo/a/quarkus-quickstarts/getting-started-native/target:/project:z --rm swd847/centos-graal-native-image-rc12 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --allow-incomplete-classpath --enable-url-protocols=https -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-quickstart-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:+PrintAnalysisCallTree -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace

but      adding               <arg>-H:+JNI</arg>
in pom.xml does not help, as it seems to be already hardcoded as disabled in the quarkus plugin...

**Comment by ludoch** [comment]
Making progress,

With 
```
          <plugin>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
            <version>${quarkus.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>native-image</goal>
                </goals>
                <configuration>
                  <enableHttpUrlHandler>true</enableHttpUrlHandler>
                  <additionalBuildArgs>
                    <arg>--allow-incomplete-classpath</arg>
                    <arg>--enable-url-protocols=https</arg>
                    <arg>--enable-https</arg>
                  </additionalBuildArgs>
                  <enableJni>true</enableJni>
                </configuration>
              </execution>
            </executions>
          </plugin>
```
Getting:

A  Caused by: java.lang.IllegalArgumentException:  
A  	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889) 
A  	at com.google.api.client.json.JsonParser.parse(JsonParser.java:382) 
A  	at com.google.api.client.json.JsonParser.parse(JsonParser.java:355) 
A  	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87) 
A  	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81) 
A  	at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:459) 
A  	at com.google.auth.oauth2.ComputeEngineCredentials.refreshAccessToken(ComputeEngineCredentials.java:173) 
A  	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:181) 
A  	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:167) 
A  	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96) 
A  	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) 
A  	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc$1.initialize(HttpDatastoreRpc.java:81) 
A  	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:181) 
A  	at com.google.datastore.v1.client.Datastore.commit(Datastore.java:87) 
A  	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:152) 
A  	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:496) 
A  	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:493) 
A  	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105) 
A  	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) 
A  	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) 
A  	at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:492) 
A  	... 73 more 
A  Caused by: java.lang.IllegalArgumentException: unable to create new instance of class com.google.api.client.util.GenericData because it has no accessible default constructor 
A  	at com.google.api.client.util.Types.handleExceptionForNewInstance(Types.java:165) 
A  	at com.google.api.client.util.Types.newInstance(Types.java:120) 
A  	at com.google.api.client.util.Data.newMapInstance(Data.java:526) 
A  	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:762) 
A  	... 93 more 
A  Caused by: java.lang.InstantiationException: Type `com.google.api.client.util.GenericData` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image. 
A  	at java.lang.Class.newInstance(DynamicHub.java:653) 
A  	at com.google.api.client.util.Types.newInstance(Types.java:116) 
A  	... 95 more

**Comment by ludoch** [comment]
https://github.com/oracle/graal/issues/926

**Comment by sduskis** [comment]
@ludoch, I'm not sure what the problem is.  [`com.google.api.client.util.GenericData` does have a public no parameter constructor](https://github.com/googleapis/google-http-java-client/blob/v1.26.0/google-http-client/src/main/java/com/google/api/client/util/GenericData.java#L61).

**Comment by ludoch** [comment]
My current understanding is that this Graal bug is the blocking one now: 
https://github.com/oracle/graal/issues/926
Agree?

**Comment by ludoch** [comment]
I've finally a set of configuration steps where Google Cloud Datastore can be used in GraalVM and the quarkus.io native target.

Doing some cleanup first, but doable now.

**Comment by sduskis** [comment]
@ludoch, is there anything actionable on this issue, or can we close it?

**Comment by jeffosmith** [comment]
@ludoch are you able to share your working config, looking to do something similar in the future

**Comment by sduskis** [comment]
There isn't much we can do here. Closing this issue.

**Comment by nhoughto** [comment]
In terms of something that can be done, you could support Graal's `native-image.properties` notation for declaring how things should be built, like micronaut does:

https://github.com/micronaut-projects/micronaut-core/blob/master/http-netty/src/main/resources/META-INF/native-image/io.micronaut/netty/native-image.properties

That way you are solving the problems once for all users..

**Comment by ludoch** [comment]
Right this is the correct approach: each external library should provide its graalvm flags if it wants to be used in this environment.
I suggest reopening this issue.

**Comment by nhoughto** [comment]
Be great to get a fix for this. Currently can't use native image with gcp. Have to write our own clients to workaround it 😢
