### ISSUE TITLE
Memory leak from netty/Deadline exceeded after 9999961477ns

### ISSUE THREAD

**Issue by tanuja5** [googleapis/google-cloud-java#4757]
The following exception occurs with gcloud pubsub client library,
	
	1. When I tried publishing about 500000 messages to a topic in async mode: 

	Stack trace:
	: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9999961477ns
	at com.myorg.proc.MyClass$MyInnerClass.onFailure(MyClass.java:324)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.core.SettableApiFuture.setException(SettableApiFuture.java:52)
	at com.google.cloud.pubsub.v1.Publisher$4.onFailure(Publisher.java:351)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:162)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2. When tried with 1000000 messages, there is a memory leak which was analysed using Eclipse Mat. The following report was produced 

		- 920 instances of "io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport$3"  
		- occupy 2,360,621,112 (76.82%) bytes. 

	Is this because of the limit in outstanding messages mentioned in "https://github.com/googleapis/google-cloud-java/issues/3884" ?

	Jar version used:
	1.google-cloud-pubsub:jar:1.53.0
	2.google-cloud-core:jar:1.53.0
	3.google-http-client:jar:1.27.0
	4.grpc-netty-shaded:jar:1.16.1

	Topic configuration:
	RetryDelay:1, MaxRetryDelay:10, TotalTimeout:10, InitialRpcTimeout:10, MaxRpcTimeout:100, RetryDelayMultiplier:2.0, NumThreads:10, ElementCountThreshold: 999, DelayThreshold:1m, RequestByteThreshold:1000000

	Os version: MacOS 10.13.6 

	Please give me some insights on this. Is this some known issue or am I missing anything here?

**Comment by ajaaym** [comment]
@tanuja5 Since you want to publish large number of messages please use higher batching thresholds as below that will reduce the total number of rpc. Memory leak reported by eclipse Mat is not actually memory leak its just number of pending rpcs. You can keep higher delay threshold and bytethreshold so you can hit element count threshold and fine tune that based on your application requirement.

```
    Publisher publish =
        Publisher.newBuilder("topic_name")
            .setBatchingSettings(
                BatchingSettings.newBuilder()
                    .setDelayThreshold(Duration.ofSeconds((20)))
                    .setRequestByteThreshold(1000000l)
                    .setElementCountThreshold(50000l) // higher number of message here will make large batch
                    .build())
```

**Comment by tanuja5** [comment]
I did try configuring different threshold values but those configurations did not help. I also read this 

> Batching also supports FlowControl. This can be used to prevent the batching implementation from accumulating messages without limit, resulting eventually in an OutOfMemory exception. This can occur if messages are created and added to batching faster than they can be processed. The flow control behavior is controlled using FlowControlSettings.

from BatchSettings doc and I tried to use FlowController like this:
`FlowController.LimitExceededBehavior le = FlowController.LimitExceededBehavior.valueOf("Block");

        FlowControlSettings flowControlSettings = FlowControlSettings.newBuilder().setMaxOutstandingElementCount(1000L)
        .setMaxOutstandingRequestBytes(1000L).setLimitExceededBehavior(le).build();`

Still I ended up with the same exception:
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9999961477ns


Please let me know if there is any documentation for configuring the right values for these properties or any other suggestion you have to overcome this.

**Comment by ajaaym** [comment]
@tanuja5 can you please share your repro? are you running in gcp?

**Comment by tanuja5** [comment]
No I'm not using GCP, I don't have a repo either. Here's a sample of my code that I use in my original application 

```
package org.example.pubsub;

import com.google.api.core.ApiFuture;
import com.google.api.core.ApiFutureCallback;
import com.google.api.core.ApiFutures;
import com.google.api.gax.batching.BatchingSettings;
import com.google.api.gax.batching.FlowControlSettings;
import com.google.api.gax.batching.FlowController;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.core.FixedCredentialsProvider;
import com.google.api.gax.core.FixedExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.ApiException;
import com.google.auth.oauth2.ServiceAccountCredentials;
import com.google.cloud.pubsub.v1.Publisher;
import com.google.cloud.pubsub.v1.TopicAdminClient;
import com.google.common.util.concurrent.MoreExecutors;
import com.google.protobuf.ByteString;
import com.google.pubsub.v1.ProjectTopicName;
import com.google.pubsub.v1.PubsubMessage;
import org.joda.time.DateTime;
import org.threeten.bp.Duration;

import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;


public class CreateTopicAndPublishMessagesAs {
    static int cnt=0;
    public static void main(String... args) throws Exception {
        createTopic();
        publishMessages();
    }

    public static void createTopic() throws Exception {

        ProjectTopicName topic = ProjectTopicName.of("myproject", "mytopic");
        TopicAdminClient topicAdminClient = TopicAdminClient.create();
            topicAdminClient.createTopic(topic);
    }

    public static void publishMessages() throws Exception {
        ProjectTopicName topicName = ProjectTopicName.of("myproject", "mytopic");
        Publisher publisher ;
        CredentialsProvider credentialsProvider =
                FixedCredentialsProvider.create(
                        ServiceAccountCredentials.fromStream(new FileInputStream("/Users/apple/MultipleCredFiles/google-cred-file.json")));
         FlowController.LimitExceededBehavior le = FlowController.LimitExceededBehavior.valueOf("Block");

        FlowControlSettings flowControlSettings = FlowControlSettings.newBuilder().setMaxOutstandingElementCount(10000L)
                .setMaxOutstandingRequestBytes(10000L).setLimitExceededBehavior(le).build();

        BatchingSettings batchingSettings =
                BatchingSettings.newBuilder()
                        .setElementCountThreshold(1000L)
                        .setRequestByteThreshold(1000000L)
                        .setDelayThreshold(Duration.ofSeconds(60)).setFlowControlSettings(flowControlSettings)
                        .build();

        RetrySettings retrySettings =
                RetrySettings.newBuilder()
                        .setInitialRetryDelay(Duration.ofMillis(1))
                        .setRetryDelayMultiplier(2.0)
                        .setMaxRetryDelay(Duration.ofSeconds(10))
                        .setTotalTimeout(Duration.ofSeconds(10))
                        .setInitialRpcTimeout(Duration.ofSeconds(10))
                        .setMaxRpcTimeout(Duration.ofSeconds(100))
                        .build();

        ExecutorProvider executorProvider = FixedExecutorProvider.create(Executors.newScheduledThreadPool(10));

        publisher = Publisher.newBuilder(topicName)
                .setCredentialsProvider(credentialsProvider).setBatchingSettings(batchingSettings)
                .setRetrySettings(retrySettings)
        .setExecutorProvider(executorProvider).build();
        try {
        int i = 0;
        while (i<20000) {

                String messages = "Data of 500 bytes";
               
                    ByteString data = ByteString.copyFromUtf8(messages);
                    PubsubMessage pubsubMessage = PubsubMessage.newBuilder().setData(data).build();

                    ApiFuture<String> messageIdFuture = publisher.publish(pubsubMessage);
                    ApiFutures.addCallback(
                            messageIdFuture,
                            new ApiFutureCallback<String>() {

                                @Override
                                public void onFailure(Throwable throwable) {
                                    if (throwable instanceof ApiException) {
                                        ApiException apiException = ((ApiException) throwable);
                                    System.out.println(apiException.fillInStackTrace());                              
                                    }
                                    System.out.println("Error publishing message : " + messages);
                                }

                                @Override
                                public void onSuccess(String messageId) {
                                    // Once published, returns server-assigned message ids (unique within the topic)
                                    System.out.println(messageId);
                                    //System.out.println("Done : " + cnt++);
                                }
                            },
                            MoreExecutors.directExecutor());

               i++; }
            } finally {
                if (publisher != null) {
                    // When finished with the publisher, shutdown to free up resources.
                    System.out.println("Shut down");
                    publisher.shutdown();
                    publisher.awaitTermination(1, TimeUnit.MINUTES);
                }
            }
        }
    }

```

**Comment by ajaaym** [comment]
@tanuja5 Element Count Threshold in  batching settings is still 1000 in sample code. Did you try that with higher number like 50k or 100k? As of now flow control setting is not respected by publisher client.

**Comment by tanuja5** [comment]
Yes, I have tried with higher element count with even higher byte threshold and interval to meet the element count threshold, I changed the config and sent about 50k events like:

`BatchingSettings batchingSettings =
                BatchingSettings.newBuilder()
                        .setElementCountThreshold(50000L)
                        .setRequestByteThreshold(30000000L)
                        .setDelayThreshold(Duration.ofSeconds(60))
                        .build();`

But i still get the exception. Is there a benchmark that is done to know how much a batch can hold at a given time?

**Comment by ajaaym** [comment]
@tanuja5 batch can hold the element based on threshold provided. Howz the connectivity between your application and gcp? Can you add delay in publishing message after number of message same as element count threshold?

**Comment by tanuja5** [comment]
The connection has been stable. As per your suggestion, 
I tried adding delay and batched 10000 events with a batch size of 1000 which usually passes, When tried with a higher batching ex: 2000 for same number of events, it fails.

**Comment by tanuja5** [comment]
@ajaaym 
I am getting a new exception when testing with EventCount set 1100.

`io.grpc.StatusRuntimeException: INVALID_ARGUMENT: The value for 1100 is too large. You passed message_count in the request, but the maximum value is 1000.. Cause: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: The value for 1100 is too large. You passed message_count in the request, but the maximum value is 1000.
	at com.myorg.proc.MyClass$MyInnerClass.onFailure(MyClass.java:324)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.core.SettableApiFuture.setException(SettableApiFuture.java:52)
	at com.google.cloud.pubsub.v1.Publisher$4.onFailure(Publisher.java:351)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:162)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: The value for 1100 is too large. You passed message_count in the request, but the maximum value is 1000.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	... 31 more
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: The value for 1100 is too large. You passed message_count in the request, but the maximum value is 1000.
	at io.grpc.Status.asRuntimeException(Status.java:526)
	... 23 more
`
And I am still seeing deadline exceeded with batch size 1000 and 10k events.

Can you please help me deal with above.

**Comment by ajaaym** [comment]
@tanuja5 Can you please share the exact code that you are using for this error "INVALID_ARGUMENT: The value for 1100 is too large. You passed message_count in the request, but the maximum value is 1000."?

**Comment by tanuja5** [comment]
@ajaaym It is the same code that i have commented above. 

```
package org.example.pubsub;

import com.google.api.core.ApiFuture;
import com.google.api.core.ApiFutureCallback;
import com.google.api.core.ApiFutures;
import com.google.api.gax.batching.BatchingSettings;
import com.google.api.gax.batching.FlowControlSettings;
import com.google.api.gax.batching.FlowController;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.core.FixedCredentialsProvider;
import com.google.api.gax.core.FixedExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.ApiException;
import com.google.auth.oauth2.ServiceAccountCredentials;
import com.google.cloud.pubsub.v1.Publisher;
import com.google.cloud.pubsub.v1.TopicAdminClient;
import com.google.common.util.concurrent.MoreExecutors;
import com.google.protobuf.ByteString;
import com.google.pubsub.v1.ProjectTopicName;
import com.google.pubsub.v1.PubsubMessage;
import org.joda.time.DateTime;
import org.threeten.bp.Duration;

import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;


public class CreateTopicAndPublishMessagesAs {
    static int cnt=0;
    public static void main(String... args) throws Exception {
        createTopic();
        publishMessages();
    }

    public static void createTopic() throws Exception {

        ProjectTopicName topic = ProjectTopicName.of("myproject", "mytopic");
        TopicAdminClient topicAdminClient = TopicAdminClient.create();
            topicAdminClient.createTopic(topic);
    }

    public static void publishMessages() throws Exception {
        ProjectTopicName topicName = ProjectTopicName.of("myproject", "mytopic");
        Publisher publisher ;
        CredentialsProvider credentialsProvider =
                FixedCredentialsProvider.create(
                        ServiceAccountCredentials.fromStream(new FileInputStream("/Users/apple/MultipleCredFiles/google-cred-file.json")));
        // FlowController.LimitExceededBehavior le = FlowController.LimitExceededBehavior.valueOf("Block");

     //   FlowControlSettings flowControlSettings = FlowControlSettings.newBuilder().setMaxOutstandingElementCount(10000L)
         //       .setMaxOutstandingRequestBytes(10000L).setLimitExceededBehavior(le).build();

        BatchingSettings batchingSettings =
                BatchingSettings.newBuilder()
                        .setElementCountThreshold(1100L)
                        .setRequestByteThreshold(1000000L)
                        .setDelayThreshold(Duration.ofSeconds(60))
//.setFlowControlSettings(flowControlSettings)
                        .build();

        RetrySettings retrySettings =
                RetrySettings.newBuilder()
                        .setInitialRetryDelay(Duration.ofMillis(1))
                        .setRetryDelayMultiplier(2.0)
                        .setMaxRetryDelay(Duration.ofSeconds(10))
                        .setTotalTimeout(Duration.ofSeconds(10))
                        .setInitialRpcTimeout(Duration.ofSeconds(10))
                        .setMaxRpcTimeout(Duration.ofSeconds(100))
                        .build();

        ExecutorProvider executorProvider = FixedExecutorProvider.create(Executors.newScheduledThreadPool(10));

        publisher = Publisher.newBuilder(topicName)
                .setCredentialsProvider(credentialsProvider).setBatchingSettings(batchingSettings)
                .setRetrySettings(retrySettings)
        .setExecutorProvider(executorProvider).build();
        try {
        int i = 0;
        while (i<20000) {

                String messages = "Data of 500 bytes";
               
                    ByteString data = ByteString.copyFromUtf8(messages);
                    PubsubMessage pubsubMessage = PubsubMessage.newBuilder().setData(data).build();

                    ApiFuture<String> messageIdFuture = publisher.publish(pubsubMessage);
                    ApiFutures.addCallback(
                            messageIdFuture,
                            new ApiFutureCallback<String>() {

                                @Override
                                public void onFailure(Throwable throwable) {
                                    if (throwable instanceof ApiException) {
                                        ApiException apiException = ((ApiException) throwable);
                                    System.out.println(apiException.fillInStackTrace());                              
                                    }
                                    System.out.println("Error publishing message : " + messages);
                                }

                                @Override
                                public void onSuccess(String messageId) {
                                    // Once published, returns server-assigned message ids (unique within the topic)
                                    System.out.println(messageId);
                                    //System.out.println("Done : " + cnt++);
                                }
                            },
                            MoreExecutors.directExecutor());

               i++; }
            } finally {
                if (publisher != null) {
                    // When finished with the publisher, shutdown to free up resources.
                    System.out.println("Shut down");
                    publisher.shutdown();
                    publisher.awaitTermination(1, TimeUnit.MINUTES);
                }
            }
        }
    }
```

**Comment by tanuja5** [comment]
@ajaaym Can you please suggest a fine tuned batch policy for Publishing say a, 100k events. What would be the appropriate number of messages to be sent in a batch of :-  

EventCount:x,
Interval:y,
Size:z

**Comment by codyoss** [comment]
@tanuja5 I am closing this as I believe the suggestion above should have fixed your issue. If it did not please feel free to re-open with more details. Thanks.
