### ISSUE TITLE
google-cloud-speech: java.lang.IllegalStateException: Failed to unpack object from 'any' field.

### ISSUE THREAD

**Issue by milenkara** [googleapis/google-cloud-java#4873]
#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: Ubuntu 18.04
3. Java version: 10.0.2
4. google-cloud-java version(s):

#### Steps to reproduce

  1. Run Asynchronous speech recognition for file in the on the link: https://drive.google.com/open?id=1iB319pvY3yAlInphXKFK_frDTocfD3KE . File is in Portuguese. During analysis we are getting java.lang.IllegalStateException

#### Code example

```java
try (SpeechClient speechClient = SpeechClient.create()) {

            RecognitionConfig.Builder configBuilder = RecognitionConfig.newBuilder()
                    .setLanguageCode(request.getLanguageCode())
                    .setEncoding(LINEAR16)
                    .setEnableWordTimeOffsets(true)
                    .setSampleRateHertz(request.getSampleRate());

            RecognitionConfig config = configBuilder.build();

            RecognitionAudio audio = RecognitionAudio.newBuilder()
                    .setUri(googleStorageUri)
                    .build();

            OperationFuture<LongRunningRecognizeResponse, LongRunningRecognizeMetadata> response =
                    speechClient.longRunningRecognizeAsync(config, audio);

            for (int i : List.rangeClosed(1, request.getPollingRetryCount())) {
                if (!response.isDone()) {
                    if (i < request.getPollingRetryCount()) {
                        LOGGER.info("[Google] Request {} not finished. Retry counter {}. Checking again in {} seconds.", request.getRequestId(), i, request.getPollingInterval());
                    } else {
                        LOGGER.info("[Google] Request {} not finished. Retry counter {}.", request.getRequestId(), i);
                    }
                    Thread.sleep(request.getPollingInterval() * 1000);
                } else
                    break;
            }

            if (!response.isDone()) {
                LOGGER.info("[Google] Request {} not finished after running out of polling retries. Returning failure.", request.getRequestId());
                return Either.left(new GenericError("Request timeout on Google AI provider."));
            }

            LOGGER.info("[Google] Method processAudio on Google AI provider finished for RequestID {}.", request.getRequestId());
            return Either.right(response.get());

```

#### Stack trace
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnknownException: java.lang.IllegalStateException: Failed to unpack object from 'any' field. Expected com.google.cloud.speech.v1.LongRunningRecognizeResponse, found 
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:459) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:107) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at ai.aiconix.cox.client.GoogleSpeechClient.speechToText(GoogleSpeechClient.java:63) [google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at ai.aiconix.cox.polling.SpeechToTextActor.lambda$createReceive$1(SpeechToTextActor.java:57) [google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.vavr.control.Either.flatMap(Either.java:331) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at ai.aiconix.cox.polling.SpeechToTextActor.lambda$createReceive$49525aa9$1(SpeechToTextActor.java:57) [google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.vavr.control.Try$WithResources1.lambda$of$97fea75d$1(Try.java:1203) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.vavr.control.Try.of(Try.java:75) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.vavr.control.Try$WithResources1.of(Try.java:1201) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at ai.aiconix.cox.polling.SpeechToTextActor.lambda$createReceive$5(SpeechToTextActor.java:46) [google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.vavr.control.Either.peek(Either.java:486) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at ai.aiconix.cox.polling.SpeechToTextActor.lambda$createReceive$6(SpeechToTextActor.java:45) [google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:517) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.actor.Actor.aroundReceive$(Actor.scala:515) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:147) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:559) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [amazon-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
Caused by: com.google.api.gax.rpc.UnknownException: java.lang.IllegalStateException: Failed to unpack object from 'any' field. Expected com.google.cloud.speech.v1.LongRunningRecognizeResponse, found 
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:117) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.grpc.ProtoOperationTransformers$ResponseTransformer.apply(ProtoOperationTransformers.java:69) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.grpc.ProtoOperationTransformers$ResponseTransformer.apply(ProtoOperationTransformers.java:46) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.core.ApiFutures$GaxFunctionToGuavaFunction.apply(ApiFutures.java:180) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:239) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:229) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:159) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:134) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:114) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:159) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:134) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:114) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.set(AbstractApiFuture.java:90) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.core.AbstractApiFuture.set(AbstractApiFuture.java:73) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onSuccess(GrpcExceptionCallable.java:86) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.core.ApiFutures$1.onSuccess(ApiFutures.java:66) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1132) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:487) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:465) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) ~[?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:844) ~[?:?]
Caused by: java.lang.IllegalStateException: Failed to unpack object from 'any' field. Expected com.google.cloud.speech.v1.LongRunningRecognizeResponse, found 
	at com.google.api.gax.grpc.ProtoOperationTransformers$AnyTransformer.apply(ProtoOperationTransformers.java:131) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.grpc.ProtoOperationTransformers$ResponseTransformer.apply(ProtoOperationTransformers.java:67) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.grpc.ProtoOperationTransformers$ResponseTransformer.apply(ProtoOperationTransformers.java:46) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.core.ApiFutures$GaxFunctionToGuavaFunction.apply(ApiFutures.java:180) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:239) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:229) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:159) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:134) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:114) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:159) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:134) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:114) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.set(AbstractApiFuture.java:90) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.core.AbstractApiFuture.set(AbstractApiFuture.java:73) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onSuccess(GrpcExceptionCallable.java:86) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.api.core.ApiFutures$1.onSuccess(ApiFutures.java:66) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1132) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:487) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:465) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[google-plugin-1.7.1-SNAPSHOT-jar-with-dependencies.jar!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) ~[?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:844) ~[?:?]
```

#### External references such as API reference guides used	

- https://cloud.google.com/speech-to-text/docs/async-recognize#speech-async-recognize-gcs-java	

#### Any additional information below	
We originaly reproduced this bug with google-cloud-speech version 0.61.0-beta but we got the same behaviour with the newest version.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by pmakani** [comment]
@milenkara I have tested above example and it's working fine, can you please try with latest version ?

**Comment by milenkara** [comment]
Thanks @pmakani for the info. I have updated our client library to newest version and exception from the description is not happening anymore for the reported file. 
The only strange thing is that results we are getting now are empty (there are no alternatives). Not sure if you got the same behavior, but this may be separate issue.

**Comment by pmakani** [comment]
@milenkara Below code is working fine and getting alternatives result , can you try this ?

```
public class SpeechExample {


  public static void main(String[] args)  {
    String googleStorageUri = "gs://yourstorageurl/hello-pt.mp3.wav";
    asyncRecognizeGcs(googleStorageUri);
  }

  public static void asyncRecognizeGcs(String gcsUri)  {
   
    try (SpeechClient speech = SpeechClient.create()) {
      RecognitionConfig config =
              RecognitionConfig.newBuilder()
                      .setEncoding(RecognitionConfig.AudioEncoding.LINEAR16)
                      .setLanguageCode("pt-PT")
                      .setSampleRateHertz(16000)
                      .build();
      RecognitionAudio audio = RecognitionAudio.newBuilder().setUri(gcsUri).build();
       OperationFuture<LongRunningRecognizeResponse, LongRunningRecognizeMetadata> response =
              speech.longRunningRecognizeAsync(config, audio);
      while (!response.isDone()) {
        System.out.println("Waiting for response...");
        Thread.sleep(10000);
      }

      List<SpeechRecognitionResult> results = response.get().getResultsList();

      for (SpeechRecognitionResult result : results) {
        SpeechRecognitionAlternative alternative = result.getAlternativesList().get(0);
        System.out.printf("Transcription: %s\n", alternative.getTranscript());
      }
    }
    catch (Exception e){
      e.printStackTrace();
    }
  }
}
```

**Comment by milenkara** [comment]
@pmakani Hah I spotted one difference and for some reason in our domain model language code for Portuguese is `pt-BR` instead of `pt-PT` and when I changed it, speech analysis works correctly. Thanks once again. I assume you can close the issue.
