### ISSUE TITLE
how to fix io.grpc.internal.CallCredentialsApplyingTransportFactory.getScheduledExecutorService

### ISSUE THREAD

**Issue by prokulit06** [googleapis/google-cloud-java#4919]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ezminute, PID: 10348
    java.lang.AbstractMethodError: abstract method "java.util.concurrent.ScheduledExecutorService io.grpc.internal.ClientTransportFactory.getScheduledExecutorService()"
        at io.grpc.internal.CallCredentialsApplyingTransportFactory.getScheduledExecutorService(CallCredentialsApplyingTransportFactory.java:52)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:569)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:440)
        at com.example.ezminute.CloudSpeechService$AccessTokenTask.onPostExecute(CloudSpeechService.java:422)
        at com.example.ezminute.CloudSpeechService$AccessTokenTask.onPostExecute(CloudSpeechService.java:375)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by ajaaym** [comment]
@prokulit06 can you please provide the sample code that you are using?

**Comment by sduskis** [comment]
@prokulit06, we can't fix this bug, since we don't have enough information.  Please open up a new bug with more information, including the code sample you're using along with the dependencies.
