### ISSUE TITLE
Getting :  com.google.api.gax.core.GaxProperties.getLibraryVersion(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/String Error while connecting to Cloud Spanner Via java code

### ISSUE THREAD

**Issue by KandasamySurya** [googleapis/google-cloud-java#4941]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-java/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version:
4. google-cloud-java version(s):

#### Steps to reproduce

  1. ?
  2. ? 

#### Code example

```java
// example
```

#### Stack trace
```
Any relevant stacktrace here.
```

#### External references such as API reference guides used	

- ?	

#### Any additional information below	

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by KandasamySurya** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: com.google.api.gax.core.GaxProperties.getLibraryVersion(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/String;
	at com.google.api.gax.grpc.GaxGrpcProperties.<clinit>(GaxGrpcProperties.java:41)
	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.<init>(GapicSpannerRpc.java:161)
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerRpcFactory.create(SpannerOptions.java:71)
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerRpcFactory.create(SpannerOptions.java:66)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:472)
	at com.google.cloud.spanner.SpannerOptions.getSpannerRpcV1(SpannerOptions.java:270)
	at com.google.cloud.spanner.SpannerImpl.<init>(SpannerImpl.java:177)
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:61)
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:56)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:459)
	at com.kohls.googlespanner.connections.CloudSpannerConnecton.getConnectionDetails(CloudSpannerConnecton.java:25)
	at com.kohls.googlespanner.connections.CloudSpannerConnecton.main(CloudSpannerConnecton.java:59)

**Comment by sduskis** [comment]
@KandasamySurya, this seems like it could be a conflict with other dependencies.  Are you using other Google Cloud libraries?  Can you please share the versions of the cloud libraries you are using?

**Comment by KandasamySurya** [comment]
ok sure sir

**Comment by KandasamySurya** [comment]
[Spanner1.zip](https://github.com/googleapis/google-cloud-java/files/3083988/Spanner1.zip)

These are the jars I have used

**Comment by KandasamySurya** [comment]
[Spanner2.zip](https://github.com/googleapis/google-cloud-java/files/3083995/Spanner2.zip)

Also these

**Comment by sduskis** [comment]
@KandasamySurya, are you using maven?  If so, can you please do a `mvn dependency:tree`?

**Comment by sduskis** [comment]
`Spanner2.zip` has different versions for the same artifacts.  That's going to be a problem.  

Another problem is that you have dependencies for google cloud libraries that may be incompatible; you're using google-cloud-(storage|spanner|logging) that are not compatible.  Please see [here](https://github.com/googleapis/google-cloud-java/blob/v0.72.0/google-cloud-bom/pom.xml) for list of compatible versions.

**Comment by KandasamySurya** [comment]
ok . I will check with the compatible versions. Thanks a lot for your valuable input
