### ISSUE TITLE
java.lang.NoSuchMethodError on Google PubSub Publisher.newBuilder().build()

### ISSUE THREAD

**Issue by Sahand1993** [googleapis/google-cloud-java#5197]
I'm getting this error stack trace:

```
Exception in thread "main" java.lang.NoSuchMethodError: io.grpc.okhttp.OkHttpChannelProvider.isAndroid()Z
	at io.grpc.okhttp.OkHttpChannelProvider.priority(OkHttpChannelProvider.java:51)
	at io.grpc.ManagedChannelProvider$1.getPriority(ManagedChannelProvider.java:49)
	at io.grpc.ManagedChannelProvider$1.getPriority(ManagedChannelProvider.java:41)
	at io.grpc.ServiceProviders$1.compare(ServiceProviders.java:79)
	at java.util.Collections$ReverseComparator2.compare(Collections.java:5178)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:175)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:76)
	at io.grpc.ServiceProviders.load(ServiceProviders.java:42)
	at io.grpc.ManagedChannelProvider.<clinit>(ManagedChannelProvider.java:37)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:37)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:194)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:169)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:156)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:157)
	at com.google.cloud.pubsub.v1.stub.GrpcPublisherStub.create(GrpcPublisherStub.java:164)
	at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:152)
	at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:82)
	at com.google.cloud.pubsub.v1.Publisher$Builder.build(Publisher.java:597)
	at TrackingAPI.sendEvent(TrackingAPI.java:20)
	at EventGenerator.sendRandomEvents(EventGenerator.java:46)
	at EventGenerator.main(EventGenerator.java:22)
```

When executing this line:

`Publisher publisher = Publisher.newBuilder(TOPIC_ID).build();`. I suspect some dependency issue. This is my pom-file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.findwise.app</groupId>
    <artifactId>data-pipeline</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-core</artifactId>
            <version>1.19.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-storage</artifactId>
            <version>1.73.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-pubsub</artifactId>
            <version>1.73.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud.dataflow</groupId>
            <artifactId>google-cloud-dataflow-java-sdk-all</artifactId>
            <version>2.5.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.grpc</groupId>
                    <artifactId>grpc-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>
```

What is the reason for this issue?

**Comment by chingor13** [comment]
This looks like a mismatch of grpc versions. Is there a reason you're locking the grpc version to 1.19?

**Comment by sduskis** [comment]
I assume that you want to set a specific version of grpc, since Dataflow and and the other clients don't use the same versions.  I would suggest using the grpc-bom instead of importing `grpc:grpc-core`.

To do that, remove the `grpc:grpc-core` dependency and add this new section in your `pom.xml`:

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
               <groupId>io.grpc</groupId>
                <artifactId>grpc-bom</artifactId>
                <version>1.19.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

That will import a consistent version of all `grpc-*` related artifacts, including the right version of ok-http.

We really need to write all of this up in a doc on this GitHub project.

**Comment by sduskis** [comment]
There isn't much more we can do on this issue.  Please feel free to open a new issue, or comment on this one if you need more of a follow up.
