### ISSUE TITLE
Dialog Flow v2 Android Application Default Credentials are not available.

### ISSUE THREAD

**Issue by Geck0x86** [googleapis/google-cloud-java#5245]
Hello. I'm trying to test dialog flow on an android device. I have been searching documentation about this and only find documentation about java, but not android. 

I set GOOGLE_APPLICATION_CREDENTIALS environment variable on my laptop. But I think I need to do the same on device but I don't know how.

Here is my code:
```kotlin
            val stream = assets.open("XXX.json")
            val credentials = GoogleCredentials.fromStream(stream)
            val projectId = (credentials as ServiceAccountCredentials).projectId

            val settingsBuilder = SessionsSettings.newBuilder()
            val sessionsSettings = settingsBuilder.setCredentialsProvider(FixedCredentialsProvider.create(credentials)).build()
            sessionsClient = SessionsClient.create(sessionsSettings)
            session = SessionName.of(projectId, UUID.randomUUID().toString()) 
```

And generates an error on line:
```
SessionsClient.create()
```

I get this output in logcat
```
I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
I/omputeEngineCredentials: Failed to detect whether we are running on Google Compute Engine.
W/System.err: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
W/System.err:     at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:132)
W/System.err:     at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:115)
W/System.err:     at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:88)
W/System.err:     at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:67)
W/System.err:     at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:140)
W/System.err:     at com.google.cloud.dialogflow.v2beta1.stub.GrpcSessionsStub.create(GrpcSessionsStub.java:78)
W/System.err:     at com.google.cloud.dialogflow.v2beta1.stub.SessionsStubSettings.createStub(SessionsStubSettings.java:103)
W/System.err:     at com.google.cloud.dialogflow.v2beta1.SessionsClient.<init>(SessionsClient.java:132)
W/System.err:     at com.google.cloud.dialogflow.v2beta1.SessionsClient.create(SessionsClient.java:114)
W/System.err:     at com.google.cloud.dialogflow.v2beta1.SessionsClient.create(SessionsClient.java:106)
W/System.err:     at com.helloauto.blackbox.DetectIntentAudio.detectIntentAudio(DetectIntentAudio.kt:33)
W/System.err:     at com.helloauto.blackbox.MainActivity$RequestTask.doInBackground(MainActivity.kt:75)
W/System.err:     at com.helloauto.blackbox.MainActivity$RequestTask.doInBackground(MainActivity.kt:65)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
```

Thank you in advance

**Comment by Geck0x86** [comment]
We found the answer.

We forget to add SessionsSettings in SessionsClient.create() function

Thank you
