### ISSUE TITLE
Bigtable: INTERNAL: HTTP/2 error code: INTERNAL_ERROR Received Rst Stream as a retryable status code

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#5519]
Long lived connections are sometimes disconnected via a RST frame. These should be handled similar to UNAVAILABLE. Also need to make sure that GOAWAYs are handled similar.

This is the same issue as https://github.com/googleapis/cloud-bigtable-client/issues/2177

**Comment by sduskis** [comment]
Did this come from Dataflow?  If so, which version of grpc was used?

**Comment by igorbernstein2** [comment]
Not sure if this is dataflow but customer said that this happened during batch jobs using the hbase client 1.11. I'll try to replicate it next week

**Comment by igorbernstein2** [comment]
I think we should try to remap this to an UNAVAILABLE error so that its similar to the more common gfe reset:

```
UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:584)
	at Main.main(Main.java:36)
Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.grpc.netty.shaded.io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
```

**Comment by kmjung** [comment]
Any updates here?

**Comment by igorbernstein2** [comment]
We haven't been able to reproduce this. So I'm not sure if this should be paved over in the bigable client or if the fix needs to be pushed down to the grpc layer. Is this something you are experiencing? If so, can you offer some details as to when you are experiencing this issue?
