### ISSUE TITLE
Cloud Tasks:  INVALID_ARGUMENT: HttpRequest.url is required

### ISSUE THREAD

**Issue by bsnisar** [googleapis/google-cloud-java#5659]
Hello!

#### Steps to reproduce

This issue is a try to create a workaround  for issue https://github.com/googleapis/google-cloud-java/issues/5555

According to suggestions in a comments
```
// @see https://github.com/googleapis/google-cloud-java/issues/5555
libraryDependencies += "com.google.cloud" % "google-cloud-tasks" % "1.7.0" excludeAll(
  ExclusionRule(organization = "com.google.cloud", name = "gax"),
  ExclusionRule(organization = "com.google.cloud", name = "gax-grpc")
)

libraryDependencies += "com.google.api" % "gax-grpc" % "1.47.0"
libraryDependencies += "com.google.api" % "gax" % "1.47.0"
```

#### Code example

```scala
val queuePath = QueueName.of(
        settings.gcpProjectId,
        settings.cloudTasksLocation,
        settings.cloudTasksBotQueue
      ).toString

      val taskBuilder =
        Task.newBuilder()
          .setHttpRequest(
            HttpRequest.newBuilder()
              .setBody(ByteString.copyFrom(payload, Charset.defaultCharset()))
              .setUrl(url)
              .setHttpMethod(HttpMethod.POST)
              .setOidcToken(oidcTokenBuilder)
              .build())

      logger.debug(s"[$queuePath] $url  - prepare to submit $job")
      val task = client.createTask(queuePath, taskBuilder)
```

#### Stack trace
```
......
		at scala.util.Success.$anonfun$map$1(Try.scala:255)
		at scala.util.Success.map(Try.scala:213)
		at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
		at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: HttpRequest.url is required.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
....
```

Thanks!

**Comment by bsnisar** [comment]
Close because of mine code issue
