### ISSUE TITLE
The newest version of google-cloud-speech jar bug report

### ISSUE THREAD

**Issue by lizekui** [googleapis/google-cloud-java#5662]
#### Environment details

1. Win 10 + Eclipse + JDK8
2. google-cloud-java version(s):
```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-speech</artifactId>
    <version>1.10.0</version>
</dependency>
```

#### Steps to reproduce

  1. When I run codes below  (official sample codes):
```
	public static void main(String... args) throws Exception {
		try (SpeechClient speech = SpeechClient.create()) {
			RecognitionConfig config = RecognitionConfig.newBuilder().setEncoding(AudioEncoding.LINEAR16)
					.setLanguageCode("en-US").setSampleRateHertz(16000).build();
			RecognitionAudio audio = RecognitionAudio.newBuilder().setUri(gcsUriEN).build();

			OperationFuture<LongRunningRecognizeResponse, LongRunningRecognizeMetadata> response = speech
					.longRunningRecognizeAsync(config, audio);
			while (!response.isDone()) {
				System.out.println("Waiting for response...");
				Thread.sleep(10000);
			}

			List<SpeechRecognitionResult> results = response.get().getResultsList();

			for (SpeechRecognitionResult result : results) {
				SpeechRecognitionAlternative alternative = result.getAlternativesList().get(0);
				System.out.printf("Transcription: %s\n", alternative.getTranscript());
			}
		}
	}
```

 2. I get the error below:
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: io.opencensus.tags.TagContextBuilder.putPropagating(Lio/opencensus/tags/TagKey;Lio/opencensus/tags/TagValue;)Lio/opencensus/tags/TagContextBuilder;
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:127)
	at com.xxx.cloudsdk.sample.GCloudSpeechSample.main(GCloudSpeechSample.java:38)
Caused by: java.lang.NoSuchMethodError: io.opencensus.tags.TagContextBuilder.putPropagating(Lio/opencensus/tags/TagKey;Lio/opencensus/tags/TagValue;)Lio/opencensus/tags/TagContextBuilder;
	at io.grpc.internal.CensusStatsModule$ClientCallTracer.<init>(CensusStatsModule.java:359)
	at io.grpc.internal.CensusStatsModule.newClientCallTracer(CensusStatsModule.java:146)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor.interceptCall(CensusStatsModule.java:689)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at com.google.api.gax.grpc.GrpcChannelUUIDInterceptor.interceptCall(GrpcChannelUUIDInterceptor.java:52)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor.interceptCall(GrpcHeaderInterceptor.java:80)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at com.google.api.gax.grpc.GrpcMetadataHandlerInterceptor.interceptCall(GrpcMetadataHandlerInterceptor.java:55)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:814)
	at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
	at com.google.api.gax.grpc.GrpcClientCalls.newCall(GrpcClientCalls.java:90)
	at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:58)
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
	at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:86)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
	at com.google.api.gax.grpc.GrpcOperationSnapshotCallable.futureCall(GrpcOperationSnapshotCallable.java:58)
	at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75)
	at com.google.api.gax.tracing.TracedOperationInitialCallable.futureCall(TracedOperationInitialCallable.java:61)
	at com.google.api.gax.rpc.OperationCallableImpl.futureCall(OperationCallableImpl.java:82)
	at com.google.api.gax.tracing.TracedOperationCallable.futureCall(TracedOperationCallable.java:78)
	at com.google.api.gax.rpc.OperationCallable$1.futureCall(OperationCallable.java:150)
	at com.google.api.gax.rpc.OperationCallable.futureCall(OperationCallable.java:67)
	at com.google.cloud.speech.v1.SpeechClient.longRunningRecognizeAsync(SpeechClient.java:360)
	at com.google.cloud.speech.v1.SpeechClient.longRunningRecognizeAsync(SpeechClient.java:320)
	at com.xxx.cloudsdk.sample.GCloudSpeechSample.main(GCloudSpeechSample.java:32)
```

But I change google-cloud-speech version to 1.6 this bug disappear. (1.9 does not work too)
Thanks!

**Comment by pmakani** [comment]
@lizekui , I have tried your above example and it's works fine, also tried different version which you have mentioned and works fine.

**Comment by vumutduman** [comment]
I got same error for speech recognize streaming service when I used below dependencies same time:

```
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-speech</artifactId>
            <version>1.7.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-storage</artifactId>
            <version>1.81.0</version>
        </dependency>
```

**Comment by lizekui** [comment]
Thanks @pmakani attention !

Sorry my slow reply... As @vumutduman said, I forget put my  google-cloud-storage pom:
```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-speech</artifactId>
    <version>1.10.0 or 1.9.0 reports bug log</version>
</dependency>

<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-storage</artifactId>
    <version>1.60.0</version>
</dependency>
```
I guess maybe the  google-cloud-storage version exists dependencies with google-cloud-speech too?

**Comment by pmakani** [comment]
> I got same error for speech recognize streaming service when I used below dependencies same time:
> 
> ```
>         <dependency>
>             <groupId>com.google.cloud</groupId>
>             <artifactId>google-cloud-speech</artifactId>
>             <version>1.7.0</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>com.google.cloud</groupId>
>             <artifactId>google-cloud-storage</artifactId>
>             <version>1.81.0</version>
>         </dependency>
> ```

@vumutduman  i tried dependencies which you mentioned and it's works fine, can you try with latest version of both dependency ?

**Comment by pmakani** [comment]
> Thanks @pmakani attention !
> 
> Sorry my slow reply... As @vumutduman said, I forget put my google-cloud-storage pom:
> 
> ```
> <dependency>
>     <groupId>com.google.cloud</groupId>
>     <artifactId>google-cloud-speech</artifactId>
>     <version>1.10.0 or 1.9.0 reports bug log</version>
> </dependency>
> 
> <dependency>
>     <groupId>com.google.cloud</groupId>
>     <artifactId>google-cloud-storage</artifactId>
>     <version>1.60.0</version>
> </dependency>
> ```
> 
> I guess maybe the google-cloud-storage version exists dependencies with google-cloud-speech too?

@lizekui i used same dependency, which you are using and got the same error , after i tried latest version of storage dependency and it's work fine, can you please try that ?

**Comment by lizekui** [comment]
```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-speech</artifactId>
    <version>1.11.0</version>
</dependency>

<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-storage</artifactId>
    <version>1.81.0</version>
</dependency>
```
Thanks dear @pmakani ! this latest version of both two jar dependency  works wonderfunlly fine!
