### ISSUE TITLE
Question: Handling 410 Gone errors when flushing buffer in BlobWriteChannel

### ISSUE THREAD

**Issue by viraj071** [googleapis/google-cloud-java#5704]
We are using GCS to store blob files. We provide a GCS implementation of an interface provided by an internal library. The implementation returns a `WritableByteChannel` which is used by the library. This means, adding a retry logic is not an easy option for us. Looking at the stack trace below, we see that it is created in the `BlobWriteChannel.flushBuffer` method.

Questions:
1. Does the SDK retry by default?
2. Is there any way for me to retry on such errors by configuration etc?

```
Caused by: com.google.cloud.storage.StorageException: 410 Gone
 {
  "error": {
   "errors": [
    {
     "domain": "global",
     "reason": "backendError",
     "message": "Backend Error"
    }
   ],
   "code": 500,
   "message": "Backend Error"
  }
 }
 
 at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:227)
 at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:762)
 at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:51)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
 at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
 at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
 at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:44)
 at com.google.cloud.BaseWriteChannel.close(BaseWriteChannel.java:151)
```

P.S: I see a similar issue https://github.com/googleapis/google-cloud-java/issues/3586 which was closed. The reason for me to open this one is to understand my options as a user of the SDK. This would be useful for anyone referencing this issue in the future.
I already have a question for this on [SO](https://stackoverflow.com/questions/56907896/gcs-retry-on-410-gone-errors-in-blobwritechannel-flushbuffer) but opened an issue here as did not get any response there.

**Comment by codyoss** [comment]
This issue is now being tracked here: https://b.corp.google.com/issues/137168102

Please respond with any further updates at the link above.
