### ISSUE TITLE
GKE Metadata server: Internal Error

### ISSUE THREAD

**Issue by neuromantik33** [googleapis/google-cloud-java#5747]
I'm unable to make use of the workload identity on GKE with the latest google cloud storage API. I've followed the guide [here](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_workload_identity_on_an_existing_cluster) and everything checks out with gcloud and the cloud-sdk image as mentioned
Here is my example groovy code:
```groovy
#!/usr/bin/env groovy
@Grapes([
  @Grab(group = 'com.google.cloud', module = 'google-cloud-storage', version = '1.82.0')
])

import com.google.api.gax.paging.Page
import com.google.cloud.storage.Blob
import com.google.cloud.storage.BlobId
import com.google.cloud.storage.Storage
import groovy.transform.CompileStatic
import groovy.transform.Field
import picocli.CommandLine
import picocli.groovy.PicocliScript

import static com.google.cloud.storage.BlobId.of as blobId
import static com.google.cloud.storage.Storage.BlobListOption.currentDirectory
import static com.google.cloud.storage.StorageOptions.getDefaultInstance

@PicocliScript
@CommandLine.Command(
  name = 'list-files',
  mixinStandardHelpOptions = true)

@Field Storage storage = defaultInstance.service

@CommandLine.Parameters(paramLabel = 'PATH')
@Field String basePath = null

println "basePath = $basePath"

listFiles(basePath)
  .each { println it }

@CompileStatic
def listFiles(String path) {

    def blob = parsePath(path)
    println "blob = $blob"
    def bucket = blob.bucket
    def extractNames = { Page<Blob> p -> p.iterateAll().toList()*.name }

    storage.list(bucket, currentDirectory())
      .collect(extractNames)
      .flatten()
      .collect { "gs://$bucket/$it" as String }

}

static BlobId parsePath(String path) {
    def m = path =~ /gs:\/\/([a-z_\-]+)\/.*/
    def bucket = m[0][1] as String
    def blob = "${m[0][2]}".replace('//', '/')
    blobId bucket, blob
}
```
My Dockerfile
```Dockerfile
FROM groovy
COPY list-files.groovy ./list-files
ENTRYPOINT ["./list-files"]
```
My Kubernetes Job Manifest
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: list-files
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - gs://<some_bucket>/
        image: eu.gcr.io/<redacted>/list-files:latest
        imagePullPolicy: Always
        name: list-files
      restartPolicy: Never
      serviceAccountName: default
```
My default service account is as the guide specified.

I'm getting this stacktrace:
```
Caught: picocli.CommandLine$ExecutionException: com.google.cloud.storage.StorageException: Unexpected Error code 500 trying to get security access token from Compute Engine metadata for the default service account: GKE Metadata Server: Internal Server Error

picocli.CommandLine$ExecutionException: com.google.cloud.storage.StorageException: Unexpected Error code 500 trying to get security access token from Compute Engine metadata for the default service account: GKE Metadata Server: Internal Server Error

	at picocli.groovy.PicocliBaseScript.handleExecutionException(PicocliBaseScript.java:262)
	at picocli.groovy.PicocliBaseScript.run(PicocliBaseScript.java:124)
Caused by: com.google.cloud.storage.StorageException: Unexpected Error code 500 trying to get security access token from Compute Engine metadata for the default service account: GKE Metadata Server: Internal Server Error

	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:226)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:367)
	at com.google.cloud.storage.StorageImpl$8.call(StorageImpl.java:355)
	at com.google.cloud.storage.StorageImpl$8.call(StorageImpl.java:352)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:351)
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:307)
	at list-files.listFiles(list-files:42)
	at list-files$listFiles.callCurrent(Unknown Source)
	at list-files.runScriptBody(list-files:31)
	at picocli.groovy.PicocliBaseScript.run(PicocliBaseScript.java:122)
Caused by: java.io.IOException: Unexpected Error code 500 trying to get security access token from Compute Engine metadata for the default service account: GKE Metadata Server: Internal Server Error

	at com.google.auth.oauth2.ComputeEngineCredentials.refreshAccessToken(ComputeEngineCredentials.java:139)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:165)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:151)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159)
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109)
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:430)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:357)
	... 11 more
```

**Comment by chingor13** [comment]
I followed the same steps and got it to work with a few modifications:

1. I had to rename the `list-files.groovy` file to be `listFiles.groovy` (and fix references to the file name)
2. Added `@Grab(group = 'info.picocli', module = 'picocli', version = '3.9.6')` to the `@Grapes` config
3. Changed the `metadata.namespace` in the job config yaml to the `[K8S_NAMESPACE]` value from the tutorial
4. Changed the `spec.template.spec.serviceAccountName` to the `[KSA_NAME]` value from the tutorial

Another things to check - was this a new cluster that is using GKE 1.12 or higher? When the credentials were not yet set up, I was getting 401 unauthorized exceptions, not 500s

**Comment by neuromantik33** [comment]
Second attempt following your recommendations no success. I've made the modifications you suggested and I will show you my output.

`listFiles.groovy` (corrected version)
```groovy
#!/usr/bin/env groovy
@Grapes([
  @Grab(group = 'com.google.cloud', module = 'google-cloud-storage', version = '1.82.0'),
  @Grab(group = 'info.picocli', module = 'picocli', version = '3.9.6')
])

import com.google.api.gax.paging.Page
import com.google.cloud.storage.Blob
import com.google.cloud.storage.Storage
import com.google.cloud.storage.Storage.BlobListOption
import groovy.transform.Field
import picocli.CommandLine
import picocli.groovy.PicocliScript

import static com.google.cloud.storage.Storage.BlobListOption.currentDirectory
import static com.google.cloud.storage.StorageOptions.getDefaultInstance

@PicocliScript
@CommandLine.Command(
  name = 'listFiles',
  mixinStandardHelpOptions = true)

@Field Storage storage = defaultInstance.service

@CommandLine.Parameters(paramLabel = 'PATH')
@Field String basePath = null

listFiles(basePath)
  .each { println it }

def listFiles(String path) {

    def extractNames = { Page<Blob> p -> p.iterateAll().toList()*.name }
    def (bucket, prefix) = parsePath(path)

    def page
    if (prefix) {
        page = storage.list(bucket, currentDirectory(), BlobListOption.prefix(prefix))
    } else {
        page = storage.list(bucket, currentDirectory())
    }

    page
      .collect(extractNames)
      .flatten()
      .collect { "gs://$bucket/$it" as String }
}

static parsePath(String path) {
    def m = path =~ /gs:\/\/([a-z_\-]+)(\/.*)?/
    def bucket = m[0][1] as String
    def prefix = m[0][2] as String
    prefix = prefix == '/' ? null : prefix[1..-1]
    if (!prefix) {
        return [bucket, null]
    }
    if (prefix[-1] != '/') {
        prefix = "$prefix/"
    }
    [bucket, prefix]
}
```
`Dockerfile`
```Dockerfile
FROM groovy
MAINTAINER Nicolas Estrada "nicolas.estrada@oscaro.com"
ENV JAVA_OPTS -Dgroovy.grape.report.downloads=true
COPY listFiles.groovy ./listFiles
ENTRYPOINT ["./listFiles"]
```
`list-files.yaml` (Job manifest)
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: list-files
  namespace: curiosity
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - gs://oscaro-ecommerce-projects
        image: eu.gcr.io/oscaro-cloud/oscaro/list-files:latest
        imagePullPolicy: Always
        name: list-files
        ports:
        - containerPort: 5005
          name: debug
          protocol: TCP
      restartPolicy: Never
      serviceAccountName: default
```
And some diagnostic output to show that everything is set up accordingly
```bash
$ k get ds -n kube-system gke-metadata-server 
NAME                  DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                 AGE
gke-metadata-server   7         7         7       7            7           iam.gke.io/gke-metadata-server-enabled=true   5d20h

$ k get node
NAME                              STATUS   ROLES    AGE     VERSION
gke-<redacted>-22746c9b-kcnx      Ready    <none>   17h     v1.13.7-gke.8
gke-<redacted>-dbabefb7-3k1l      Ready    <none>   8h      v1.13.7-gke.8

$ k get serviceaccounts default -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: curiosity@oscaro-ecommerce.iam.gserviceaccount.com
  creationTimestamp: "2019-07-11T17:29:25Z"
  name: default
  namespace: curiosity
  resourceVersion: "51167"
  selfLink: /api/v1/namespaces/curiosity/serviceaccounts/default
  uid: 6e05cdfb-a401-11e9-a827-4201c0a80004
secrets:
- name: default-token-5vh8p

$ gcloud --project oscaro-ecommerce iam service-accounts describe curiosity@oscaro-ecommerce.iam.gserviceaccount.com
displayName: curiosity
email: curiosity@oscaro-ecommerce.iam.gserviceaccount.com
etag: MDEwMjE5MjA=
name: projects/oscaro-ecommerce/serviceAccounts/curiosity@oscaro-ecommerce.iam.gserviceaccount.com
oauth2ClientId: '<redacted>'
projectId: oscaro-ecommerce
uniqueId: '<redacted>'

$ gcloud iam service-accounts add-iam-policy-binding --project oscaro-ecommerce --role roles/iam.workloadIdentityUser --member serviceAccount:oscaro-ecommerce.svc.id.goog[curiosity/default] curiosity@oscaro-ecommerce.iam.gserviceaccount.com
Updated IAM policy for serviceAccount [curiosity@oscaro-ecommerce.iam.gserviceaccount.com].
bindings:
- members:
  - serviceAccount:oscaro-ecommerce.svc.id.goog[curiosity/default]
  role: roles/iam.workloadIdentityUser
etag: BwWN3wLnq5M=
version: 1
```
And the exception remains the same
```bash
$ k apply -f list-files.yaml 
job.batch/list-files created
$ k logs list-files-grftp 
Resolving dependency: info.picocli#picocli;3.9.6 {default=[default]}
Resolving dependency: com.google.cloud#google-cloud-storage;1.82.0 {default=[default]}
Preparing to download artifact info.picocli#picocli;3.9.6!picocli.jar
Preparing to download artifact com.google.cloud#google-cloud-storage;1.82.0!google-cloud-storage.jar
Preparing to download artifact com.google.cloud#google-cloud-core;1.82.0!google-cloud-core.jar
Preparing to download artifact com.google.cloud#google-cloud-core-http;1.82.0!google-cloud-core-http.jar
Preparing to download artifact com.google.apis#google-api-services-storage;v1-rev20190624-1.30.1!google-api-services-storage.jar
Preparing to download artifact com.google.guava#guava;28.0-android!guava.jar(bundle)
Preparing to download artifact com.google.http-client#google-http-client;1.30.1!google-http-client.jar
Preparing to download artifact com.google.code.findbugs#jsr305;3.0.2!jsr305.jar
Preparing to download artifact com.google.api#api-common;1.8.1!api-common.jar
Preparing to download artifact com.google.api#gax;1.47.1!gax.jar
Preparing to download artifact com.google.protobuf#protobuf-java-util;3.7.1!protobuf-java-util.jar(bundle)
Preparing to download artifact com.google.api.grpc#proto-google-common-protos;1.16.0!proto-google-common-protos.jar
Preparing to download artifact com.google.api.grpc#proto-google-iam-v1;0.12.0!proto-google-iam-v1.jar
Preparing to download artifact com.google.guava#failureaccess;1.0.1!failureaccess.jar(bundle)
Preparing to download artifact com.google.guava#listenablefuture;9999.0-empty-to-avoid-conflict-with-guava!listenablefuture.jar
Preparing to download artifact org.checkerframework#checker-compat-qual;2.5.5!checker-compat-qual.jar
Preparing to download artifact com.google.errorprone#error_prone_annotations;2.3.3!error_prone_annotations.jar
Preparing to download artifact com.google.j2objc#j2objc-annotations;1.3!j2objc-annotations.jar
Preparing to download artifact org.codehaus.mojo#animal-sniffer-annotations;1.18!animal-sniffer-annotations.jar
Preparing to download artifact org.apache.httpcomponents#httpclient;4.5.8!httpclient.jar
Preparing to download artifact io.opencensus#opencensus-api;0.21.0!opencensus-api.jar
Preparing to download artifact io.opencensus#opencensus-contrib-http-util;0.21.0!opencensus-contrib-http-util.jar
Preparing to download artifact org.apache.httpcomponents#httpcore;4.4.11!httpcore.jar
Preparing to download artifact commons-logging#commons-logging;1.2!commons-logging.jar
Preparing to download artifact commons-codec#commons-codec;1.11!commons-codec.jar
Preparing to download artifact io.grpc#grpc-context;1.21.0!grpc-context.jar
Preparing to download artifact javax.annotation#javax.annotation-api;1.3.2!javax.annotation-api.jar
Preparing to download artifact org.threeten#threetenbp;1.3.3!threetenbp.jar
Preparing to download artifact com.google.auth#google-auth-library-oauth2-http;0.16.2!google-auth-library-oauth2-http.jar
Preparing to download artifact com.google.auth#google-auth-library-credentials;0.16.2!google-auth-library-credentials.jar
Preparing to download artifact com.google.http-client#google-http-client-jackson2;1.30.1!google-http-client-jackson2.jar
Preparing to download artifact com.fasterxml.jackson.core#jackson-core;2.9.9!jackson-core.jar(bundle)
Preparing to download artifact com.google.protobuf#protobuf-java;3.7.1!protobuf-java.jar(bundle)
Preparing to download artifact com.google.code.gson#gson;2.8.5!gson.jar
Preparing to download artifact com.google.api-client#google-api-client;1.30.2!google-api-client.jar
Preparing to download artifact com.google.http-client#google-http-client-appengine;1.30.1!google-http-client-appengine.jar
Preparing to download artifact com.google.api#gax-httpjson;0.64.1!gax-httpjson.jar
Preparing to download artifact com.google.oauth-client#google-oauth-client;1.30.1!google-oauth-client.jar
Downloaded 10347 Kbytes in 4545ms:
  [SUCCESSFUL ] info.picocli#picocli;3.9.6!picocli.jar (896ms)
  [SUCCESSFUL ] com.google.cloud#google-cloud-storage;1.82.0!google-cloud-storage.jar (221ms)
  [SUCCESSFUL ] com.google.cloud#google-cloud-core;1.82.0!google-cloud-core.jar (96ms)
  [SUCCESSFUL ] com.google.guava#guava;28.0-android!guava.jar(bundle) (202ms)
  [SUCCESSFUL ] com.google.guava#failureaccess;1.0.1!failureaccess.jar(bundle) (57ms)
  [SUCCESSFUL ] com.google.guava#listenablefuture;9999.0-empty-to-avoid-conflict-with-guava!listenablefuture.jar (58ms)
  [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.2!jsr305.jar (81ms)
  [SUCCESSFUL ] org.checkerframework#checker-compat-qual;2.5.5!checker-compat-qual.jar (61ms)
  [SUCCESSFUL ] com.google.errorprone#error_prone_annotations;2.3.3!error_prone_annotations.jar (61ms)
  [SUCCESSFUL ] com.google.j2objc#j2objc-annotations;1.3!j2objc-annotations.jar (60ms)
  [SUCCESSFUL ] org.codehaus.mojo#animal-sniffer-annotations;1.18!animal-sniffer-annotations.jar (60ms)
  [SUCCESSFUL ] com.google.http-client#google-http-client;1.30.1!google-http-client.jar (133ms)
  [SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.5.8!httpclient.jar (129ms)
  [SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.4.11!httpcore.jar (119ms)
  [SUCCESSFUL ] commons-logging#commons-logging;1.2!commons-logging.jar (73ms)
  [SUCCESSFUL ] commons-codec#commons-codec;1.11!commons-codec.jar (122ms)
  [SUCCESSFUL ] io.opencensus#opencensus-api;0.21.0!opencensus-api.jar (121ms)
  [SUCCESSFUL ] io.grpc#grpc-context;1.21.0!grpc-context.jar (72ms)
  [SUCCESSFUL ] io.opencensus#opencensus-contrib-http-util;0.21.0!opencensus-contrib-http-util.jar (70ms)
  [SUCCESSFUL ] com.google.api#api-common;1.8.1!api-common.jar (98ms)
  [SUCCESSFUL ] javax.annotation#javax.annotation-api;1.3.2!javax.annotation-api.jar (53ms)
  [SUCCESSFUL ] com.google.api#gax;1.47.1!gax.jar (127ms)
  [SUCCESSFUL ] org.threeten#threetenbp;1.3.3!threetenbp.jar (119ms)
  [SUCCESSFUL ] com.google.auth#google-auth-library-oauth2-http;0.16.2!google-auth-library-oauth2-http.jar (83ms)
  [SUCCESSFUL ] com.google.auth#google-auth-library-credentials;0.16.2!google-auth-library-credentials.jar (59ms)
  [SUCCESSFUL ] com.google.http-client#google-http-client-jackson2;1.30.1!google-http-client-jackson2.jar (59ms)
  [SUCCESSFUL ] com.fasterxml.jackson.core#jackson-core;2.9.9!jackson-core.jar(bundle) (96ms)
  [SUCCESSFUL ] com.google.protobuf#protobuf-java-util;3.7.1!protobuf-java-util.jar(bundle) (84ms)
  [SUCCESSFUL ] com.google.protobuf#protobuf-java;3.7.1!protobuf-java.jar(bundle) (155ms)
  [SUCCESSFUL ] com.google.code.gson#gson;2.8.5!gson.jar (131ms)
  [SUCCESSFUL ] com.google.api.grpc#proto-google-common-protos;1.16.0!proto-google-common-protos.jar (169ms)
  [SUCCESSFUL ] com.google.api.grpc#proto-google-iam-v1;0.12.0!proto-google-iam-v1.jar (93ms)
  [SUCCESSFUL ] com.google.cloud#google-cloud-core-http;1.82.0!google-cloud-core-http.jar (61ms)
  [SUCCESSFUL ] com.google.api-client#google-api-client;1.30.2!google-api-client.jar (127ms)
  [SUCCESSFUL ] com.google.oauth-client#google-oauth-client;1.30.1!google-oauth-client.jar (67ms)
  [SUCCESSFUL ] com.google.http-client#google-http-client-appengine;1.30.1!google-http-client-appengine.jar (75ms)
  [SUCCESSFUL ] com.google.api#gax-httpjson;0.64.1!gax-httpjson.jar (77ms)
  [SUCCESSFUL ] com.google.apis#google-api-services-storage;v1-rev20190624-1.30.1!google-api-services-storage.jar (76ms)
Caught: picocli.CommandLine$ExecutionException: com.google.cloud.storage.StorageException: Unexpected Error code 500 trying to get security access token from Compute Engine metadata for the default service account: GKE Metadata Server: Internal Server Error

picocli.CommandLine$ExecutionException: com.google.cloud.storage.StorageException: Unexpected Error code 500 trying to get security access token from Compute Engine metadata for the default service account: GKE Metadata Server: Internal Server Error

	at picocli.groovy.PicocliBaseScript.handleExecutionException(PicocliBaseScript.java:262)
	at picocli.groovy.PicocliBaseScript.run(PicocliBaseScript.java:124)
Caused by: com.google.cloud.storage.StorageException: Unexpected Error code 500 trying to get security access token from Compute Engine metadata for the default service account: GKE Metadata Server: Internal Server Error

	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:226)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:367)
	at com.google.cloud.storage.StorageImpl$8.call(StorageImpl.java:355)
	at com.google.cloud.storage.StorageImpl$8.call(StorageImpl.java:352)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:351)
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:307)
	at listFiles.listFiles(listFiles:40)
	at listFiles$listFiles.callCurrent(Unknown Source)
	at listFiles.runScriptBody(listFiles:28)
	at picocli.groovy.PicocliBaseScript.run(PicocliBaseScript.java:122)
Caused by: java.io.IOException: Unexpected Error code 500 trying to get security access token from Compute Engine metadata for the default service account: GKE Metadata Server: Internal Server Error

	at com.google.auth.oauth2.ComputeEngineCredentials.refreshAccessToken(ComputeEngineCredentials.java:139)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:165)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:151)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159)
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109)
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:430)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:357)
	... 11 more
```
I'm really out of ideas as to why it's not working, but a 500 error code without any more info is quite puzzling.

**Comment by neuromantik33** [comment]
Ok by looking at the gke-metadata-server daemonset logs I was able to figure it out :)
It turns out that in order to use workload-identity you need to :

- Enable IAM Service Account Credentials API
- Add an additional IAM policy binding, ie. `gcloud --project [PROJECT_NAME] iam service-accounts add-iam-policy-binding --role roles/iam.serviceAccountTokenCreator --member serviceAccount:[PROJECT_NAME].svc.id.goog[[K8S_NAMESPACE]/[KSA_NAME]] [GSA_NAME]`

I don't recall either steps being prerequisites in the documentation. Anyhow sorry to take your time :)

**Comment by chingor13** [comment]
Thanks for following up. That command is what links the K8S Service Account with the underlying Google Service Account to use. In any case it's odd that you get a 500 error rather than a 401 error with a better error message.

We'd appreciate any feedback on the backend service on the [GKE issue tracker](https://issuetracker.google.com/issues/new?component=187077&template=0)
