### ISSUE TITLE
Spanner JDBC: Fix flaky test

### ISSUE THREAD

**Issue by kolea2** [googleapis/google-cloud-java#6075]
On java 11 build:

`[ERROR]   SingleUseTransactionTest.testExecuteUpdateWithTimeout:726 » IllegalArgument`

**Comment by kolea2** [comment]
Also:

```
[ERROR] testTimeoutExceptionReadWriteTransactionalSlowRollback(com.google.cloud.spanner.jdbc.StatementTimeoutTest)  Time elapsed: 0.13 s  <<< ERROR!
com.google.cloud.spanner.SpannerException: DEADLINE_EXCEEDED: Statement execution timeout occurred for SELECT fast_column FROM fast_table
	at com.google.cloud.spanner.jdbc.StatementTimeoutTest.testTimeoutExceptionReadWriteTransactionalSlowRollback(StatementTimeoutTest.java:565)
Caused by: java.util.concurrent.TimeoutException
	at com.google.cloud.spanner.jdbc.StatementTimeoutTest.testTimeoutExceptionReadWriteTransactionalSlowRollback(StatementTimeoutTest.java:565)
```

**Comment by olavloite** [comment]
```
[ERROR] Tests run: 20, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.05 s <<< FAILURE! - in com.google.cloud.spanner.jdbc.SingleUseTransactionTest
[ERROR] testExecuteUpdateWithTimeout(com.google.cloud.spanner.jdbc.SingleUseTransactionTest)  Time elapsed: 0.014 s  <<< ERROR!
java.lang.IllegalArgumentException
	at com.google.cloud.spanner.jdbc.SingleUseTransactionTest.testExecuteUpdateWithTimeout(SingleUseTransactionTest.java:726)
```

**Comment by olavloite** [comment]
Also:

```
[ERROR] Tests run: 20, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.122 s <<< FAILURE! - in com.google.cloud.spanner.jdbc.SingleUseTransactionTest
[ERROR] testExecuteUpdateWithTimeout(com.google.cloud.spanner.jdbc.SingleUseTransactionTest)  Time elapsed: 0.016 s  <<< ERROR!
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at com.google.cloud.spanner.jdbc.SingleUseTransaction.fireAndForgetRollbackAndCloseTxManager(SingleUseTransaction.java:474)
	at com.google.cloud.spanner.jdbc.SingleUseTransaction.executeAsyncTransactionalUpdate(SingleUseTransaction.java:450)
	at com.google.cloud.spanner.jdbc.SingleUseTransaction.executeUpdate(SingleUseTransaction.java:290)
	at com.google.cloud.spanner.jdbc.SingleUseTransactionTest.testExecuteUpdateWithTimeout(SingleUseTransactionTest.java:726)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by olavloite** [comment]
Not directly JDBC related, but still a flaky Spanner test failure (on Java 11):

```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.436 s <<< FAILURE! - in com.google.cloud.spanner.DatabaseClientImplTest
[ERROR] testPartitionedDmlWithTimeout(com.google.cloud.spanner.DatabaseClientImplTest)  Time elapsed: 0.155 s  <<< FAILURE!
java.lang.AssertionError: expected DEADLINE_EXCEEDED
	at com.google.cloud.spanner.DatabaseClientImplTest.testPartitionedDmlWithTimeout(DatabaseClientImplTest.java:240)
```
