### ISSUE TITLE
Read time error when uploading large files

### ISSUE THREAD

**Issue by Adam-Oudaimah-SCASE** [googleapis/google-cloud-java#6171]
Hello,
I'm trying to upload large files.
I've tried to use "WriterChannel" (because as mentioned in the documentation, it's better to use it with large files), but when I used it, I always got this error:
com.google.cloud.storage.StorageException: Read timed out
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:226)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:773)
	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:53)
	at com.google.cloud.BaseWriteChannel.flush(BaseWriteChannel.java:112)
	at com.google.cloud.BaseWriteChannel.write(BaseWriteChannel.java:139)
	at de.intenta.storage.cloud.google.GoogleStorageWriter.writeObject(GoogleStorageWriter.java:139)
	at de.intenta.storage.cloud.google.GoogleStorageWriterTest.testWriteObjectBigFiles(GoogleStorageWriterTest.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:36)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:144)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:79)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:995)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:750)
	... 75 more

**Comment by Adam-Oudaimah-SCASE** [comment]
Execution environment:
I'm building a Java (using Java 8) application that warps google storage API.
OS: Windows 10, client version: google-cloud-storage(1.86.0).

I used the approach that mentioned in the following example:
https://github.com/googleapis/google-cloud-java/blob/2c9e603d3c22d22197445da6b5cd6c776087e252/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/StorageExample.java#L301

**Comment by pmakani** [comment]
@Adam-Oudaimah-SCASE I tried more than 5GB files many times but not able reproduce read timeout error.

**Comment by codyoss** [comment]
@Adam-Oudaimah-SCASE if you have not already can you try to change the chunk size?

```java
int CHUNK_SIZE = 50 * 1000 * 1000;
Storage storage = StorageOptions.getDefaultInstance().getService();
WriteChannel writer = storage.writer(blobInfo);
writer.setChunkSize(CHUNK_SIZE);
```
