### ISSUE TITLE
Firestore: issue with grpc native library

### ISSUE THREAD

**Issue by emanuelemaffeo** [googleapis/google-cloud-java#6200]
When I start the application I get java.lang.UnsatisfiedLinkError no io_grpc_netty_shaded_netty_tcnative_osx_x86_64 in java.library.path, I've tried to force older versions of netty-tcnative, upgrade jdk version, checked if that library is in my classpath with different versions, but nothing, still get this error. What could it be?

```2019-08-30 12:04:19.336	DEBUG	BAY	io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader	Unable to load the library 'io_grpc_netty_shaded_netty_tcnative_osx_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_osx_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_221]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_221]
	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_221]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_221]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:526) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:93) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:436) ~[grpc-netty-shaded-1.21.0.jar:1.21.0]
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:444) ~[grpc-core-1.19.0.jar:1.19.0]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:223) ~[gax-grpc-1.44.0.jar:1.44.0]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:164) ~[gax-grpc-1.44.0.jar:1.44.0]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:156) ~[gax-grpc-1.44.0.jar:1.44.0]
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:157) ~[gax-1.44.0.jar:1.44.0]
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122) ~[gax-1.44.0.jar:1.44.0]
	at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:122) ~[google-cloud-firestore-1.0.0.jar:1.0.0]
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:80) ~[google-cloud-firestore-1.0.0.jar:1.0.0]
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:72) ~[google-cloud-firestore-1.0.0.jar:1.0.0]
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:510) ~[google-cloud-core-1.70.0.jar:1.70.0]
	at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:315) ~[google-cloud-firestore-1.0.0.jar:1.0.0]
	at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:76) ~[google-cloud-firestore-1.0.0.jar:1.0.0]
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:63) ~[google-cloud-firestore-1.0.0.jar:1.0.0]
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:56) ~[google-cloud-firestore-1.0.0.jar:1.0.0]
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:498) ~[google-cloud-core-1.70.0.jar:1.70.0]```

**Comment by pmakani** [comment]
@emanuelemaffeo can you share list of dependencies and sample code which you have used ?

**Comment by emanuelemaffeo** [comment]
> @emanuelemaffeo can you share list of dependencies and sample code which you have used ?

This is my dependecy tree

```+--- org.springframework.boot:spring-boot-starter-security:2.1.4.RELEASE
|    +--- org.springframework.boot:spring-boot-starter:2.1.4.RELEASE
|    |    +--- org.springframework.boot:spring-boot:2.1.4.RELEASE
|    |    |    +--- org.springframework:spring-core:5.1.6.RELEASE
|    |    |    |    \--- org.springframework:spring-jcl:5.1.6.RELEASE
|    |    |    \--- org.springframework:spring-context:5.1.6.RELEASE
|    |    |         +--- org.springframework:spring-aop:5.1.6.RELEASE
|    |    |         |    +--- org.springframework:spring-beans:5.1.6.RELEASE
|    |    |         |    |    \--- org.springframework:spring-core:5.1.6.RELEASE (*)
|    |    |         |    \--- org.springframework:spring-core:5.1.6.RELEASE (*)
|    |    |         +--- org.springframework:spring-beans:5.1.6.RELEASE (*)
|    |    |         +--- org.springframework:spring-core:5.1.6.RELEASE (*)
|    |    |         \--- org.springframework:spring-expression:5.1.6.RELEASE
|    |    |              \--- org.springframework:spring-core:5.1.6.RELEASE (*)
|    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.1.4.RELEASE
|    |    |    \--- org.springframework.boot:spring-boot:2.1.4.RELEASE (*)
|    |    +--- javax.annotation:javax.annotation-api:1.3.2
|    |    \--- org.springframework:spring-core:5.1.6.RELEASE (*)
|    +--- org.springframework:spring-aop:5.1.6.RELEASE (*)
|    +--- org.springframework.security:spring-security-config:5.1.5.RELEASE
|    |    +--- org.springframework.security:spring-security-core:5.1.5.RELEASE
|    |    |    +--- org.springframework:spring-aop:5.1.6.RELEASE (*)
|    |    |    +--- org.springframework:spring-beans:5.1.6.RELEASE (*)
|    |    |    +--- org.springframework:spring-context:5.1.6.RELEASE (*)
|    |    |    +--- org.springframework:spring-core:5.1.6.RELEASE (*)
|    |    |    \--- org.springframework:spring-expression:5.1.6.RELEASE (*)
|    |    +--- org.springframework:spring-aop:5.1.6.RELEASE (*)
|    |    +--- org.springframework:spring-beans:5.1.6.RELEASE (*)
|    |    +--- org.springframework:spring-context:5.1.6.RELEASE (*)
|    |    \--- org.springframework:spring-core:5.1.6.RELEASE (*)
|    \--- org.springframework.security:spring-security-web:5.1.5.RELEASE
|         +--- org.springframework.security:spring-security-core:5.1.5.RELEASE (*)
|         +--- org.springframework:spring-aop:5.1.6.RELEASE (*)
|         +--- org.springframework:spring-beans:5.1.6.RELEASE (*)
|         +--- org.springframework:spring-context:5.1.6.RELEASE (*)
|         +--- org.springframework:spring-core:5.1.6.RELEASE (*)
|         +--- org.springframework:spring-expression:5.1.6.RELEASE (*)
|         \--- org.springframework:spring-web:5.1.6.RELEASE
|              +--- org.springframework:spring-beans:5.1.6.RELEASE (*)
|              \--- org.springframework:spring-core:5.1.6.RELEASE (*)
+--- org.springframework.boot:spring-boot-starter-web:2.1.4.RELEASE
|    +--- org.springframework.boot:spring-boot-starter:2.1.4.RELEASE (*)
|    +--- org.springframework.boot:spring-boot-starter-json:2.1.4.RELEASE
|    |    +--- org.springframework.boot:spring-boot-starter:2.1.4.RELEASE (*)
|    |    +--- org.springframework:spring-web:5.1.6.RELEASE (*)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.9.8
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
|    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.8 -> 2.9.9
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.9.8
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.9.8 -> 2.9.9
|    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.9.8 (*)
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.8
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.9.8 -> 2.9.9
|    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.9.8 (*)
|    |    \--- com.fasterxml.jackson.module:jackson-module-parameter-names:2.9.8
|    |         +--- com.fasterxml.jackson.core:jackson-core:2.9.8 -> 2.9.9
|    |         \--- com.fasterxml.jackson.core:jackson-databind:2.9.8 (*)
|    +--- org.springframework.boot:spring-boot-starter-tomcat:2.1.4.RELEASE
|    |    +--- javax.annotation:javax.annotation-api:1.3.2
|    |    +--- org.apache.tomcat.embed:tomcat-embed-core:9.0.17
|    |    |    \--- org.apache.tomcat:tomcat-annotations-api:9.0.17
|    |    +--- org.apache.tomcat.embed:tomcat-embed-el:9.0.17
|    |    \--- org.apache.tomcat.embed:tomcat-embed-websocket:9.0.17
|    |         \--- org.apache.tomcat.embed:tomcat-embed-core:9.0.17 (*)
|    +--- org.hibernate.validator:hibernate-validator:6.0.16.Final
|    |    +--- javax.validation:validation-api:2.0.1.Final
|    |    +--- org.jboss.logging:jboss-logging:3.3.2.Final
|    |    \--- com.fasterxml:classmate:1.3.4
|    +--- org.springframework:spring-web:5.1.6.RELEASE (*)
|    \--- org.springframework:spring-webmvc:5.1.6.RELEASE
|         +--- org.springframework:spring-aop:5.1.6.RELEASE (*)
|         +--- org.springframework:spring-beans:5.1.6.RELEASE (*)
|         +--- org.springframework:spring-context:5.1.6.RELEASE (*)
|         +--- org.springframework:spring-core:5.1.6.RELEASE (*)
|         +--- org.springframework:spring-expression:5.1.6.RELEASE (*)
|         \--- org.springframework:spring-web:5.1.6.RELEASE (*)
+--- org.springframework.boot:spring-boot-starter-log4j2:2.1.4.RELEASE
|    +--- org.apache.logging.log4j:log4j-slf4j-impl:2.11.2
|    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.26
|    |    \--- org.apache.logging.log4j:log4j-api:2.11.2
|    +--- org.apache.logging.log4j:log4j-core:2.11.2
|    |    \--- org.apache.logging.log4j:log4j-api:2.11.2
|    +--- org.apache.logging.log4j:log4j-jul:2.11.2
|    |    \--- org.apache.logging.log4j:log4j-api:2.11.2
|    \--- org.slf4j:jul-to-slf4j:1.7.26
|         \--- org.slf4j:slf4j-api:1.7.26
+--- com.fasterxml.jackson.module:jackson-module-kotlin:2.9.7
|    +--- com.fasterxml.jackson.core:jackson-databind:2.9.7 -> 2.9.8 (*)
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
|    \--- org.jetbrains.kotlin:kotlin-reflect:1.2.51 -> 1.2.71
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.71
|              +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.2.71
|              \--- org.jetbrains:annotations:13.0
+--- org.jetbrains.kotlin:kotlin-reflect:1.2.71 (*)
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.71 (*)
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.71 (*)
+--- io.jsonwebtoken:jjwt:0.9.1
|    \--- com.fasterxml.jackson.core:jackson-databind:2.9.6 -> 2.9.8 (*)
+--- org.apache.commons:commons-lang3:3.9
\--- com.google.cloud:google-cloud-firestore:1.19.0
     +--- com.google.cloud:google-cloud-core-grpc:1.89.0
     |    +--- com.google.auth:google-auth-library-credentials:0.17.1
     |    +--- com.google.cloud:google-cloud-core:1.89.0
     |    |    +--- com.google.api:gax:1.48.0
     |    |    |    +--- com.google.guava:guava:28.0-android
     |    |    |    |    +--- com.google.guava:failureaccess:1.0.1
     |    |    |    |    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
     |    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
     |    |    |    |    +--- org.checkerframework:checker-compat-qual:2.5.5
     |    |    |    |    +--- com.google.errorprone:error_prone_annotations:2.3.2
     |    |    |    |    +--- com.google.j2objc:j2objc-annotations:1.3
     |    |    |    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.17
     |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
     |    |    |    +--- org.threeten:threetenbp:1.3.3
     |    |    |    +--- com.google.auth:google-auth-library-oauth2-http:0.17.0
     |    |    |    |    +--- com.google.auto.value:auto-value-annotations:1.6.5
     |    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
     |    |    |    |    +--- com.google.auth:google-auth-library-credentials:0.17.0 -> 0.17.1
     |    |    |    |    +--- com.google.http-client:google-http-client:1.31.0
     |    |    |    |    |    +--- org.apache.httpcomponents:httpclient:4.5.9
     |    |    |    |    |    |    +--- org.apache.httpcomponents:httpcore:4.4.11
     |    |    |    |    |    |    +--- commons-logging:commons-logging:1.2
     |    |    |    |    |    |    \--- commons-codec:commons-codec:1.11
     |    |    |    |    |    +--- org.apache.httpcomponents:httpcore:4.4.11
     |    |    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
     |    |    |    |    |    +--- com.google.guava:guava:26.0-android -> 28.0-android (*)
     |    |    |    |    |    +--- com.google.j2objc:j2objc-annotations:1.3
     |    |    |    |    |    +--- io.opencensus:opencensus-api:0.21.0 -> 0.23.0
     |    |    |    |    |    |    \--- io.grpc:grpc-context:1.19.0 -> 1.23.0
     |    |    |    |    |    \--- io.opencensus:opencensus-contrib-http-util:0.21.0
     |    |    |    |    |         +--- io.opencensus:opencensus-api:0.21.0 -> 0.23.0 (*)
     |    |    |    |    |         \--- com.google.guava:guava:26.0-android -> 28.0-android (*)
     |    |    |    |    +--- com.google.http-client:google-http-client-jackson2:1.31.0
     |    |    |    |    |    +--- com.google.http-client:google-http-client:1.31.0 (*)
     |    |    |    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.9
     |    |    |    |    \--- com.google.guava:guava:28.0-android (*)
     |    |    |    +--- com.google.api:api-common:1.8.1
     |    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
     |    |    |    |    +--- com.google.guava:guava:26.0-android -> 28.0-android (*)
     |    |    |    |    \--- javax.annotation:javax.annotation-api:1.3.2
     |    |    |    \--- io.opencensus:opencensus-api:0.23.0 (*)
     |    |    +--- com.google.protobuf:protobuf-java-util:3.9.1
     |    |    |    +--- com.google.protobuf:protobuf-java:3.9.1
     |    |    |    +--- com.google.guava:guava:26.0-android -> 28.0-android (*)
     |    |    |    +--- com.google.errorprone:error_prone_annotations:2.3.2
     |    |    |    \--- com.google.code.gson:gson:2.7
     |    |    +--- com.google.api.grpc:proto-google-common-protos:1.16.0
     |    |    |    \--- com.google.protobuf:protobuf-java:3.7.1 -> 3.9.1
     |    |    \--- com.google.api.grpc:proto-google-iam-v1:0.12.0
     |    |         +--- com.google.protobuf:protobuf-java:3.5.1 -> 3.9.1
     |    |         +--- com.google.api:api-common:1.5.0 -> 1.8.1 (*)
     |    |         \--- com.google.api.grpc:proto-google-common-protos:1.11.0 -> 1.16.0 (*)
     |    +--- com.google.guava:guava:28.0-android (*)
     |    \--- com.google.api:gax-grpc:1.48.0
     |         +--- com.google.api:gax:1.48.0 (*)
     |         +--- io.grpc:grpc-stub:1.23.0
     |         |    \--- io.grpc:grpc-api:1.23.0
     |         |         +--- io.grpc:grpc-context:1.23.0
     |         |         +--- com.google.errorprone:error_prone_annotations:2.3.2
     |         |         +--- com.google.code.findbugs:jsr305:3.0.2
     |         |         +--- org.codehaus.mojo:animal-sniffer-annotations:1.17
     |         |         \--- com.google.guava:guava:26.0-android -> 28.0-android (*)
     |         +--- io.grpc:grpc-auth:1.23.0
     |         |    +--- io.grpc:grpc-api:[1.23.0] -> 1.23.0 (*)
     |         |    \--- com.google.auth:google-auth-library-credentials:0.13.0 -> 0.17.1
     |         +--- io.grpc:grpc-protobuf:1.23.0
     |         |    +--- io.grpc:grpc-api:1.23.0 (*)
     |         |    +--- com.google.protobuf:protobuf-java:3.9.0 -> 3.9.1
     |         |    +--- com.google.guava:guava:26.0-android -> 28.0-android (*)
     |         |    +--- com.google.api.grpc:proto-google-common-protos:1.12.0 -> 1.16.0 (*)
     |         |    \--- io.grpc:grpc-protobuf-lite:1.23.0
     |         |         +--- io.grpc:grpc-api:1.23.0 (*)
     |         |         \--- com.google.guava:guava:26.0-android -> 28.0-android (*)
     |         +--- com.google.guava:guava:28.0-android (*)
     |         +--- com.google.code.findbugs:jsr305:3.0.2
     |         +--- org.threeten:threetenbp:1.3.3
     |         +--- com.google.auth:google-auth-library-oauth2-http:0.17.0 (*)
     |         +--- com.google.auth:google-auth-library-credentials:0.17.0 -> 0.17.1
     |         +--- com.google.api.grpc:proto-google-common-protos:1.15.0 -> 1.16.0 (*)
     |         +--- com.google.api:api-common:1.8.1 (*)
     |         +--- io.grpc:grpc-netty-shaded:1.23.0
     |         |    \--- io.grpc:grpc-core:[1.23.0] -> 1.23.0
     |         |         +--- io.grpc:grpc-api:[1.23.0] -> 1.23.0 (*)
     |         |         +--- com.google.code.gson:gson:2.7
     |         |         +--- com.google.android:annotations:4.1.1.4
     |         |         +--- io.perfmark:perfmark-api:0.17.0
     |         |         |    +--- com.google.code.findbugs:jsr305:3.0.2
     |         |         |    \--- com.google.errorprone:error_prone_annotations:[2.3.2,2.3.3] -> 2.3.2
     |         |         +--- io.opencensus:opencensus-api:0.21.0 -> 0.23.0 (*)
     |         |         \--- io.opencensus:opencensus-contrib-grpc-metrics:0.21.0
     |         |              \--- io.opencensus:opencensus-api:0.21.0 -> 0.23.0 (*)
     |         \--- io.grpc:grpc-alts:1.23.0
     |              +--- io.grpc:grpc-grpclb:1.23.0
     |              |    +--- io.grpc:grpc-core:[1.23.0] -> 1.23.0 (*)
     |              |    +--- io.grpc:grpc-protobuf:1.23.0 (*)
     |              |    +--- io.grpc:grpc-stub:1.23.0 (*)
     |              |    +--- com.google.protobuf:protobuf-java:3.9.0 -> 3.9.1
     |              |    \--- com.google.protobuf:protobuf-java-util:3.9.0 -> 3.9.1 (*)
     |              +--- io.grpc:grpc-auth:1.23.0 (*)
     |              +--- io.grpc:grpc-core:[1.23.0] -> 1.23.0 (*)
     |              +--- io.grpc:grpc-netty-shaded:[1.23.0] -> 1.23.0 (*)
     |              +--- io.grpc:grpc-protobuf:1.23.0 (*)
     |              +--- io.grpc:grpc-stub:1.23.0 (*)
     |              +--- org.apache.commons:commons-lang3:3.5 -> 3.9
     |              +--- com.google.protobuf:protobuf-java:3.9.0 -> 3.9.1
     |              \--- com.google.auth:google-auth-library-oauth2-http:0.13.0 -> 0.17.0 (*)
     +--- com.google.api.grpc:proto-google-cloud-firestore-admin-v1:1.19.0
     |    +--- com.google.protobuf:protobuf-java:3.9.1
     |    +--- com.google.api:api-common:1.8.1 (*)
     |    +--- com.google.api.grpc:proto-google-common-protos:1.16.0 (*)
     |    \--- javax.annotation:javax.annotation-api:1.3.2
     +--- com.google.api.grpc:proto-google-cloud-firestore-v1:1.19.0
     |    +--- com.google.protobuf:protobuf-java:3.9.1
     |    +--- com.google.api:api-common:1.8.1 (*)
     |    +--- com.google.api.grpc:proto-google-common-protos:1.16.0 (*)
     |    \--- javax.annotation:javax.annotation-api:1.3.2
     +--- com.google.api.grpc:proto-google-cloud-firestore-v1beta1:0.72.0
     |    +--- com.google.protobuf:protobuf-java:3.9.1
     |    +--- com.google.api:api-common:1.8.1 (*)
     |    +--- com.google.api.grpc:proto-google-common-protos:1.16.0 (*)
     |    \--- javax.annotation:javax.annotation-api:1.3.2
     \--- io.opencensus:opencensus-contrib-grpc-util:0.23.0
          +--- io.opencensus:opencensus-api:0.23.0 (*)
          \--- io.grpc:grpc-core:1.19.0 -> 1.23.0 (*)
```

Sample code: 

```
val serviceAccount = FileInputStream("gcs-credentials.json")
            val credentials = GoogleCredentials.fromStream(serviceAccount)
            val options = FirestoreOptions.getDefaultInstance().toBuilder()
                    .setCredentials(credentials)
                    .build()
           val db = options.service
```

**Comment by pmakani** [comment]
@emanuelemaffeo I tested your sample code with same dependencies and getting exception but still able to create firestore client and retrieved data from database, is this happening for you ?

**Comment by emanuelemaffeo** [comment]
Ok, actually I've this other exception also:

```io.grpc.StatusRuntimeException: PERMISSION_DENIED: Missing or insufficient permissions.
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.23.0.jar:1.23.0]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490) ~[grpc-stub-1.23.0.jar:1.23.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.23.0.jar:1.23.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.23.0.jar:1.23.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.23.0.jar:1.23.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) ~[grpc-core-1.23.0.jar:1.23.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.23.0.jar:1.23.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.23.0.jar:1.23.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.23.0.jar:1.23.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) ~[grpc-core-1.23.0.jar:1.23.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510) ~[grpc-core-1.23.0.jar:1.23.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) ~[grpc-core-1.23.0.jar:1.23.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630) ~[grpc-core-1.23.0.jar:1.23.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518) ~[grpc-core-1.23.0.jar:1.23.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692) ~[grpc-core-1.23.0.jar:1.23.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681) ~[grpc-core-1.23.0.jar:1.23.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.23.0.jar:1.23.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.23.0.jar:1.23.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]```

I guess I've been fooled by the other exception cause it happens right before the db call.
So this is only a permission problem I think...It's strange because I give my service account all roles related to firestore.

**Comment by emanuelemaffeo** [comment]
Ok, It's not even a permission error, I've used the same json credentials in a test golang project and everything works fine. Seems something related to google-cloud-firestore library.

**Comment by pmakani** [comment]
Closing this issue due to inactivity. Feel free to reopen if you are facing problem .
