### ISSUE TITLE
Dialogflow V2 Java integration error in Android: UNAUTHENTICATED: Failed computing credential metadata

### ISSUE THREAD

**Issue by abhi007tyagi** [googleapis/google-cloud-java#6209]
I am trying to integrate the latest Google Cloud Java API for Dialogflow V2Beta1 0.106.0-alpha & 0.107.0-alpha with Android. My code works fine with version 0.88.0-alpha. But with the new version, it gives error and returns a NULL response.

#### Environment details

1. JAVA API: com.google.cloud:google-cloud-dialogflow:0.107.0-alpha 
2. OS type and version: Android minSdkVersion 19 targetSdkVersion 27
3. Java version: 7
4. google-cloud-java version(s): google-cloud-dialogflow:0.107.0-alpha

#### Steps to reproduce

  1. just change the version from 0.88.0 to 0.106.0 or 0.107.0

#### Code example

```@Override
        protected DetectIntentResponse doInBackground(Void... voids) {
            try {
                DetectIntentRequest detectIntentRequest =
                        DetectIntentRequest.newBuilder()
                                .setSession(session.toString())
                                .setQueryInput(queryInput)
                                .build();
                return sessionsClient.detectIntent(detectIntentRequest); // Executes with 0.88.0 version
            } catch (Exception e) {
                e.printStackTrace(); //Error Comes Here
            }
            return null;
        }
```

#### Stack trace
```
2019-09-03 11:46:04.384 1990-1990/com.google.android.inputmethod.latin I/LatinIme: onActivate() : EditorInfo = Package = com.chatapp.chatappbot : Type = Text : Learning = Disable : Suggestion = Show : AutoCorrection = Disable : Microphone = Show : Incognito = Disable
2019-09-03 11:46:04.474 1990-1990/com.google.android.inputmethod.latin W/Conv2QueryExtension: Conv2Query not enabled due to current app [com.chatapp.chatappbot] not in whitelist
2019-09-03 11:46:06.042 1990-1990/com.google.android.inputmethod.latin W/Conv2QueryExtension: Conv2Query not enabled due to current app [com.chatapp.chatappbot] not in whitelist
2019-09-03 11:46:06.050 1990-1990/com.google.android.inputmethod.latin W/Conv2QueryExtension: Conv2Query not enabled due to current app [com.chatapp.chatappbot] not in whitelist
2019-09-03 11:46:06.166 8594-8722/com.chatapp.chatappbot W/System.err: com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed computing credential metadata
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:73)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:982)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:957)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:748)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:515)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
2019-09-03 11:46:06.167 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
2019-09-03 11:46:06.168 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
2019-09-03 11:46:06.168 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
2019-09-03 11:46:06.168 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
2019-09-03 11:46:06.168 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
2019-09-03 11:46:06.168 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-09-03 11:46:06.169 8594-8722/com.chatapp.chatappbot W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err: 	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.cloud.dialogflow.v2beta1.SessionsClient.detectIntent(SessionsClient.java:253)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err:     at com.chatapp.chatbotlibrary.ChatbotActivity$RequestDialogflowTask.doInBackground(ChatbotActivity.java:418)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err:     at com.chatapp.chatbotlibrary.ChatbotActivity$RequestDialogflowTask.doInBackground(ChatbotActivity.java:396)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err: 		... 3 more
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err: Caused by: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed computing credential metadata
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.Status.asRuntimeException(Status.java:533)
2019-09-03 11:46:06.170 8594-8722/com.chatapp.chatappbot W/System.err: 	... 23 more
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err: Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.cache.LocalCache.get(LocalCache.java:3851)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3875)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4800)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.auth.oauth2.ServiceAccountJwtAccessCredentials.getRequestMetadata(ServiceAccountJwtAccessCredentials.java:346)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.auth.Credentials.blockingGetToCallback(Credentials.java:112)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.auth.oauth2.ServiceAccountJwtAccessCredentials.getRequestMetadata(ServiceAccountJwtAccessCredentials.java:323)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.auth.GoogleAuthLibraryCallCredentials.applyRequestMetadata(GoogleAuthLibraryCallCredentials.java:110)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.CallCredentials2.applyRequestMetadata(CallCredentials2.java:58)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.CallCredentialsApplyingTransportFactory$CallCredentialsApplyingTransport.newStream(CallCredentialsApplyingTransportFactory.java:108)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.ForwardingConnectionClientTransport.newStream(ForwardingConnectionClientTransport.java:49)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.InternalSubchannel$CallTracingTransport.newStream(InternalSubchannel.java:632)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:353)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.DelayedClientTransport$PendingStream.access$300(DelayedClientTransport.java:341)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at io.grpc.internal.DelayedClientTransport$5.run(DelayedClientTransport.java:300)
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err: 	... 6 more
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err: Caused by: java.lang.NullPointerException
2019-09-03 11:46:06.171 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:890)
2019-09-03 11:46:06.172 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.auth.oauth2.JwtCredentials$Builder.setPrivateKeyId(JwtCredentials.java:223)
2019-09-03 11:46:06.172 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.auth.oauth2.ServiceAccountJwtAccessCredentials$1.load(ServiceAccountJwtAccessCredentials.java:271)
2019-09-03 11:46:06.172 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.auth.oauth2.ServiceAccountJwtAccessCredentials$1.load(ServiceAccountJwtAccessCredentials.java:266)
2019-09-03 11:46:06.172 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3445)
2019-09-03 11:46:06.172 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2194)
2019-09-03 11:46:06.172 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2153)
2019-09-03 11:46:06.172 8594-8722/com.chatapp.chatappbot W/System.err:     at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2043)
2019-09-03 11:46:06.172 8594-8722/com.chatapp.chatappbot W/System.err: 	... 20 more
2019-09-03 11:46:06.175 8594-8594/com.chatapp.chatappbot E/ChatbotActivity: processResponse: Null Response
2019-09-03 11:46:06.193 1990-1990/com.google.android.inputmethod.latin W/Conv2QueryExtension: Conv2Query not enabled due to current app [com.chatapp.chatappbot] not in whitelist
```

#### External references such as API reference guides used	

- I have used my other project as a reference for this one.	https://github.com/abhi007tyagi/DialogflowChat

Thanks!

**Comment by vernazza** [comment]
This is happening also with com.google.cloud:google-cloud-speech upgrading from 1.17.0 to 1.18.0 or to 1.9.0

**Comment by arteam** [comment]
Happens to me as well when converting between `ServiceAccountCredentials` and `ServiceAccountJwtAccessCredentials`. It looks like the `privateKeyId` field is not getting copied.

**Comment by chingor13** [comment]
For the original issue, please update google-auth-library to 0.17.1. We will have a new release tomorrow that forces the update.

**Comment by chingor13** [comment]
@arteam What do you mean by "converting between ServiceAccountCredentials and ServiceAccountJwtAccessCredentials"

**Comment by abhi007tyagi** [comment]
Thanks @chingor13 
adding dependency -> implementation 'com.google.auth:google-auth-library-oauth2-http:0.17.1'
solved the issue. But want to know why it is required as I was not using it earlier in the actual library project?

**Comment by chingor13** [comment]
0.17.0 had a regression that was over-validating that privateKeyId must be non-null when it should have been allowed (hence the NullPointerException from Preconditions in the stacktrace). Unfortunately, we didn't catch that before we released gax and the latest google-cloud-x clients, but it will be addressed tomorrow.

**Comment by abhi007tyagi** [comment]
@chingor13 but I was not using it earlier. How was my code working while creating the library? Is this already embedded into Android SDK?

**Comment by chingor13** [comment]
google-auth-library is a transitive dependency of google-cloud-dialogflow so your package manager (looks like gradle for your case) is pulling in the dependency.

**Comment by codyoss** [comment]
It looks like this problem has been solved. If there is something I missed please feel free to reopen. Thanks.

**Comment by abhi007tyagi** [comment]
@codyoss I made a library to easily integrate Dialogflow into Android app. [Please try it](https://medium.com/@abhi007tyagi/android-dialogflow-chatbot-library-6b7b3822e7bc) and share feedback
