### ISSUE TITLE
Stackdriver: io.grpc.StatusRuntimeException: INTERNAL: An internal error occurred.

### ISSUE THREAD

**Issue by IRus** [googleapis/google-cloud-java#6212]
#### Environment details

1. OS type and version: macOS 10.14.6 (18G87)
1. Java version: 11.0.4-amzn
1. google-cloud-java version(s): 1.86.0, 1.89.0

#### Steps to reproduce

  1. Publish time series

#### Code example

```java
// micrometer-registry-stackdriver-1.2.0-sources.jar!/io/micrometer/stackdriver/StackdriverMeterRegistry.java:172
for (List<TimeSeries> partition : series) {
            try {
                CreateTimeSeriesRequest request = CreateTimeSeriesRequest.newBuilder()
                        .setName("projects/" + config.projectId())
                        .addAllTimeSeries(partition)
                        .build();

                logger.trace("publishing batch to Stackdriver:{}{}", System.lineSeparator(), request);

                client.createTimeSeries(request);
                logger.debug("successfully sent {} TimeSeries to Stackdriver", partition.size());
            } catch (ApiException e) {
                logger.warn("failed to send metrics to Stackdriver", e);
            }
        }
```

#### Stack trace
```
16:49:39.224 [stackdriver-metrics-publisher] WARN  i.m.s.StackdriverMeterRegistry - failed to send metrics to Stackdriver
com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: An internal error occurred.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:982)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:957)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:748)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:515)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.monitoring.v3.MetricServiceClient.createTimeSeries(MetricServiceClient.java:1156)
		at io.micrometer.stackdriver.StackdriverMeterRegistry.publish(StackdriverMeterRegistry.java:181)
		at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:48)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		... 3 common frames omitted
Caused by: io.grpc.StatusRuntimeException: INTERNAL: An internal error occurred.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 24 common frames omitted
```

Async stacktrace from Intellij Idea
```
publish:184, StackdriverMeterRegistry (io.micrometer.stackdriver)
publishSafely:48, PushMeterRegistry (io.micrometer.core.instrument.push)
run:-1, 1163189762 (io.micrometer.core.instrument.push.PushMeterRegistry$$Lambda$83)
call:515, Executors$RunnableAdapter (java.util.concurrent)
runAndReset$$$capture:305, FutureTask (java.util.concurrent)
runAndReset:-1, FutureTask (java.util.concurrent)
 - Async stack trace
<init>:151, FutureTask (java.util.concurrent)
<init>:227, ScheduledThreadPoolExecutor$ScheduledFutureTask (java.util.concurrent)
scheduleAtFixedRate:629, ScheduledThreadPoolExecutor (java.util.concurrent)
scheduleAtFixedRate:785, Executors$DelegatedScheduledExecutorService (java.util.concurrent)
start:68, PushMeterRegistry (io.micrometer.core.instrument.push)
start:132, StackdriverMeterRegistry (io.micrometer.stackdriver)
<init>:116, StackdriverMeterRegistry (io.micrometer.stackdriver)
<init>:67, StackdriverMeterRegistry (io.micrometer.stackdriver)
build:283, StackdriverMeterRegistry$Builder (io.micrometer.stackdriver)
meterRegistry:26, MeterRegistryKt (com.company.app.adaptor.core.metrics)
invoke:27, CoreModuleKt$coreMetricsModule$1$3 (com.company.app.adaptor.core)
invoke:-1, CoreModuleKt$coreMetricsModule$1$3 (com.company.app.adaptor.core)
create:54, DefinitionInstance (org.koin.core.instance)
get:40, SingleDefinitionInstance (org.koin.core.instance)
resolveInstance:70, BeanDefinition (org.koin.core.definition)
resolveInstance:165, Scope (org.koin.core.scope)
get:128, Scope (org.koin.core.scope)
getWithDefault:61, InstanceBuilderKt (org.koin.experimental.builder)
getArguments:34, InstanceBuilderKt (org.koin.experimental.builder)
invoke:18, AgentContextKt$agentModule$1$$special$$inlined$singleBy$2 (com.company.app.adaptor.agent)
invoke:-1, AgentContextKt$agentModule$1$$special$$inlined$singleBy$2 (com.company.app.adaptor.agent)
create:54, DefinitionInstance (org.koin.core.instance)
get:40, SingleDefinitionInstance (org.koin.core.instance)
resolveInstance:70, BeanDefinition (org.koin.core.definition)
resolveInstance:165, Scope (org.koin.core.scope)
get:128, Scope (org.koin.core.scope)
getWithDefault:61, InstanceBuilderKt (org.koin.experimental.builder)
getArguments:34, InstanceBuilderKt (org.koin.experimental.builder)
invoke:18, AgentContextKt$agentModule$1$$special$$inlined$singleBy$1 (com.company.app.adaptor.agent)
invoke:-1, AgentContextKt$agentModule$1$$special$$inlined$singleBy$1 (com.company.app.adaptor.agent)
create:54, DefinitionInstance (org.koin.core.instance)
get:40, SingleDefinitionInstance (org.koin.core.instance)
resolveInstance:70, BeanDefinition (org.koin.core.definition)
resolveInstance:165, Scope (org.koin.core.scope)
get:128, Scope (org.koin.core.scope)
invoke:83, AgentContextKt$agentModule$1$2 (com.company.app.adaptor.agent)
invoke:-1, AgentContextKt$agentModule$1$2 (com.company.app.adaptor.agent)
create:54, DefinitionInstance (org.koin.core.instance)
get:40, SingleDefinitionInstance (org.koin.core.instance)
resolveInstance:70, BeanDefinition (org.koin.core.definition)
resolveInstance:165, Scope (org.koin.core.scope)
get:128, Scope (org.koin.core.scope)
getWithDefault:61, InstanceBuilderKt (org.koin.experimental.builder)
getArguments:34, InstanceBuilderKt (org.koin.experimental.builder)
invoke:18, AgentContextKt$agentModule$1$$special$$inlined$single$1 (com.company.app.adaptor.agent)
invoke:-1, AgentContextKt$agentModule$1$$special$$inlined$single$1 (com.company.app.adaptor.agent)
create:54, DefinitionInstance (org.koin.core.instance)
get:40, SingleDefinitionInstance (org.koin.core.instance)
resolveInstance:70, BeanDefinition (org.koin.core.definition)
resolveInstance:165, Scope (org.koin.core.scope)
get:128, Scope (org.koin.core.scope)
main:83, AgentKt (com.company.app.adaptor.agent)
main:-1, AgentKt (com.company.app.adaptor.agent)
```

#### Any additional information below	

**Issue reproduced on OpenJDK 11 (11.0.4-amzn), but not on OpenJDK 8 (8.0.222-amzn)**

**Comment by athakor** [comment]
@IRus  I have followed your steps with OpenJDK 11 (11.0.4-amzn) and tried to reproduced it by creating simple time series example but I am unable to reproduced it. Below are the code snippets which  successfully sent TimeSeries to Stackdriver.

```
{

    String projectId = ServiceOptions.getDefaultProjectId();
    MetricServiceClient client = MetricServiceClient.create();

    // Prepares an individual data point
    TimeInterval interval =
        TimeInterval.newBuilder()
            .setEndTime(Timestamps.fromMillis(System.currentTimeMillis()))
            .build();

    TypedValue value = TypedValue.newBuilder().setDoubleValue(123.45).build();
    Point point = Point.newBuilder().setInterval(interval).setValue(value).build();

    List<Point> pointList = new ArrayList<>();
    pointList.add(point);
    ProjectName name = ProjectName.of(projectId);

    // Prepares the metric descriptor
    Map<String, String> metricLabels = new HashMap<>();
    Metric metric =
        Metric.newBuilder()
            .setType("custom.googleapis.com/my_metric")
            .putAllLabels(metricLabels)
            .build();

    // Prepares the monitored resource descriptor
    Map<String, String> resourceLabels = new HashMap<>();
    resourceLabels.put("instance_id", "1234567890123456789");
    resourceLabels.put("zone", "us-central1-f");
    MonitoredResource resource =
        MonitoredResource.newBuilder().setType("gce_instance").putAllLabels(resourceLabels).build();

    // Prepares the time series request
    TimeSeries timeSeries =
        TimeSeries.newBuilder()
            .setMetric(metric)
            .setResource(resource)
            .addAllPoints(pointList)
            .build();

    List<TimeSeries> timeSeriesList = new ArrayList<>();
    timeSeriesList.add(timeSeries);

    List<List<TimeSeries>> series = new ArrayList<List<TimeSeries>>();
    series.add(timeSeriesList);

    for (List<TimeSeries> partition : series) {
      try {
        CreateTimeSeriesRequest request =
            CreateTimeSeriesRequest.newBuilder()
                .setName("projects/" + projectId)
                .addAllTimeSeries(partition)
                .build();

        logger.trace("publishing batch to Stackdriver:{}{}", System.lineSeparator(), request);
        client.createTimeSeries(request);
        logger.debug("successfully sent {} TimeSeries to Stackdriver", partition.size());
      } catch (ApiException e) {
        logger.warn("failed to send metrics to Stackdriver", e);
      }
    }
    System.out.println("success");
  }
```

**Comment by IRus** [comment]
@athakor Thanks, I'll create sample project and where reproduce this issue.
