### ISSUE TITLE
Não é possível utilizar juntamente com o Firestore no Android

### ISSUE THREAD

**Issue by ReniDelonzek** [googleapis/google-cloud-java#6318]
Tenho um app que utiliza da biblioteca do Firestore e também precisa utilizar a do DialogFlow, até o momento estou utilizando a [biblioteca V1](https://github.com/dialogflow/dialogflow-android-client) e não enfrento quaisquer problemas, porém, como a V1 do DialogFlow vai ser encerrada em breve, preciso migrar para a V2. Em minhas tentativas de utilizar esta biblioteca juntamente com o Firestore, enfrento problemas de duplicação de classes.

O problema deve-se a que esta lib usa de  protobuf-java e a do firestore, protobuf-lite, ambas fornecem as mesmas classes com implementações diferentes

Já verifiquei [esse](https://github.com/googleapis/google-cloud-java/issues/5608) tópico que fala sobre, mas implementando a solução sugerida 

`configurations.all {
          exclude group:'com.google.api.grpc',module:'proto-google-common-protos'
          exclude group: 'com.google.protobuf', module: 'protobuf-java'
          exclude group: 'com.google.guava',module: 'guava-jdk5'
      }`

Tenho o seguinte erro 
`Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.google.cloud.dialogflow.v2beta1.QueryInput, unresolved supertypes: com.google.protobuf.GeneratedMessageV3
    class com.google.cloud.dialogflow.v2beta1.QueryInputOrBuilder, unresolved supertypes: com.google.protobuf.MessageOrBuilder
    class com.google.cloud.dialogflow.v2beta1.TextInput, unresolved supertypes: com.google.protobuf.GeneratedMessageV3
    class com.google.cloud.dialogflow.v2beta1.TextInputOrBuilder, unresolved supertypes: com.google.protobuf.MessageOrBuilder
    class com.google.cloud.dialogflow.v2beta1.TextInput.Builder, unresolved supertypes: com.google.protobuf.GeneratedMessageV3.Builder
    class com.google.cloud.dialogflow.v2beta1.QueryInput.Builder, unresolved supertypes: com.google.protobuf.GeneratedMessageV3.Builder
    class com.google.cloud.dialogflow.v2beta1.DetectIntentResponse, unresolved supertypes: com.google.protobuf.GeneratedMessageV3
    class com.google.cloud.dialogflow.v2beta1.DetectIntentResponseOrBuilder, unresolved supertypes: com.google.protobuf.MessageOrBuilder`

Existe alguma solução para isso?

**Comment by athakor** [comment]
@ReniDelonzek 

I have create simple android app that uses the Firestore library and DialogFlow V2 library and try to reproduced it but unable to reproduced it.

**Library**
```
implementation 'com.google.cloud:google-cloud-firestore:1.22.0'
implementation 'com.google.cloud:google-cloud-dialogflow:0.108.0-alpha'
```

can you share project level as well app level **build.gradle** files.

**Comment by ReniDelonzek** [comment]
The detail is that on android (client) we are required to use lib com.google.firebase: firebase-firestore: 21.0.0 '

Follow my build.gradle file

`apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'io.fabric'

apply plugin: 'kotlin-kapt'

def dbflow_version = "4.2.4"

android {
    compileSdkVersion 29
    defaultConfig {
        applicationId 
        minSdkVersion 18
        targetSdkVersion 29
        versionCode 54
        versionName "5.4"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            manifestPlaceholders = [crashlyticsEnabled: true]
        }
        debug {
            manifestPlaceholders = [crashlyticsEnabled: false]
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/INDEX.LIST'
    }
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
    configurations.all {
        exclude group: 'com.google.api.grpc', module: 'proto-google-common-protos'
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
        exclude group: 'com.google.guava', module: 'guava-jdk5'
    }
    
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'

    implementation 'androidx.vectordrawable:vectordrawable:1.0.0'
    configurations {
        all*.exclude group: 'com.android.support', module: 'support-v13'
    }


    implementation("android.arch.work:work-runtime:1.0.0-alpha11") {
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }
    //implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'com.google.android.material:material:1.1.0-alpha09'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    implementation 'com.google.firebase:firebase-auth:19.0.0'
    implementation('com.google.firebase:firebase-firestore:21.0.0')
    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.google.android.gms:play-services-auth:17.0.0'
    //implementation 'com.google.firebase:firebase-inappmessaging-display:19.0.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'


    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'

    implementation 'ai.api:sdk:2.0.5@aar'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'commons-io:commons-io:2.4'
    implementation('ai.api:libai:1.4.8') {
        exclude module: 'log4j-core'
    }
    implementation 'com.google.dagger:dagger:2.22'
    kapt 'com.google.dagger:dagger-compiler:2.16'

    implementation 'io.github.dreierf:material-intro-screen:0.0.6'
    implementation 'de.hdodenhof:circleimageview:3.0.0'

    implementation 'weekselection.com.library:library:1.0.0'
    implementation 'com.google.android:flexbox:1.1.0'

    implementation 'com.github.iamrobj:NotificationHelperLibrary:2.0.5'

    kapt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow-kotlinextensions:${dbflow_version}"

    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.android.billingclient:billing:2.0.3'

    implementation 'com.squareup.retrofit2:retrofit:2.5.0'//rede
    implementation 'com.squareup.retrofit2:converter-jackson:2.4.0'
    implementation 'com.github.pchmn:MaterialChipsInput:1.0.8'
    implementation 'com.github.clans:fab:1.6.4'//floatingActionMenu

    implementation 'com.github.ialokim:android-phone-field:0.2.3'
    implementation 'com.google.cloud:google-cloud-dialogflow:0.110.0-alpha'
    //implementation 'io.grpc:grpc-okhttp:1.21.0'


    implementation 'com.squareup.picasso:picasso:2.71828'

    implementation 'com.stepstone.apprating:app-rating:2.3.1'

}
apply plugin: 'com.google.gms.google-services'
googleServices { disableVersionCheck = true }
`

Compiling as it is, it returns the errors mentioned in the question when you try to use some feature of the dialogflow library, just because you are removing part of the library with the excludes.
Removing the excludes, the error is in the duplicate classes, which I mentioned in the question and which were discussed in the topic in which I mentioned the link.

Please, I really need to use both libraries before version v1 stops working, if you can help me I'm very grateful

**Comment by athakor** [comment]
@ReniDelonzek Thanks for your info, I have tried your build.gradle file and able to reproduced it.
could please remove `configurations.all{}` block from your build.gradle (module app) file and Add below code instead of that.I have checked that its working fine without getting any duplicate classes or dialogflow or protobuf related error.

```
 configurations{
        implementation.exclude module:'protolite-well-known-types'
        implementation.exclude module:'protobuf-lite'
    }
```

**Comment by ReniDelonzek** [comment]
@athakor  Thanks for the quick response

I removed my exclude and added yours, the application actually conforms without errors, but when I try to use firestore, the following error is provided

`java.lang.RuntimeException: Internal error in Cloud Firestore (21.0.0).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(com.google.firebase:firebase-firestore@@21.0.0:513)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ExceptionInInitializerError
        at com.google.firestore.v1.ListenRequest.getDefaultInstance(com.google.firebase:firebase-firestore@@21.0.0:915)
        at com.google.firestore.v1.FirestoreGrpc.getListenMethod(com.google.firebase:firebase-firestore@@21.0.0:408)
        at com.google.firebase.firestore.remote.WatchStream.<init>(com.google.firebase:firebase-firestore@@21.0.0:61)
        at com.google.firebase.firestore.remote.Datastore.createWatchStream(com.google.firebase:firebase-firestore@@21.0.0:112)
        at com.google.firebase.firestore.remote.RemoteStore.<init>(com.google.firebase:firebase-firestore@@21.0.0:167)
        at com.google.firebase.firestore.core.FirestoreClient.initialize(com.google.firebase:firebase-firestore@@21.0.0:262)
        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$2(com.google.firebase:firebase-firestore@@21.0.0:116)
        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$2.run(Unknown Source:8)
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(com.google.firebase:firebase-firestore@@21.0.0:423)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(Unknown Source:2)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(com.google.firebase:firebase-firestore@@21.0.0:312)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@21.0.0:219)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.RuntimeException: Unable to get message info for com.google.firestore.v1.ListenRequest
        at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:62)
        at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:143)
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:55)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:170)
        at com.google.firestore.v1.ListenRequest.<clinit>(com.google.firebase:firebase-firestore@@21.0.0:911)
        at com.google.firestore.v1.ListenRequest.getDefaultInstance(com.google.firebase:firebase-firestore@@21.0.0:915) 
        at com.google.firestore.v1.FirestoreGrpc.getListenMethod(com.google.firebase:firebase-firestore@@21.0.0:408) 
        at com.google.firebase.firestore.remote.WatchStream.<init>(com.google.firebase:firebase-firestore@@21.0.0:61) 
        at com.google.firebase.firestore.remote.Datastore.createWatchStream(com.google.firebase:firebase-firestore@@21.0.0:112) 
        at com.google.firebase.firestore.remote.RemoteStore.<init>(com.google.firebase:firebase-firestore@@21.0.0:167) 
        at com.google.firebase.firestore.core.FirestoreClient.initialize(com.google.firebase:firebase-firestore@@21.0.0:262) 
        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$2(com.google.firebase:firebase-firestore@@21.0.0:116) 
        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$2.run(Unknown Source:8) 
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(com.google.firebase:firebase-firestore@@21.0.0:423) 
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(Unknown Source:2) 
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(com.google.firebase:firebase-firestore@@21.0.0:312) 
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@21.0.0:219) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.UnsupportedOperationException
        at com.google.firestore.v1.ListenRequest.dynamicMethod(com.google.firebase:firebase-firestore@@21.0.0:903)
        at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:251)
        at com.google.protobuf.GeneratedMessageLite.buildMessageInfo(GeneratedMessageLite.java:279)
        at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:60)
        at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:143) 
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:55) 
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93) 
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107) 
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:170) 
        at com.google.firestore.v1.ListenRequest.<clinit>(com.google.firebase:firebase-firestore@@21.0.0:911) 
        at com.google.firestore.v1.ListenRequest.getDefaultInstance(com.google.firebase:firebase-firestore@@21.0.0:915) 
        at com.google.firestore.v1.FirestoreGrpc.getListenMethod(com.google.firebase:firebase-firestore@@21.0.0:408) 
        at com.google.firebase.firestore.remote.WatchStream.<init>(com.google.firebase:firebase-firestore@@21.0.0:61) 
        at com.google.firebase.firestore.remote.Datastore.createWatchStream(com.google.firebase:firebase-firestore@@21.0.0:112) 
        at com.google.firebase.firestore.remote.RemoteStore.<init>(com.google.firebase:firebase-firestore@@21.0.0:167) 
        at com.google.firebase.firestore.core.FirestoreClient.initialize(com.google.firebase:firebase-firestore@@21.0.0:262) 
        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$2(com.google.firebase:firebase-firestore@@21.0.0:116) 
        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$2.run(Unknown Source:8) 
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(com.google.firebase:firebase-firestore@@21.0.0:423) 
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(Unknown Source:2) 
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(com.google.firebase:firebase-firestore@@21.0.0:312) 
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@21.0.0:219) 
        at java.lang.Thread.run(Thread.java:919) `

**Comment by athakor** [comment]
@ReniDelonzek  Its really hard to reproduced.It would great if You can share your sample code or git repository and Please make sure there's no sensitive data before sharing.

**Comment by ReniDelonzek** [comment]
@athakor  The error only occurs when you play the application connected to firebase and make any request with firestore, I believe that is why you could not reproduce the error. Unfortunately I can not share the project, but I created a test by reproducing the same error when executed and an attempt is made to save any record in firestore

https://github.com/ReniDelonzek/TestDialogFlow

**Comment by ReniDelonzek** [comment]
Any updates on this?

**Comment by athakor** [comment]
@ReniDelonzek Thanks for your code sample i have tried it and able to reproduced it.Most likely you are getting this error because of dependency eliminate.Could you please modified your configuration something like below.I have checked record save in firestore without app crash.

```
configurations {
        implementation.exclude group: 'com.google.api.grpc'
        implementation.exclude module: 'protobuf-java'
    }
```

**Output:**
![output](https://user-images.githubusercontent.com/49403056/66470745-3775cf00-ea58-11e9-84b4-c922d84f4ee0.png)

**Comment by ReniDelonzek** [comment]
The problem is that this excludes parts of dialogFlow, causing it not to compile when you try to use it. I modified the project and updated it in git, I invite you to try compiling it using dialogFlow. The error displayed is as follows:

`> Task :app:compileDebugKotlin FAILED
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/ListenerDialogFlow.kt: (3, 39): Unresolved reference: DetectIntentResponse
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/ListenerDialogFlow.kt: (7, 28): Unresolved reference: DetectIntentResponse
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/MainActivity.kt: (7, 39): Unresolved reference: DetectIntentResponse
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (6, 39): Unresolved reference: DetectIntentRequest
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (7, 39): Unresolved reference: DetectIntentResponse
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (8, 39): Unresolved reference: QueryInput
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (9, 39): Unresolved reference: SessionName
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (14, 26): Unresolved reference: SessionName
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (16, 29): Unresolved reference: QueryInput
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (18, 27): Unresolved reference: DetectIntentResponse
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (20, 54): Unresolved reference: DetectIntentResponse
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (22, 39): Unresolved reference: DetectIntentRequest
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (26, 35): Cannot access class 'com.google.cloud.dialogflow.v2.DetectIntentResponse'. Check your module classpath for missing or conflicting dependencies
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (26, 35): Cannot access class 'com.google.cloud.dialogflow.v2.DetectIntentRequest'. Check your module classpath for missing or conflicting dependencies
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/RequestJavaV2Task.kt: (34, 42): Unresolved reference: DetectIntentResponse
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/UtilsDialogFlow.kt: (27, 17): Unresolved reference: SessionName
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/UtilsDialogFlow.kt: (30, 30): Unresolved reference: QueryInput
e: /Users/reni/Downloads/Projetos/TestDialogFlow/app/src/main/java/br/com/rd/testdialogflow/UtilsDialogFlow.kt: (32, 21): Unresolved reference: TextInput
`

Forgive my insistence on the subject, I really need to find a way out

**Comment by ReniDelonzek** [comment]
No updates on this?

**Comment by BenWhitehead** [comment]
Hi @ReniDelonzek looking at things here, it looks like you are excluding `com.google.protobuf:*` from your class path. Dialog flow needs the classes in `com.google.protobuf` to satisfy its class inheritance.

For example [`DetectIntentResponse`](https://github.com/googleapis/google-cloud-java/blob/484a2f00046ec6306c6ef6b86484b72600f09981/google-api-grpc/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/DetectIntentResponse.java#L15) extends from [`com.google.protobuf.GeneratedMessageV3`](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java#L79) which is excluded because it is included in `com.google.protobuf:protobuf-java`.

You'll need to update your gradle config to allow this artifact to be included.

Hope this helps.
