### ISSUE TITLE
AutoML: GRPC Related Exception using PredictionServiceClient

### ISSUE THREAD

**Issue by MarioAriasC** [googleapis/google-cloud-java#6338]
Trying to use `PredictionServiceClient.batchPredictAsync()` shows an exception on stdout and it doesn't start the prediction process.

The exception is GRPC/Threading related.

#### Environment details

1. AutoML
2. OS type and version: Ubuntu 
3. Java version: OpenJDK 9 (+ Kotlin 1.3.50)
4. google-cloud-java version(s): 0.110.0-beta

#### Steps to reproduce

  1. `PredictionServiceClient.batchPredictAsync()`
  2. Use `ApiFutures.addCallback` to wait for the response

#### Code example

```kotlin
fun startPrediction(inputUris: String): OperationFuture<BatchPredictResult, OperationMetadata>? {
            logger.debug { "Start prediction" }
            logger.debug { "Input Uris $inputUris" }
            logger.debug { "Base prefix $basePrefix" }

            val inputConfig = BatchPredictInputConfig.newBuilder()
                .setGcsSource(GcsSource.newBuilder().addInputUris(inputUris))
                .build()
            val outputConfig = BatchPredictOutputConfig.newBuilder()
                .setGcsDestination(GcsDestination.newBuilder().setOutputUriPrefix(basePrefix))
                .build()
            return PredictionServiceClient.create().use { client ->
                client.batchPredictAsync(
                    config[GoogleSpec.AutoMl.modelId], inputConfig, outputConfig, mapOf(
                        "shot_classification" to "True",
                        "1s_interval_classification" to "True",
                        "score_threshold" to "0"
                    )
                )
            }.also {
                logger.debug { "ApiFuture: $it" }
                logger.debug { "Prediction request sent to google, waiting for the response" }
            }
        }

val future = startPrediction(predictionUri)!!

ApiFutures.addCallback(future, object : ApiFutureCallback<BatchPredictResult> {
  override fun onSuccess(result: BatchPredictResult?) {
    logger.debug { "Results: $result" }          
    downloadResults()
    logger.debug { "ML process finished" }
  }
     
 override fun onFailure(t: Throwable?) {
   logger.error(t) { "Error on ApiFuture execution" }
 }
 }, MoreExecutors.directExecutor())
```

The callback never gets executed, neither `onSuccess` nor `onFailure`

#### Stack trace
```
Sep 23, 2019 11:21:49 AM io.grpc.internal.ManagedChannelImpl$1 uncaughtException
SEVERE: [Channel<1>: (automl.googleapis.com:443)] Uncaught exception in the SynchronizationContext. Panic!
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@101dfa3f rejected from java.util.concurrent.ScheduledThreadPoolExecutor@a9fc902[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:332)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:560)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:652)
        at io.grpc.internal.DelayedClientTransport.reprocess(DelayedClientTransport.java:297)
        at io.grpc.internal.ManagedChannelImpl.updateSubchannelPicker(ManagedChannelImpl.java:790)
        at io.grpc.internal.ManagedChannelImpl.access$5200(ManagedChannelImpl.java:102)
        at io.grpc.internal.ManagedChannelImpl$LbHelperImpl$1UpdateBalancingState.run(ManagedChannelImpl.java:1149)
        at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:88)
        at io.grpc.internal.InternalSubchannel$TransportListener.transportReady(InternalSubchannel.java:579)
        at io.grpc.netty.shaded.io.grpc.netty.ClientTransportLifecycleManager.notifyReady(ClientTransportLifecycleManager.java:43)
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$FrameListener.onSettingsRead(NettyClientHandler.java:783)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:419)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:637)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onSettingsRead(Http2InboundFrameLogger.java:93)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readSettingsFrame(DefaultHttp2FrameReader.java:542)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:263)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:390)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:254)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1476)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1225)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1272)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:844)

```

#### Any additional information below	

Part of the same application uses Cloud Storage and is working fine

**Comment by athakor** [comment]
> java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@101dfa3f rejected from java.util.concurrent.ScheduledThreadPoolExecutor@a9fc902[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]

@MarioAriasC, You seem to run into an issue where an executor that is used by your transport channel is rejecting any further tasks but am not sure why the thing is happen.

@olavloite help would be appreciate
