### ISSUE TITLE
Bigtable from Dataproc: Guava error trying to instantiate Bigtable client

### ISSUE THREAD

**Issue by Gastove** [googleapis/google-cloud-java#6355]
#### Environment details
We're running a Dataproc cluster with the `1.3.43-debian9` image, Spark version 2.3.3, Scala version 2.11.8, and Java version 1.8.0_222. We've reproduced this using the `google-cloud-bigtable` jar at version 0.95-alpha and 0.110.0, as well as the `bigtable-hbase-1.x` jar at version 1.9.

#### Steps to reproduce

  1. Build an assembled jar containing the `google-cloud-bigtable` jar; upload it to a GCP bucket.
  1. Configure a dataproc cluster with Bigtable
  1. ssh to the master node of a dataproc cluster. 
  1. Start `spark-shell` using the JAR option to include your jar on the classpath.
  1. Run:
```
scala> import com.google.cloud.bigtable.data.v2.BigtableDataClient
scala> val bigTable = BigtableDataClient.create(projectId, instanceId)
```

#### Stack trace
```
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;J)V
  at com.google.api.gax.batching.BlockingSemaphore.checkNotNegative(BlockingSemaphore.java:40)
  at com.google.api.gax.batching.BlockingSemaphore.<init>(BlockingSemaphore.java:44)
  at com.google.api.gax.batching.FlowController.<init>(FlowController.java:168)
  at com.google.api.gax.rpc.BatchingCallSettings.<init>(BatchingCallSettings.java:70)
  at com.google.api.gax.rpc.BatchingCallSettings.<init>(BatchingCallSettings.java:46)
  at com.google.api.gax.rpc.BatchingCallSettings$Builder.build(BatchingCallSettings.java:146)
  at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStubSettings.<init>(EnhancedBigtableStubSettings.java:
148)
  at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStubSettings.<init>(EnhancedBigtableStubSettings.java:
81)
  at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStubSettings$Builder.build(EnhancedBigtableStubSetting
s.java:626)
  at com.google.cloud.bigtable.data.v2.BigtableDataSettings.<init>(BigtableDataSettings.java:61)
  at com.google.cloud.bigtable.data.v2.BigtableDataSettings.<init>(BigtableDataSettings.java:57)
  at com.google.cloud.bigtable.data.v2.BigtableDataSettings$Builder.build(BigtableDataSettings.java:210)
  at com.google.cloud.bigtable.data.v2.BigtableDataClient.create(BigtableDataClient.java:128)
  at com.squarespace.databases.mumu.BigTable.getClient(BigTable.scala:34)
  ... 49 elided 
```

#### External references such as API reference guides used	

- https://cloud.google.com/bigtable/docs/reference/libraries

#### Any additional information below	
Happy to provide any extra information desired.

**Comment by rahulKQL** [comment]
Hi @Gastove, The reason build this `NoSuchMethodFound` exception is guava version pulling in from spark classpath.

One workaround for that would be to shade your assembled jar with prefixing your organization name. In your `pom.xml`:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.2.1</version>
    <configuration>
        <shadedArtifactAttached>true</shadedArtifactAttached>
        <relocations>
            <relocation>
                <pattern>com.google.common</pattern>
                <shadedPattern>com.shaded.google.common</shadedPattern>
            </relocation>
        </relocations>
    </configuration>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by Gastove** [comment]
@rahulKQL that's interesting -- I checked for that. I am, admittedly, using SBT, but I'm also using the SBT dependency tree plugin, and I verified that no earlier versions of Guava were on my classpath. I also loaded the `spark-shell` with my uberjar attached, and verified that I could, indeed, import the needed `Precondition` class, and that the `checkArgument` function was present. 

So! I don't doubt you; Guava version conflicts are one of my oldest and least favourite kinds of transitive dependency problems. My question is: do you have _any idea_ which dependency might be causing this, or any suggestion for how I could pin down the runtime classpath myself?

**Comment by rahulKQL** [comment]
@Gastove Thanks for ack. 

By simply listing the classloader shows this dependency comes from Hadoop in my case:
```scala
val cl = java.lang.ClassLoader.getSystemClassLoader;
val urls:[java.net.URL] = cl.asInstanceOf[java.net.URLClassLoader].getURLs;
urls.filter(x => x.toString.matches(".*guava.*")).foreach(println);
```
<img width="921" alt="Screenshot 2019-09-28 at 1 06 53 AM" src="https://user-images.githubusercontent.com/42969463/65797226-4cb34980-e18c-11e9-861d-acdf1d684c41.png">

I am not sure if you are already doing this but, here is the [link of the solution](https://github.com/googleapis/google-cloud-java/issues/4414#issuecomment-458681216) to a similar issue faced by another user.

**Comment by rahulKQL** [comment]
Closing this issue due to inactivity, If still facing the issue please reopen it.

**Comment by shril** [comment]
I am facing similar issues - More details in this https://github.com/googleapis/java-bigtable/issues/1789
