### ISSUE TITLE
java.lang.NoClassDefFoundError: StorageOptions

### ISSUE THREAD

**Issue by turboT4** [googleapis/google-cloud-java#6679]
Been recently dealing with issues regarding Guava versions within Hadoop and the rest used by other components.

After getting rid of the MethodNotFound errors regarding Preconditions I've came to another exception which I can't really understand as the library is provided within the sbt file...

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/cloud/storage/StorageOptions
```

Taking into account this libraries and versioning.

```
val googleCloudV    = "1.89.0"
val googleHadoopV   = "hadoop3-2.0.0"

val cloudStorage = "com.google.cloud"            % "google-cloud-storage" % googleCloudV
val cloudHadoop  = "com.google.cloud.bigdataoss" % "gcs-connector"        % googleHadoopV
```

I've also tried setting `cloudStorage` as `"provided"` but I'm getting, in that case, the same exception regarding Guava.

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
```

I've already included shadowing to avoid conflict with Hadoop dependencies.

```
assemblyShadeRules in assembly := Seq(ShadeRule.rename("com.google.**" -> "shadeio.@1").inAll)
```

**Comment by pmakani** [comment]
@turboT4 I tried your depenedencies and made small changes in your config, it's work for me. Could you try below sbt config ?

```scala
val googleCloudV = "1.89.0"
val googleHadoopV = "hadoop3-2.0.0"

libraryDependencies += "com.google.cloud.bigdataoss" % "gcs-connector" % googleHadoopV
libraryDependencies += "com.google.cloud" % "google-cloud-storage" % googleCloudV

dependencyOverrides := Seq(
  "com.google.guava" % "guava" % "28.0-jre"
)
assemblyShadeRules in assembly := Seq(
  ShadeRule
    .rename("com.google.*.**" -> "shade.com.google.shade@1.shade@2")
    .inAll
)
```

**Comment by turboT4** [comment]
@pmakani thanks a lot for the reply! Just tried your config and the following still pops up in the console.

```Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V```

Could this be related to any other dependency? Personally I don't use Guava within the project. Should I import it and include it within the module which is throwing the conflict?

**Comment by turboT4** [comment]
@pmakani just a quick update. I've changed all the versions to my clusters `1.3.34` which would mean changing Hadoop to `hadoop2-1.9.17` and so the `google-cloud-storage` to cope with that.

I've changed the storage lib version to the month when `hadoop2-1.9.17` was released and the given conflict (I think I've asked this before and someone told me that this was included by mistake?).

```[error] deduplicate: different file contents found in the following:
[error] /Users/testing/.m2/repository/com/google/http-client/google-http-client-apache/2.0.0/google-http-client-apache-2.0.0.jar:com/google/api/client/http/apache/ContentEntity.class
[error] /Users/testing/.m2/repository/com/google/http-client/google-http-client/1.29.1/google-http-client-1.29.1.jar:com/google/api/client/http/apache/ContentEntity.class```

Having the following versioning now.

```
    val googleCloudV    = "1.74.0"
    val googleHadoopV   = "hadoop2-1.9.17"
```

Deduplication error when performing the assembly is solved in `1.77.0` but again, no luck with the Preconditions error thrown before once deployed in Dataproc.

**Comment by pmakani** [comment]
@turboT4 it's works for me, you can see below.
![Screenshot from 2019-11-05 17-03-34](https://user-images.githubusercontent.com/44407134/68204808-cbeb3700-ffee-11e9-9837-e407b45eabcc.png)
it could be problem with your sbt local dependencies. can you delete all those folder where sbt store depedencies i.e. `.sbt, .ivy2`

**Comment by turboT4** [comment]
Still, no luck so far @pmakani 😢 .

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.google.cloud.storage.StorageImpl.optionMap(StorageImpl.java:1480)
	at com.google.cloud.storage.StorageImpl.optionMap(StorageImpl.java:1469)
	at com.google.cloud.storage.StorageImpl.optionMap(StorageImpl.java:1502)
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:326)
```

**Comment by pmakani** [comment]
@turboT4 can you please share your sbt config file ?

**Comment by turboT4** [comment]
Absolutely @pmakani , here it goes.

```
organization := "com.sample"
name := "sample-common"
version in ThisBuild := "5.0.0"

scalaVersion in ThisBuild := "2.11.0"

lazy val global = project
  .in(file("."))
  .settings(
    name := "sample-common",
    assemblyJarName in assembly := "sample-common-assembly" + "-" + sys.env.getOrElse("version", "dev") + ".jar",
    settings
  )
  .aggregate(
    sample_io,
    sample_batch,
    sample_sandbox
  )

lazy val sample_io = project
  .in(file("sample-io"))
  .settings(
    name := "sample-io",
    assemblyJarName in assembly := "sample-io-assembly" + "-" + sys.env.getOrElse("version", "dev") + ".jar",
    settings,
    libraryDependencies ++= commonDependencies,
    libraryDependencies ++= sampleIODependencies
  )

lazy val sample_batch = project
  .in(file("sample-batch"))
  .settings(
    name := "sample-batch",
    assemblyJarName in assembly := "sample-batch-assembly" + "-" + sys.env.getOrElse("version", "dev") + ".jar",
    settings,
    libraryDependencies ++= commonDependencies,
    libraryDependencies ++= sampleBatchDependencies
  )
  .dependsOn(
    sample_io
  )

lazy val sample_sandbox = project
  .in(file("sample-sandbox"))
  .settings(
    name := "sample-sandbox",
    assemblyJarName in assembly := "sample-sandbox-assembly" + "-" + sys.env.getOrElse("version", "dev") + ".jar",
    settings,
    libraryDependencies ++= commonDependencies,
    libraryDependencies ++= sampleSandboxDependencies
  )
  .dependsOn(
    sample_io
  )

lazy val dependencies =
  new {
    val sparkV          = "2.3.0"
    val gsonV           = "2.3.1"
    val slf4jV          = "1.7.25"
    val jodaTimeV       = "2.9.9"
    val mongodbV        = "2.4.2"
    val sparkConnectorV = "2.3.2"
    val scalaJV         = "2.4.1"
    val googleCloudV    = "1.89.0"
    val googleHadoopV   = "hadoop3-2.0.0"

    // SPARK
    val sparkCore      = "org.apache.spark" %% "spark-core"      % sparkV % "provided"
    val sparkSql       = "org.apache.spark" %% "spark-sql"       % sparkV % "provided"
    val sparkStreaming = "org.apache.spark" %% "spark-streaming" % sparkV % "provided"
    val sparkMlib      = "org.apache.spark" %% "spark-mllib"     % sparkV % "provided"

    // GCP
    val cloudStorage = "com.google.cloud"            % "google-cloud-storage" % googleCloudV
    val cloudHadoop  = "com.google.cloud.bigdataoss" % "gcs-connector"        % googleHadoopV

    // OTHERS
    val gson           = "com.google.code.gson" % "gson"                   % gsonV
    val slf4j          = "org.slf4j"            % "jcl-over-slf4j"         % slf4jV % "provided"
    val jodaTime       = "joda-time"            % "joda-time"              % jodaTimeV
    val mongodb        = "org.mongodb.scala"    %% "mongo-scala-driver"    % mongodbV
    val sparkConnector = "org.mongodb.spark"    %% "mongo-spark-connector" % sparkConnectorV

    val logbackV      = "1.2.3"
    val logstashV     = "4.11"
    val scalaLoggingV = "3.7.2"

    val typesafeConfigV = "1.3.1"
    val pureconfigV     = "0.8.0"
    val monocleV        = "1.4.0"
    val akkaV           = "2.5.6"
    val scalatestV      = "3.0.4"
    val scalacheckV     = "1.13.5"

    val logback      = "ch.qos.logback"             % "logback-classic"          % logbackV
    val logstash     = "net.logstash.logback"       % "logstash-logback-encoder" % logstashV
    val scalaLogging = "com.typesafe.scala-logging" %% "scala-logging"           % scalaLoggingV

    val typesafeConfig = "com.typesafe"               % "config"         % typesafeConfigV
    val akka           = "com.typesafe.akka"          %% "akka-stream"   % akkaV
    val monocleCore    = "com.github.julien-truffaut" %% "monocle-core"  % monocleV
    val monocleMacro   = "com.github.julien-truffaut" %% "monocle-macro" % monocleV
    val pureconfig     = "com.github.pureconfig"      %% "pureconfig"    % pureconfigV
    val scalatest      = "org.scalatest"              %% "scalatest"     % scalatestV
    val scalacheck     = "org.scalacheck"             %% "scalacheck"    % scalacheckV
    val scalaJ         = "org.scalaj"                 %% "scalaj-http"   % scalaJV

    val jsonSimple   = "com.googlecode.json-simple" % "json-simple"    % "1.1.1"
    val json4sNative = "org.json4s"                 %% "json4s-native" % "3.6.6"

  }

lazy val commonDependencies = Seq(
  dependencies.sparkSql,
  dependencies.sparkCore,
  dependencies.sparkStreaming,
  dependencies.slf4j,
  dependencies.typesafeConfig,
  //  dependencies.logback,
  //  dependencies.logstash,
  //  dependencies.scalaLogging,
  //  dependencies.akka,
  dependencies.scalatest % "test",
  dependencies.scalaJ
  //  dependencies.scalacheck % "test"
)

lazy val sampleIODependencies = Seq(
  dependencies.jodaTime,
  dependencies.mongodb
)

lazy val sampleBatchDependencies = Seq(
  dependencies.mongodb,
  dependencies.sparkConnector,
  dependencies.jsonSimple,
  dependencies.cloudHadoop,
  dependencies.cloudStorage
)

lazy val sampleSandboxDependencies = Seq(
  dependencies.jsonSimple
)

// SETTINGS

lazy val settings =
commonSettings ++
wartremoverSettings ++
scalafmtSettings

lazy val compilerOptions = Seq(
  "-unchecked",
  "-feature",
  "-language:existentials",
  "-language:higherKinds",
  "-language:implicitConversions",
  "-language:postfixOps",
  "-deprecation",
  "-encoding",
  "utf8"
)

lazy val commonSettings = Seq(
  scalacOptions ++= compilerOptions,
  crossPaths := false,
  resolvers ++= Seq(
    "Local Maven Repository" at "file://" + Path.userHome.absolutePath + "/.m2/repository"
  )
)

lazy val wartremoverSettings = Seq(
  wartremoverWarnings in (Compile, compile) ++= Warts.allBut(Wart.Throw)
)

lazy val scalafmtSettings =
  Seq(
    scalafmtOnCompile := true,
    scalafmtTestOnCompile := true,
    scalafmtVersion := "1.2.0"
  )

lazy val assemblySettings = Seq(
  assemblyJarName in assembly := name.value + ".jar",
  assemblyMergeStrategy in assembly := {
    case PathList("META-INF", xs @ _*) => MergeStrategy.discard
    case _                             => MergeStrategy.first
  }
)
```
