### ISSUE TITLE
Firestore: support updating an individual field with pojo as a value

### ISSUE THREAD

**Issue by menulis** [googleapis/google-cloud-java#6711]
Current Firestore (1.30.0+) does not support updating an individual field with pojo as a value, thus the following code

```
data class Test(
    val primitiveField: String,
    val complexField: Test2
)

data class Test2(
    val primitiveField1: String,
    val primitiveField2: Int
)

val firestore = FirestoreOptions.getDefaultInstance().service

fun main() {
    val test = Test("test", Test2("test", 123))
    val docRef = firestore.collection("test").document("test")
    docRef.set(test).get()
    docRef.update("complexField", Test2("updated test", 456)).get()
}
```
yields to the following exception:

```
Exception in thread "main" com.google.cloud.firestore.FirestoreException: Cannot convert Test2(primitiveField1=updated test, primitiveField2=456) to Firestore Value
	at com.google.cloud.firestore.FirestoreException.invalidState(FirestoreException.java:51)
	at com.google.cloud.firestore.UserDataConverter.encodeValue(UserDataConverter.java:180)
	at com.google.cloud.firestore.DocumentSnapshot.fromObject(DocumentSnapshot.java:89)
	at com.google.cloud.firestore.UpdateBuilder.performUpdate(UpdateBuilder.java:513)
	at com.google.cloud.firestore.UpdateBuilder.performUpdate(UpdateBuilder.java:502)
	at com.google.cloud.firestore.UpdateBuilder.update(UpdateBuilder.java:389)
	at com.google.cloud.firestore.DocumentReference.update(DocumentReference.java:261)
```

This is because _UserDataConverter.encodeValue_ only accepts either primitive types or list or maps of primitive types (which get encoded recursively). However, I do not see any reason why pojos could not be accepted as valid field values. Further, _CustomClassMapper.convertToPlainJavaTypes_ function used to convert pojos to maps could potentially be (re)used. In other words, the following workaround works (as long as you access the CustomClassMapper class through reflection as it is package-private) as expected:

```
docRef.update(
    "complexField",
    CustomClassMapper.convertToPlainJavaTypes(Test2("updated test", 456))
).get()
```
**Related issues:**
- https://github.com/googleapis/google-cloud-java/issues/5622
- https://github.com/googleapis/google-cloud-java/issues/6039

**Comment by menulis** [comment]
`UpdateBuilder` has two private polymorphic performUpdate methods: the first one (1) that takes 5 arguments and internally calls `CustomClassMapper.convertToPlainJavaTypes ` followed by the call to the second `performUpdate` method (2) that takes three arguments:

```
private T performUpdate(
      @Nonnull DocumentReference documentReference,
      @Nonnull Precondition options,
      @Nonnull FieldPath fieldPath,
      @Nullable Object value,
      Object[] moreFieldsAndValues
) {
    Object data = CustomClassMapper.convertToPlainJavaTypes(value);
    // ...
    return performUpdate(documentReference, fields, options);
}
```

```
private T performUpdate(
      @Nonnull DocumentReference documentReference,
      @Nonnull final Map<FieldPath, Object> fields,
      @Nonnull Precondition precondition
) {
    ///...
}
```

`UpdateBuilder` has six public polymorphic `update` methods, but only four of them (the ones that take `value` argument of type `Object`) call (1), the other two are calling (2). The same is true for the six update methods in `DocumentReference`.

Not only this is a bit confusing, I also believe it is quite common to update multiple fields with a pojo as a value in a batch or transaction, therefore the value of the `Map<String, Object> fields` parameter should also assume that the one of the values may be a pojo. This way the two versions of `performUpdate` could be merged into one or the only method that calls (2) is (1).
