### ISSUE TITLE
BigQuery listJobs throws NullPointerException

### ISSUE THREAD

**Issue by anthavio** [googleapis/google-cloud-java#7087]
#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: macOS Catalina 10.15.2
3. Java version: jdk1.8.0_211
4. google-cloud-java version(s):
"com.google.cloud" % "google-cloud-bigquery" % "1.102.0"

#### Code example

```scala
bigquery.listJobs(JobListOption.allUsers()).iterateAll().asScala.foreach(job => println(job.toString))
```

#### Stack trace
```
Exception in thread "main" java.lang.NullPointerException
	at com.google.cloud.bigquery.JobStatistics.fromPb(JobStatistics.java:1183)
	at com.google.cloud.bigquery.JobInfo$BuilderImpl.<init>(JobInfo.java:154)
	at com.google.cloud.bigquery.Job.fromPb(Job.java:485)
	at com.google.cloud.bigquery.BigQueryImpl$32.apply(BigQueryImpl.java:1127)
	at com.google.cloud.bigquery.BigQueryImpl$32.apply(BigQueryImpl.java:1124)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:786)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.cloud.PageImpl$PageIterator.computeNext(PageImpl.java:72)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:39)
```

**Comment by anthavio** [comment]
It works if JobListOption.fields is used and BigQuery.JobField.STATISTICS is not included in list
```scala
bigquery.listJobs(JobListOption.allUsers(), JobListOption.fields(BigQuery.JobField.ID ,BigQuery.JobField.STATUS))
```

**Comment by anthavio** [comment]
Also fails in version 1.103.0
