### ISSUE TITLE
Timestamp ofTimeMicroseconds(long microseconds) fails for epoch dates with microseconds

### ISSUE THREAD

**Issue by gmreddy278** [googleapis/google-cloud-java#7111]
com.google.cloud.Timestamp.ofTimeMicroseconds(long microseconds) fails with IllegalArgumentException if the given date is epoch and not truncated to seconds, in the concrete example, -8499613106649 epoch timestamp was used.

google-cloud-core version: 1.62.0

Stacktrace fragment:

java.lang.IllegalArgumentException: timestamp out of range: -8499613106649, 749440000
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:357)
	at com.google.cloud.Timestamp.ofTimeMicroseconds(Timestamp.java:96)

**Comment by gmreddy278** [comment]
Team, i tried adding `L` in the test case and it is working fine(below one).  
    ```
@Test
    public void timeStamp() {
        long microSeconds = -8499613106649L;
        Timestamp t = Timestamp.ofTimeMicroseconds(microSeconds);
    }
```
Is it possible that if you could append `L` at the end of the integer. So that it won't through an exception?
