### ISSUE TITLE
NPE when we tried to read the Dataobjects uing BigQuery API

### ISSUE THREAD

**Issue by spauldurai** [googleapis/google-cloud-java#7216]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-java/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: ANY
3. Java version: 1.8
4. google-cloud-java version(s):   
com.google.cloud  
google-cloud-bigquery  
 1.110.0

#### Steps to reproduce

NOT able to reproduce

#### Code example

```java

  Page<Dataset> datasets = bigquery.listDatasets(project.toLowerCase(), BigQuery.DatasetListOption.pageSize(100));
  Iterable<Dataset> dataset_iterator = datasets.iterateAll();
  for (Dataset dataset : dataset_iterator {
             System.out.println("Getting tables for DatasetId " + dataset.getDatasetId());
             Page<Table> tables = bigquery.listTables(datasetId, BigQuery.TableListOption.pageSize(100));
             Iterable<Table> table_iterator = tables.iterateAll();

             while (tables_iterator.hasNext()) {
                  try {
                         Table table =  tables_iterator.next();
                        System.out.println(table.toString());
                        System.out.println(table.getTableId().getTable());
                        System.out.println(table.getDefinition().getType());

                        if (table.getDefinition().getType().toString().equals("TABLE")) {
				System.out.println("table");
			}
	          } catch (Exception e) {
                     e.printStackTrace();
                  }
	     }
   }


```

#### Stack trace
```
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at com.google.cloud.bigquery.TimePartitioning$Type.valueOf(TimePartitioning.java:43)
	at com.google.cloud.bigquery.TimePartitioning.fromPb(TimePartitioning.java:145)
	at com.google.cloud.bigquery.StandardTableDefinition.fromPb(StandardTableDefinition.java:275)
	at com.google.cloud.bigquery.TableDefinition.fromPb(TableDefinition.java:151)
	at com.google.cloud.bigquery.TableInfo$BuilderImpl.<init>(TableInfo.java:188)
	at com.google.cloud.bigquery.Table.fromPb(Table.java:624)
	at com.google.cloud.bigquery.BigQueryImpl$21.apply(BigQueryImpl.java:847)
	at com.google.cloud.bigquery.BigQueryImpl$21.apply(BigQueryImpl.java:844)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:820)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.cloud.PageImpl$PageIterator.computeNext(PageImpl.java:72)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:156)
```

#### External references such as API reference guides used	

- ?	

#### Any additional information below	

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by spauldurai** [comment]
https://github.com/googleapis/java-bigquery/blob/b539f95965ddba6ce4fc5b6712ce1e38b8286bd7/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TimePartitioning.java#L145

**Comment by spauldurai** [comment]
Can someone please fix it asap ?
