### ISSUE TITLE
[GKE] ClusterManagerClient.getCluster throws Conscrypt error "UnsupportedOperationException"

### ISSUE THREAD

**Issue by ligao-databricks** [googleapis/google-cloud-java#7286]
## Environment details

1. Open JDK 8u242-b08-0ubuntu3-16.04
1. google-cloud-java version(s):

```xml
 <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-compute</artifactId>
            <version>0.118.0-alpha</version>
</dependency>

 <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-container</artifactId>
            <version>1.0.4</version>
</dependency>
```

#### Steps to reproduce

  1. Build a fixed credential provider:

```Scala
val clusterManagerSettings = ClusterManagerSettings.newBuilder
      .setCredentialsProvider(credsProvider)
      .build
 
 val clusterManagerClient = ClusterManagerClient.create(clusterManagerSettings)

 val clusterRes = clusterManagerClient.getCluster(
      s"projects/${projectId}/locations/${zone}/clusters/${clusterName}"
    )
```

The command will throw exception on the last line.

#### Stack trace
```
Caused by: gcp_java_shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at gcp_java_shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	... 16 more
Caused by: javax.net.ssl.SSLHandshakeException: java.lang.UnsupportedOperationException
	at org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:361)
	at org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1135)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1090)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:867)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:738)
	at org.conscrypt.Conscrypt.unwrap(Conscrypt.java:605)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.handler.ssl.ConscryptAlpnSslEngine.unwrap(ConscryptAlpnSslEngine.java:93)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:243)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1324)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at gcp_java_shaded.io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.security.cert.CertificateException: java.lang.UnsupportedOperationException
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1645)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:547)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1096)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1080)
	... 27 more
Caused by: java.lang.UnsupportedOperationException
	at javax.net.ssl.ExtendedSSLSession.getRequestedServerNames(ExtendedSSLSession.java:116)
	at sun.security.ssl.X509TrustManagerImpl.getRequestedServerNames(X509TrustManagerImpl.java:395)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:424)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:261)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at org.conscrypt.Platform.checkServerTrusted(Platform.java:329)
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1637)
	... 31 more
```

#### External references such as API reference guides used	
Tried the some potential workaround proposed here without success:
https://github.com/grpc/grpc-java/pull/6962/files

**Comment by ligao-databricks** [comment]
we figured out a fix by downgrading to lower version of `Conscrypt`.
