### ISSUE TITLE
QuickStart issue : Error while using PubSub Lite with Pubsub library

### ISSUE THREAD

**Issue by nrj179** [googleapis/google-cloud-java#7352]
Steps to reproduce : 

1. Create a new blank maven project.
2. Include pubsub lite and pubsub libraries in your pom.xml as described here.https://cloud.google.com/pubsub/lite/docs/reference/libraries
```
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-pubsublite</artifactId>
  <version>0.4.0</version>
</dependency>
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-pubsub</artifactId>
  <version>1.108.1</version>
</dependency>
```
3. Write a PublisherExample class as described here. https://cloud.google.com/pubsub/lite/docs/publishing
4. Create a fat jar using maven-assembly plugin.
5. Try to run the Publisher Example code.
6. Below error will be thrown : 

```
io.grpc.StatusException: INTERNAL: Panic! This is a bug!
	at io.grpc.Status.asException(Status.java:541) ~[stormjar.jar:na]
	at com.google.cloud.pubsublite.internal.ExtractStatus.toCanonical(ExtractStatus.java:41) ~[stormjar.jar:na]
	at com.google.cloud.pubsublite.PartitionLookupUtils.numPartitions(PartitionLookupUtils.java:38) ~[stormjar.jar:na]
	at com.google.cloud.pubsublite.internal.wire.RoutingPublisherBuilder$Builder.build(RoutingPublisherBuilder.java:64) ~[stormjar.jar:na]
	at com.google.cloud.pubsublite.cloudpubsub.PublisherSettings.instantiate(PublisherSettings.java:132) ~[stormjar.jar:na]
	at com.google.cloud.pubsublite.cloudpubsub.Publisher.create(Publisher.java:27) ~[stormjar.jar:na]
	at com.aeris.storm.components.CloudPubSubPublisher.buildLitePublisher(CloudPubSubPublisher.java:104) ~[stormjar.jar:na]
	at com.aeris.storm.components.publisher.PacketFeedPublisherBolt.prepare(PacketFeedPublisherBolt.java:51) ~[stormjar.jar:na]
	at backtype.storm.topology.BasicBoltExecutor.prepare(BasicBoltExecutor.java:43) [storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.executor$fn__3441$fn__3453.invoke(executor.clj:692) [storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.util$async_loop$fn__464.invoke(util.clj:461) [storm-core-0.9.3.jar:0.9.3]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:94) ~[stormjar.jar:na]
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:65) ~[stormjar.jar:na]
	at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:375) ~[stormjar.jar:na]
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider$1ExitIdleModeForTransport.run(ManagedChannelImpl.java:469) ~[stormjar.jar:na]
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95) ~[stormjar.jar:na]
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127) ~[stormjar.jar:na]
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:473) ~[stormjar.jar:na]
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:253) ~[stormjar.jar:na]
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:210) ~[stormjar.jar:na]
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32) ~[stormjar.jar:na]
	at com.google.cloud.pubsublite.Stubs$1$1.start(Stubs.java:92) ~[stormjar.jar:na]
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:314) ~[stormjar.jar:na]
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:288) ~[stormjar.jar:na]
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:200) ~[stormjar.jar:na]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132) ~[stormjar.jar:na]
	at com.google.cloud.pubsublite.proto.AdminServiceGrpc$AdminServiceBlockingStub.getTopicPartitions(AdminServiceGrpc.java:1161) ~[stormjar.jar:na]
	at com.google.cloud.pubsublite.internal.AdminClientImpl.lambda$getTopicPartitionCount$2(AdminClientImpl.java:131) ~[stormjar.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) ~[stormjar.jar:na]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) ~[stormjar.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) ~[stormjar.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
	... 1 common frames omitted
```

**Comment by nrj179** [comment]
As per the analysis, META-INF/services/io.grpc.LoadBalancerProvider is conflicting in both the pubsub and pubsub lite libraries. 
After updating the contents( please see below the new content) of META-INF/services/io.grpc.LoadBalancerProvider manually, it got working.

io.grpc.grpclb.GrpclbLoadBalancerProvider
io.grpc.internal.PickFirstLoadBalancerProvider
io.grpc.util.SecretRoundRobinLoadBalancerProvider$Provider
