### ISSUE TITLE
TimeoutException Google Cloud Logging flush()

### ISSUE THREAD

**Issue by sanjaypujare** [googleapis/google-cloud-java#7790]
#### Environment details

1. Cloud Logging flush()
2. OS type and vers: MacOS
3. Java version: 1.8
4. google-cloud-java version(s): 

#### Steps to reproduce

  1. Use Cloud logging with the latest version of Java
  2. Try to send logs to Cloud Logging backend

#### Code example

```java
// TODO
```

#### Stack trace
```
Any relevant stacktrace here.
```

#### External references such as API reference guides used	

- ?	

#### Any additional information below	

This is basically the same as https://github.com/googleapis/google-cloud-java/issues/5225 but we cannot reopen that issue hence opening a new one.

CC @DNVindhya pls fill in the details such as code example and stack trace

Also CC @elharo to see if he can help because of `protobuf-java` issue

**Comment by DNVindhya** [comment]
We are trying to use Google Cloud Logging Java Client library from grpc-java. 
Calling [logging.close( ) as part of the custom logging handler](https://github.com/DNVindhya/grpc-java/blob/o11y-cloudlogginghandler/observability/src/main/java/io/grpc/observability/logging/CloudLoggingHandler.java#L129) which calls flush( ) underneath raises following TimeoutException.

<h4>Stack Trace</h4>

```
java.util.concurrent.TimeoutException: Waited 6 seconds (plus 355085 nanoseconds delay) for ListFuture@2af9d539[status=PENDING, info=[futures=[com.google.api.core.ApiFutureToListenableFuture@5272be34]]]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:111)
        at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:68)
        at com.google.cloud.logging.LoggingImpl.flush(LoggingImpl.java:883)
        at com.google.cloud.logging.LoggingImpl.close(LoggingImpl.java:1098)
        at io.grpc.observability.logging.CloudLoggingHandler.close(CloudLoggingHandler.java:138)
        at java.logging/java.util.logging.LogManager.closeHandlers(LogManager.java:1470)
        at java.logging/java.util.logging.LogManager.resetLogger(LogManager.java:1485)
        at java.logging/java.util.logging.LogManager.resetLoggerContext(LogManager.java:1460)
        at java.logging/java.util.logging.LogManager.reset(LogManager.java:1445)
        at java.logging/java.util.logging.LogManager$Cleaner.run(LogManager.java:282)
```

Even when I used [LoggingExample](https://github.com/googleapis/java-logging/blob/main/samples/snippets/src/main/java/com/example/logging/WriteLogEntry.java) without any modification it gives similar exception as mentioned below.

```
java.util.concurrent.TimeoutException: Waited 6 seconds (plus 444903 nanoseconds delay) for ListFuture@70e0accd[status=PENDING, info=[futures=[com.google.api.core.ApiFutureToListenableFuture@7957dc72]]]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:111)
        at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:68)
        at com.google.cloud.logging.LoggingImpl.flush(LoggingImpl.java:883)
        at com.google.cloud.logging.LoggingImpl.close(LoggingImpl.java:1098)
        at io.grpc.observability.logging.CloudLoggingSample.main(CloudLoggingSample.java:54)
```

<h4>Environment Details</h4>       

Cloud Logging flush()
OS type and vers: Debian GNU/Linux 12 (rodete)
Java version: OpenJDK 11.0.12
google-cloud version(s): com.google.cloud:google-cloud-logging:3.6.1
