### ISSUE TITLE
com.google.cloud.redis.v1.it.ITSystemTest is flaky

### ISSUE THREAD

**Issue by meltsufin** [googleapis/google-cloud-java#8679]
```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1,452.943 s <<< FAILURE! - in com.google.cloud.redis.v1.it.ITSystemTest
[ERROR] com.google.cloud.redis.v1.it.ITSystemTest.testUpdateInstance  Time elapsed: 1,452.477 s  <<< ERROR!
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.DeadlineExceededException: Operation with name "projects/gcloud-devel/locations/us-central1/operations/operation-1666649961543-5ebcf2eec35c0-1ab7e373-a6c445d9" failed with status = GrpcStatusCode{transportCode=DEADLINE_EXCEEDED} and message = Operation took longer than expected and was aborted. Please try again.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:66)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:125)
	at com.google.cloud.redis.v1.it.ITSystemTest.testUpdateInstance(ITSystemTest.java:141)

```
https://source.cloud.google.com/results/invocations/f33bad19-a69c-40d2-b908-b3f76d762576/log

**Comment by alicejli** [comment]
Looks like this test hasn't failed in the last 10 days when I look at Fusion - let me know if we can close and re-open if needed.

**Comment by burkedavison** [comment]
No replication issues in nightly builds over the last couple months. Closing as no longer an issue.
