### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.

### ISSUE THREAD

**Issue by dalaopo** [googleapis/google-cloud-java#8980]
Im sorry，I wrote the demo according to the documentation
https://cloud.google.com/bigquery/docs/quickstarts/quickstart-client-libraries#before-you-begin
```
Exception in thread "main" java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:304)
	at com.google.cloud.bigquery.BigQueryOptions.<init>(BigQueryOptions.java:91)
	at com.google.cloud.bigquery.BigQueryOptions.<init>(BigQueryOptions.java:30)
	at com.google.cloud.bigquery.BigQueryOptions$Builder.build(BigQueryOptions.java:86)
	at com.google.cloud.bigquery.BigQueryOptions.getDefaultInstance(BigQueryOptions.java:161)
	at app.test.main(test.java:16)
```
But I get an error that I can't understand,how should i avoid
This is my 16 line content
```
BigQuery bigquery = BigQueryOptions.getDefaultInstance().getService();
```

**Comment by dalaopo** [comment]
> google云项目cloud cloud cloud cloud cloud的的cloud cloud cloud cloud可能未正确。。[您](https://cloud.google.com/java/docs/setup)您您[是否](https://cloud.google.com/docs/authentication/client-libraries)是否`GOOGLE_APPLICATION_CREDENTIALS`使用使用使用使用或或或或或或变量变量变量变量变量变量变量变量变量变量变量变量变量变量变量变量cloud cloud cloud cloud为为为为为[](https://cloud.google.com/java/docs/setup)[](https://cloud.google.com/docs/authentication/client-libraries)


Yes, thank you,it is my mistake，the reason is that I only configured system environment variables and did not configure user environment variables
