### ISSUE TITLE
getting "Task was cancelled" error after 4 or 5 minutes of runtime 

### ISSUE THREAD

**Issue by rajatg717** [googleapis/google-cloud-java#9404]
Hey , 
I am getting this error while running the program on intellij after 4 or 5 minutes of run.

Exception in thread "main" java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1543)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:586)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:463)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:99)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:73)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:131)
	at org.example.Importbuild.main(Importbuild.java:86)

I have defined following parameters of 120 minutes timeout units , although build will be still working in GCP platform which can be seen in build history but in intellij error appears in 4 or 5 minutes.

 Build response = cloudBuildClient.createBuildAsync(request).get(120, TimeUnit.MINUTES) 

What can be the reason of this?

**Comment by suztomo** [comment]
@rajatg717 Sorry for late response. Do you still see this is a problem?

**Comment by suztomo** [comment]
Please recreate an issue if this is still a problem.
