### ISSUE TITLE
accessSecretVersion throws grpc error using latest version 

### ISSUE THREAD

**Issue by avula-sudheer** [googleapis/google-cloud-java#9405]
I didn't see any updates to googleapis/java-secretmanager#822, Not sure if that is because it is in the closed state. Thus I am raising a new bug to see for any input here.

**Description**

Here is the sample code snippet that does access a secret with version as **latest**. 

        try (SecretManagerServiceClient client = SecretManagerServiceClient.create()) {

            // Build SecretVersionName based on project-id, secret name and version.
            SecretVersionName secretVersionName = SecretVersionName.of(projectId, name, version);
            // Access the secret version.
            AccessSecretVersionResponse response = client.accessSecretVersion(secretVersionName);
            // Get secret value from the response.
            String secretValue = response.getPayload().getData().toStringUtf8();
        }
        catch (Exception e) {
            throw new RuntimeException("Error while accessing secret: " + name + ", " + version + ". " + e.getMessage(), e);
        }

**Observation:**

This issue doesn't exist with the 2.2.0 library version and started to see it when upgrading the library from 2.2.0 to 2.3.1 and above

**Exception Trace:**

Caused by: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
   at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:112 undefined)
   at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41 undefined)
   at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86 undefined)
   at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66 undefined)
   at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97 undefined)
   at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67 undefined)
   at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132 undefined)
   at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31 undefined)
   at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270 undefined)
   at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:761 undefined)
   at com.google.common.util.concurrent.ForwardingListenableFuture.addListener(ForwardingListenableFuture.java:47 undefined)
   at com.google.api.core.ApiFutureToListenableFuture.addListener(ApiFutureToListenableFuture.java:51 undefined)
   at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1105 undefined)
   at com.google.api.core.ApiFutures.addCallback(ApiFutures.java:62 undefined)
   at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:67 undefined)
   at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:87 undefined)
   at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131 undefined)
   at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74 undefined)
   at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82 undefined)
   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515 undefined)
   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264 undefined)
   at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304 undefined)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128 undefined)
   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628 undefined) ... 1 more Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
   at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57 undefined)
   at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112 undefined)
   at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1279 undefined)
   at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1215 undefined)
   at com.******************************************.GoogleSecretRetriever.accessSecret(GoogleSecretRetriever.java:114 undefined)

Please let me know for more info.

**Comment by suztomo** [comment]
@avula-sudheer We haven't received similar problems. Would it possible to reproduce the issue in the client library another programming language?

https://cloud.google.com/secret-manager/docs/reference/libraries

**Comment by avula-sudheer** [comment]
> @avula-sudheer We haven't received similar problems. Would it possible to reproduce the issue in the client library another programming language?
> 
> https://cloud.google.com/secret-manager/docs/reference/libraries

Thanks for looking into this. Just to iterate, this issue is observed only with the latest version of the library, and reverting to the older version seems to work as expected. So, I doubt if this has any relation with the library in other languages.

**Comment by suztomo** [comment]
Client libraries share certain cross-language middleware and libraries (gRPC and Protobuf, notably). If newer Go library has this problem and not in older Go library, then we can suspect that layer.

**Comment by avula-sudheer** [comment]
@suztomo ,

I was able to create a simple cloud function in Java to rule out if any dependent libraries are causing this issue. 

I see the error with the latest version of library - https://mvnrepository.com/artifact/com.google.cloud/google-cloud-secretmanager/2.17.0

Do suggest how to conclude this?

Thanks

**Comment by suztomo** [comment]
@avula-sudheer Can I read the entire implementation of the function in addition to the code snippet?

@ddixit14 Can you try to reproduce the issue with the snippet in the description of this issue?

**Comment by avula-sudheer** [comment]
Hi @suztomo ,

Yes, here is the extract of the code that I used to retrieve the secret. This code when built with the older secret manager library work and fails with the newer version.

```
private String accessSecret(String name, String version) {
        try (SecretManagerServiceClient client = SecretManagerServiceClient.create()) {
            SecretVersionName secretVersionName = SecretVersionName.of(projectId, name, version);
            AccessSecretVersionResponse response = client.accessSecretVersion(secretVersionName);
            return response.getPayload().getData().toStringUtf8();
        }
        catch (Exception e) {
            throw new RuntimeException("Error while accessing secret: " + name + ", " + version + ". " + e.getMessage(), e);
        }
    }
```

Let me know for more info.

**Comment by avula-sudheer** [comment]
> @avula-sudheer Can I read the entire implementation of the function in addition to the code snippet?
> 
> @ddixit14 Can you try to reproduce the issue with the snippet in the description of this issue?

I am happy to share the sample code or demo the error from the cloud function execution. Do you want to schedule a meeting? Do suggest

**Comment by ddixit14** [comment]
Hey @avula-sudheer, can you share the sample code (maybe a github project?), describing the error, and how to reproduce it?

**Comment by avula-sudheer** [comment]
Hi @ddixit14 , I don't have it in a public Git repo. Rather it is in a internal enterprise repo. 

Let me know if you have an alternate way that I can show the issue.

**Comment by avula-sudheer** [comment]
Hi Team,

I started seeing below error messages and digging further into this lead me to the [Stackoverflow post](https://stackoverflow.com/questions/55484043/how-to-fix-could-not-find-policy-pick-first-with-google-tts-java-client). 

> Uncaught exception in the SynchronizationContext. Panic! java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
> ...

The solutions 1) [configuring `io.grpc.LoadBalancerProvider` file](https://stackoverflow.com/a/55654794/2938413), and 2) [specifying the `transformer` in `maven-shade` plugin](https://stackoverflow.com/a/71531071/2938413), discussed here worked. With these solutions, I no longer see the grpc error. 

Let me know if you recommend these solutions and your preference for each. Alao, any technical insights into it is much appreciated.

**Comment by suztomo** [comment]
> I started seeing

Would you explain what change you made before that?

**Comment by avula-sudheer** [comment]
> > I started seeing
> 
> Would you explain what change you made before that?

maven shade plugin was configured to exclude some libraries to make the uber jar thin and one of them is `io.grpc:grpc-grpclb`. Commenting out the exclusion, include this library in the uber/fat jar. Since then, I started seeing this additional error.

**Comment by avula-sudheer** [comment]
I observed that the exception trace has a slightly different message now.

> Caused by: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug! at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:110) at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41) at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86) at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66) at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84) at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127) at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286) at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:760) at com.google.common.util.concurrent.ForwardingListenableFuture.addListener(ForwardingListenableFuture.java:45) at com.google.api.core.ApiFutureToListenableFuture.addListener(ApiFutureToListenableFuture.java:49) at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1100) at com.google.api.core.ApiFutures.addCallback(ApiFutures.java:79) at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:67) at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:87) at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63) at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41) at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75) at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126) at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87) at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1396) at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1326) at com.voltage.securedata.cloud.gcp.util.GoogleSecretRetriever.accessSecret(GoogleSecretRetriever.java:116) ... 40 more Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) ... 44 more 
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug! at io.grpc.Status.asRuntimeException(Status.java:539) at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:548) at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541) at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567) at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716) at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ... 1 more 
Caused by: java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files. at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:94) at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:61) at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:413) at io.grpc.internal.ManagedChannelImpl$RealChannel$2.run(ManagedChannelImpl.java:969) at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94) at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126) at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:966) at com.google.api.gax.grpc.GrpcChannelUUIDInterceptor.interceptCall(GrpcChannelUUIDInterceptor.java:52) at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156) at com.google.api.gax.grpc.GrpcHeaderInterceptor.interceptCall(GrpcHeaderInterceptor.java:80) at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156) at com.google.api.gax.grpc.GrpcMetadataHandlerInterceptor.interceptCall(GrpcMetadataHandlerInterceptor.java:54) at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156) at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:908) at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63) at com.google.api.gax.grpc.ChannelPool$AffinityChannel.newCall(ChannelPool.java:516) at com.google.api.gax.grpc.ChannelPool.newCall(ChannelPool.java:145) at com.google.api.gax.grpc.GrpcClientCalls.newCall(GrpcClientCalls.java:99) at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:60) at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:68) at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64) at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:87) at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63) at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41) at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75) at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126) at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87) at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1396) at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1326) 
....

**Comment by suztomo** [comment]
In general shadng is a renaming of packages of classes or removal of (seemingly) unnecessary classes. Some classes use reflection to access other classes via package name and class name. There's no guarantee that shading always works without proper care in shading configurations. I'm afraid that our team cannot help the configurations.

If you encounter problems without shading, please create a new issue.
