### ISSUE TITLE
Compute : Can't update Loadbalance BackendService resource

### ISSUE THREAD

**Issue by scutlxp** [googleapis/google-cloud-java#9433]
Version used : 0.119.3-alpha
API `com.google.cloud.compute.v1.BackendServiceClient.updateBackendService()`

I want to update a already created BackendService but an exception was thrown. I'm not sure if it is a bug of a misunderstanding from my part, but if it is a misunderstanding, it would help to clarify this in the doc.

Below is my code:
``` java
try (BackendServiceClient client = BackendServiceClient.create()) {
   String projectName = "myProject";
   String oldBackendServiceName = "myBackendService";

   ProjectGlobalBackendServiceName projectBackendServiceName = ProjectGlobalBackendServiceName.of(oldBackendServiceName , projectName);

   // oldBackendService is an already created BackendService
   BackendService oldBackendService = client.getBackendService(projectBackendServiceName);

   if (oldBackendService  != null) {
       BackendService newBackendService = BackendService.newBuilder(oldBackendService)
       .setTimeoutSec(60)
       .setFingerprint(oldBackendService.getFingerprint())
       .build();

      Operation operation = client.updateBackendService(projectBackendServiceName, newBackendService, new ArrayList<>());
   }
}
````

Then the error is as follow:
```java
com.google.api.gax.rpc.InvalidArgumentException: Bad Request
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:90)
	at com.google.api.gax.httpjson.HttpJsonExceptionCallable$ExceptionTransformingFuture.onFailure(HttpJsonExceptionCallable.java:106)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1041)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.core.SettableApiFuture.setException(SettableApiFuture.java:52)
	at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.compute.v1.BackendServiceClient.updateBackendService(BackendServiceClient.java:1544)
		at com.google.cloud.compute.v1.BackendServiceClient.updateBackendService(BackendServiceClient.java:1468)
		at xxx (my internal code)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
		at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
		at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
		at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
PUT https://compute.googleapis.com/compute/v1/projects/xxx/global/backendServices/backend-server-ece995c379234485bd65a906c824168d
{
  "error": {
    "code": 400,
    "message": "Required field 'resource.fingerprint' not specified",
    "errors": [
      {
        "message": "Required field 'resource.fingerprint' not specified",
        "domain": "global",
        "reason": "required"
      }
    ]
  }
}

	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1113)
	at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:143)
	... 7 common frames omitted
Result(status=0, msg=Insert instance group to backendService error: 400 Bad Request
PUT https://compute.googleapis.com/compute/v1/projects/test-project/global/backendServices/backend-server-ece995c379234485bd65a906c824168d
{
  "error": {
    "code": 400,
    "message": "Required field 'resource.fingerprint' not specified",
    "errors": [
      {
        "message": "Required field 'resource.fingerprint' not specified",
        "domain": "global",
        "reason": "required"
      }
    ]
  }
}
, data=null)
```
The error message is 'resource.fingerprint' not specified. But I have set this filed when build new BackendService.
Is there something wrong with my usage?

**Comment by burkedavison** [comment]
Closing due to lack of response. Please reopen if this is still an issue.
