### ISSUE TITLE
New Client check is failing

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#9553]
It started failing today. https://github.com/googleapis/google-cloud-java/actions/runs/5294045532/jobs/9583003899?pr=9552

```
Run python generation/new_client/new-client.py generate \
  python generation/new_client/new-client.py generate \
      --api_shortname=${API_SHORT_NAME} \
      --proto-path=google/api/${API_SHORT_NAME} \
      --name-pretty="${API_PRETTY_NAME}" \
      --product-docs="https://github.com/googleapis/google-cloud-java/tree/main/java-${API_SHORT_NAME}" \
      --api-description="${API_PRETTY_NAME} Client lets you use ${API_PRETTY_NAME} API." \
      --googleapis-gen-url=***github.com/googleapis/googleapis-gen.git
  shell: /usr/bin/bash -e {0}
  env:
    API_SHORT_NAME: apikeys
    API_PRETTY_NAME: API Keys
    pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x64
    Python[2](https://github.com/googleapis/google-cloud-java/actions/runs/5294045532/jobs/9583003899?pr=9552#step:11:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/googleapis/google-cloud-java/actions/runs/5294045532/jobs/9583003899?pr=9552#step:11:3).9.17/x6[4](https://github.com/googleapis/google-cloud-java/actions/runs/5294045532/jobs/9583003899?pr=9552#step:11:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.19-7/x64
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.19-7/x64
gcr.io/cloud-devrel-public-resources/owlbot-java:latest
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/googleapis/googleapis-gen.git/'
/home/runner/work/google-cloud-java/google-cloud-java/generation/new_client
Creating a new module /home/runner/work/google-cloud-java/google-cloud-java/java-apikeys
Cloning googleapis-gen...
Traceback (most recent call last):
  File "/home/runner/work/google-cloud-java/google-cloud-java/generation/new_client/new-client.py", line 38[5](https://github.com/googleapis/google-cloud-java/actions/runs/5294045532/jobs/9583003899?pr=9552#step:11:5), in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.9.17/x[6](https://github.com/googleapis/google-cloud-java/actions/runs/5294045532/jobs/9583003899?pr=9552#step:11:6)4/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1[7](https://github.com/googleapis/google-cloud-java/actions/runs/5294045532/jobs/9583003899?pr=9552#step:11:7)/x64/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/google-cloud-java/google-cloud-java/generation/new_client/new-client.py", line 266, in generate
    subprocess.check_call(["git", "clone", "-q", googleapis_gen_url, "./gen/googleapis-gen"], cwd=workdir)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '-q', '***github.com/googleapis/googleapis-gen.git', './gen/googleapis-gen']' returned non-zero exit status 12[8](https://github.com/googleapis/google-cloud-java/actions/runs/5294045532/jobs/9583003899?pr=9552#step:11:8).
```

**Comment by meltsufin** [comment]
Looks like an auth problem to the private googleapis-gen repo?

**Comment by suztomo** [comment]
It was temporary failure. The subsequent job succeeded https://github.com/googleapis/google-cloud-java/actions/runs/5294198019/jobs/9583275647
