### ISSUE TITLE
Token not getting refreshed for ga4 admin api.

### ISSUE THREAD

**Issue by sagarkhilrrani** [googleapis/google-cloud-java#9832]
Hi Team, 

For Google Analytics 4 Admin Api,  New Access Token is not getting generated for Admin API after getting expired. ideally the token should get refreshed similar to Data API. As Conversion events and Properties are fetched through Admin API we are unable to get the updated list of conversion events/properties.

This issue is happening while using Google libraries. So, can you please check and escalate this with your engineering team, as this will affect all our clients.

I have attached a file where in following things are added :- 
a.Part of code which are implementing at our end.
b.Error which we are getting from channel side

Thanks and Regards
Sagar Khilrani

[GA4 admin API issue.docx](https://github.com/googleapis/google-cloud-java/files/12597819/GA4.admin.API.issue.docx)

**Comment by diegomarquezp** [comment]
From Doc (opened in Google Docs)
### 1.Code which we are implementing at out end :-

```java
// Data API
        Object expiresIn // get from mongo that we have git when we authenticated ofr the first time
        Long expiry = 0L;
        if (expiresIn instanceof Long) {
            expiry = (Long) expiresIn;
        }
 
        final UserCredentials credentials =
            UserCredentials.newBuilder()
                           .setClientId( // project Client Id)
                           .setClientSecret(// project Client Secret)
                           .setRefreshToken(// refersh token received on firts autrhentication)
                           .setAccessToken(new AccessToken( // refersh token received on firts autrhentication// , new Date(expiry)))
                           .build();
        credentials.addChangeListener(new CredentialsChangedListener() {
            @Override
            public void onChanged(OAuth2Credentials credentials) throws IOException {
                AccessToken accessToken = credentials.getAccessToken();
                String newRefreshToken = null;
                if (credentials instanceof UserCredentials) {
                    UserCredentials userCredentials = (UserCredentials) credentials;
                    newRefreshToken = userCredentials.getRefreshToken();
                }
                try {

                    oldExpiresTime ->  expiretime we git during last authentoication
                    boolean appAccountNeedsUpdate = false;
                    if (accessToken.getExpirationTime() != null && accessToken.getExpirationTime().getTime() > oldExpiresTime) {
 
                    
                       // should save the new expit time
                    }
                    if (!SprStringUtils.equalsWithBlankCheck(accessToken.getTokenValue(), old accesstoken from last authentication)) {
                         // update the access token
                        appAccountNeedsUpdate = true;
                    }
                    if (StringUtils.isNotBlank(newRefreshToken) && !SprStringUtils.equalsWithBlankCheck(newRefreshToken,
                                                                                                        // old refreshTokne from last authentocation))) {
                       // update the referesh token
                        appAccountNeedsUpdate = true;
                    }
                    if (appAccountNeedsUpdate) {
                       // save all new details rfresh token, accesstoken, expiry time
                    }
                } catch (Exception e) {
                    throw new IOException("Error occurred while updating google analytics account credentials and properties in Database", e);
                }
            }
        });
 
        try {
            credentials.refreshIfExpired();
        } catch (Exception e) {
            LOG.error("Credential refresh error happened", e);

        }
 
        // Create transport provider with HTTP support (GRPC is also supported in Libraries)
        final TransportChannelProvider transportChannelProvider = BetaAnalyticsDataSettings.defaultHttpJsonTransportProviderBuilder().build();
 
        // Create the settings for the AnalyticsAdminServiceClient
        final AnalyticsAdminServiceSettings analyticsAdminServiceSettings =
            AnalyticsAdminServiceSettings.newBuilder().setTransportChannelProvider(transportChannelProvider)
                                         .setCredentialsProvider(new CredentialsProvider() {
                                             @Override
                                             public Credentials getCredentials() throws IOException {
                                                 return credentials;
                                             }
                                         }).build();
 

        // Create the AnalyticsAdminServiceClient
        analyticsAdminServiceClient = AnalyticsAdminServiceClient.create(analyticsAdminServiceSettings);
```

### 2.Error which we are Getting from channel:-

```
com.google.auth.oauth2.GoogleAuthException: com.google.api.client.http.HttpResponseException: 401 Unauthorized\nPOST https://oauth2.googleapis.com/token
at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:129)
at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:145)
at com.google.auth.oauth2.UserCredentials.doRefreshAccessToken(UserCredentials.java:272)
at com.google.auth.oauth2.UserCredentials.refreshAccessToken(UserCredentials.java:177)
at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269)
at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:581)
at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:232)
at com.google.auth.oauth2.OAuth2Credentials.refreshIfExpired(OAuth2Credentials.java:203)
at com.spr.listening.external.googleAnalytics4.GoogleAnalytics4APIClientImpl.initClient(GoogleAnalytics4APIClientImpl.java:264)
at com.spr.listening.external.googleAnalytics4.GoogleAnalytics4APIClientImpl.<init>(GoogleAnalytics4APIClientImpl.java:87)
at com.spr.ops.channels.ganalytics4.GoogleAnalytics4ServiceImpl.getConversionEvents(GoogleAnalytics4ServiceImpl.java:776)
at com.spr.ops.channels.ganalytics4.GoogleAnalytics4ServiceImpl.getAllGoogleAnalytics4Measurements(GoogleAnalytics4ServiceImpl.java:258)
at com.spr.graphql.api.GoogleAnalytics4GraphqlAPI.getAllGoogleAnalytics4Measurements(GoogleAnalytics4GraphqlAPI.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at io.leangen.graphql.metadata.execution.FixedMethodInvoker.execute(FixedMethodInvoker.java:22)
at io.leangen.graphql.metadata.Resolver.resolve(Resolver.java:102)
at io.leangen.graphql.execution.OperationExecutor.lambda$execute$1(OperationExecutor.java:93)
at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:103)
at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:99)
at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:58)
at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:272)
at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:205)
at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:62)
at graphql.execution.Execution.executeOperation(Execution.java:164)
at graphql.execution.Execution.execute(Execution.java:105)
at graphql.GraphQL.execute(GraphQL.java:566)
at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:489)
at graphql.GraphQL.executeAsync(GraphQL.java:448)
at graphql.kickstart.execution.GraphQLInvoker.executeAsync(GraphQLInvoker.java:26)
at graphql.kickstart.execution.GraphQLInvoker.queryAsync(GraphQLInvoker.java:35)
at graphql.kickstart.servlet.HttpRequestInvokerImpl.invoke(HttpRequestInvokerImpl.java:78)
at graphql.kickstart.servlet.HttpRequestInvokerImpl.execute(HttpRequestInvokerImpl.java:37)
at graphql.kickstart.servlet.HttpRequestHandlerImpl.handle(HttpRequestHandlerImpl.java:39)
at graphql.kickstart.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:82)
at graphql.kickstart.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:74)
at com.spr.servlet.SprGraphQLServlet.doPost(SprGraphQLServlet.java:100)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:528)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at com.spr.filters.OperationModeFilter.doFilter(OperationModeFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at com.spr.filters.CSRFFilter.doFilterInternal(CSRFFilter.java:200)
at com.spr.filters.CSRFFilter.doFilter(CSRFFilter.java:105)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at com.spr.filters.NoCacheFilter.doFilter(NoCacheFilter.java:31)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at com.spr.utils.ContextLoggingFilter.doFilter(ContextLoggingFilter.java:100)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at com.spr.filters.AppSessionManagerFilter.doFilter(AppSessionManagerFilter.java:67)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at com.spr.filters.AuthFilter.doFilter(AuthFilter.java:361)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
at com.spr.filt
```

**Comment by diegomarquezp** [comment]
Hi @sagarkhilrrani , thanks for reporting this.
I tagged our auth team in case they know about this use case.

Would you mind sharing a full reproducer?

Also, for quicker response times consider using our [support hub](https://cloud.google.com/support-hub) if you have a support plan.

Thanks!

**Comment by lqiu96** [comment]
Going to close this issue as we haven't got a response. Feel free to re-open this issue.
