### ISSUE TITLE
New Client / generate fails "fatal: Authentication failed for 'https://github.com/googleapis/googleapis-gen.git/'"

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#9851]
https://github.com/googleapis/google-cloud-java/actions/runs/6236607444/job/16937159859?pr=9849#step:11:23

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/googleapis/googleapis-gen.git/'
```

```
python generation/new_client/new-client.py generate \
      --api_shortname=${API_SHORT_NAME} \
      --proto-path=google/api/${API_SHORT_NAME} \
      --name-pretty="${API_PRETTY_NAME}" \
      --product-docs="[https://github.com/googleapis/google-cloud-java/tree/main/java-${API_SHORT_NAME}](https://github.com/googleapis/google-cloud-java/tree/main/java-$%7BAPI_SHORT_NAME%7D)" \
      --api-description="${API_PRETTY_NAME} Client lets you use ${API_PRETTY_NAME} API." \
      --googleapis-gen-url=***github.com/googleapis/googleapis-gen.git
...
gcr.io/cloud-devrel-public-resources/owlbot-java:latest
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/googleapis/googleapis-gen.git/'
/home/runner/work/google-cloud-java/google-cloud-java/generation/new_client
Creating a new module /home/runner/work/google-cloud-java/google-cloud-java/java-apikeys
Cloning googleapis-gen...
Traceback (most recent call last):
  File "/home/runner/work/google-cloud-java/google-cloud-java/generation/new_client/new-client.py", line 385, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/google-cloud-java/google-cloud-java/generation/new_client/new-client.py", line [26](https://github.com/googleapis/google-cloud-java/actions/runs/6236607444/job/16937159859?pr=9849#step:11:27)6, in generate
    subprocess.check_call(["git", "clone", "-q", googleapis_gen_url, "./gen/googleapis-gen"], cwd=workdir)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '-q', '***github.com/googleapis/googleapis-gen.git', './gen/googleapis-gen']' returned non-zero exit status 1[28](https://github.com/googleapis/google-cloud-java/actions/runs/6236607444/job/16937159859?pr=9849#step:11:29).
```

**Comment by suztomo** [comment]
So if one finds the error message, create a pull request without creating a forked repository. Create a branch in this googleapis/google-cloud-java repository first and then create a pull request.
