### ISSUE TITLE
`ITSystemTest.updateTenantTest ` caused nightly build failed

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/google-cloud-java#9867]
From [graalvm nightly build](https://fusion2.corp.google.com/invocations/4e64e2e3-0763-4709-825d-fe80cacb65d9/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-cloud-java%2Fnightly%2Fgraalvm-sub-jobs%2Fnative%2Fgraalvm-native-1;config=default/log)
```
08:07:46:694 [ERROR] com.google.cloud.talent.v4beta1.it.ITSystemTest.updateTenantTest  Time elapsed: 0.066 s  <<< ERROR!
com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:110)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
```

**Comment by diegomarquezp** [comment]
This also fails in presubmits https://github.com/googleapis/google-cloud-java/pull/9881#issuecomment-1734415818

**Comment by diegomarquezp** [comment]
https://github.com/googleapis/google-cloud-java/pull/9892#issuecomment-1735944441 is a good question. I'm reopening this in order to determine the root cause

**Comment by suztomo** [comment]
"com.google.cloud.talent.v4beta1" is an old version. We can remove the test.

**Comment by suztomo** [comment]
Or migrate to the latest version.
